// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminAdjustCurrency = `-- name: AdminAdjustCurrency :one
UPDATE app.players SET gold = gold + $2, diamonds = diamonds + $3 WHERE id = $1 RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day
`

type AdminAdjustCurrencyParams struct {
	ID       uuid.UUID
	Gold     int64
	Diamonds int64
}

func (q *Queries) AdminAdjustCurrency(ctx context.Context, arg AdminAdjustCurrencyParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, adminAdjustCurrency, arg.ID, arg.Gold, arg.Diamonds)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
	)
	return i, err
}

const adminSetPlayerState = `-- name: AdminSetPlayerState :one
UPDATE app.players SET state = $2 WHERE id = $1 RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day
`

type AdminSetPlayerStateParams struct {
	ID    uuid.UUID
	State string
}

func (q *Queries) AdminSetPlayerState(ctx context.Context, arg AdminSetPlayerStateParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, adminSetPlayerState, arg.ID, arg.State)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
	)
	return i, err
}

const battleStats = `-- name: BattleStats :one
SELECT
  count(*)::bigint AS battles,
  count(*) FILTER (WHERE attacker_won)::bigint AS attacker_wins,
  coalesce(sum(gold_stolen), 0)::bigint AS gold_moved,
  coalesce(avg(rounds), 0)::float AS avg_rounds
FROM app.battles
WHERE created_at > now() - ($1::int * interval '1 day')
`

type BattleStatsRow struct {
	Battles      int64
	AttackerWins int64
	GoldMoved    int64
	AvgRounds    float64
}

func (q *Queries) BattleStats(ctx context.Context, dollar_1 int32) (BattleStatsRow, error) {
	row := q.db.QueryRow(ctx, battleStats, dollar_1)
	var i BattleStatsRow
	err := row.Scan(
		&i.Battles,
		&i.AttackerWins,
		&i.GoldMoved,
		&i.AvgRounds,
	)
	return i, err
}

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM admin.users
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminSession = `-- name: CreateAdminSession :one
INSERT INTO admin.sessions (admin_id, token_hash, expires_at) VALUES ($1,$2,$3) RETURNING id, admin_id, token_hash, expires_at, revoked_at, created_at
`

type CreateAdminSessionParams struct {
	AdminID   uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (AdminSession, error) {
	row := q.db.QueryRow(ctx, createAdminSession, arg.AdminID, arg.TokenHash, arg.ExpiresAt)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin.users (username, password_hash, role) VALUES ($1,$2,$3) RETURNING id, username, password_hash, role, disabled, created_at, last_login_at
`

type CreateAdminUserParams struct {
	Username     string
	PasswordHash string
	Role         string
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdminUser, arg.Username, arg.PasswordHash, arg.Role)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, username, password_hash, role, disabled, created_at, last_login_at FROM admin.users WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, password_hash, role, disabled, created_at, last_login_at FROM admin.users WHERE lower(username) = lower($1)
`

func (q *Queries) GetAdminByUsername(ctx context.Context, lower string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, lower)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getAdminSession = `-- name: GetAdminSession :one
SELECT s.id, s.admin_id, s.token_hash, s.expires_at, s.revoked_at, s.created_at, u.username, u.role, u.disabled
FROM admin.sessions s JOIN admin.users u ON u.id = s.admin_id
WHERE s.token_hash = $1
`

type GetAdminSessionRow struct {
	ID        uuid.UUID
	AdminID   uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
	Username  string
	Role      string
	Disabled  bool
}

func (q *Queries) GetAdminSession(ctx context.Context, tokenHash []byte) (GetAdminSessionRow, error) {
	row := q.db.QueryRow(ctx, getAdminSession, tokenHash)
	var i GetAdminSessionRow
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Username,
		&i.Role,
		&i.Disabled,
	)
	return i, err
}

const goldFlows = `-- name: GoldFlows :many
SELECT reason,
       sum(CASE WHEN delta > 0 THEN delta ELSE 0 END)::bigint AS created,
       sum(CASE WHEN delta < 0 THEN -delta ELSE 0 END)::bigint AS destroyed,
       count(*)::bigint AS entries
FROM app.gold_ledger
WHERE created_at > now() - ($1::int * interval '1 day')
GROUP BY reason
ORDER BY greatest(sum(CASE WHEN delta > 0 THEN delta ELSE 0 END),
                  sum(CASE WHEN delta < 0 THEN -delta ELSE 0 END)) DESC
`

type GoldFlowsRow struct {
	Reason    string
	Created   int64
	Destroyed int64
	Entries   int64
}

// Economy health: what created gold and what destroyed it, by reason.
func (q *Queries) GoldFlows(ctx context.Context, dollar_1 int32) ([]GoldFlowsRow, error) {
	rows, err := q.db.Query(ctx, goldFlows, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GoldFlowsRow{}
	for rows.Next() {
		var i GoldFlowsRow
		if err := rows.Scan(
			&i.Reason,
			&i.Created,
			&i.Destroyed,
			&i.Entries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAudit = `-- name: ListAudit :many
SELECT id, admin_id, admin_name, action, subject, before, after, note, created_at FROM admin.audit_log ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListAudit(ctx context.Context, limit int32) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAudit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAuditLog{}
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.AdminName,
			&i.Action,
			&i.Subject,
			&i.Before,
			&i.After,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playerCounts = `-- name: PlayerCounts :one
SELECT
  count(*) FILTER (WHERE NOT is_bot)::bigint AS players,
  count(*) FILTER (WHERE is_bot)::bigint AS bots,
  count(*) FILTER (WHERE NOT is_bot AND last_seen_at > now() - interval '1 day')::bigint AS active_1d,
  count(*) FILTER (WHERE NOT is_bot AND last_seen_at > now() - interval '7 days')::bigint AS active_7d,
  count(*) FILTER (WHERE NOT is_bot AND created_at > now() - interval '1 day')::bigint AS new_1d,
  coalesce(sum(gold) FILTER (WHERE NOT is_bot), 0)::bigint AS gold_held,
  coalesce(avg(level) FILTER (WHERE NOT is_bot), 0)::float AS avg_level
FROM app.players
`

type PlayerCountsRow struct {
	Players  int64
	Bots     int64
	Active1d int64
	Active7d int64
	New1d    int64
	GoldHeld int64
	AvgLevel float64
}

func (q *Queries) PlayerCounts(ctx context.Context) (PlayerCountsRow, error) {
	row := q.db.QueryRow(ctx, playerCounts)
	var i PlayerCountsRow
	err := row.Scan(
		&i.Players,
		&i.Bots,
		&i.Active1d,
		&i.Active7d,
		&i.New1d,
		&i.GoldHeld,
		&i.AvgLevel,
	)
	return i, err
}

const revokeAdminSession = `-- name: RevokeAdminSession :exec
UPDATE admin.sessions SET revoked_at = now() WHERE token_hash = $1
`

func (q *Queries) RevokeAdminSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeAdminSession, tokenHash)
	return err
}

const searchPlayers = `-- name: SearchPlayers :many
SELECT id, username, display_name, level, gold, diamonds, state, is_bot,
       kingdom_id, created_at, last_seen_at
FROM app.players
WHERE lower(username) LIKE lower($1) OR lower(display_name) LIKE lower($1)
ORDER BY last_seen_at DESC
LIMIT 50
`

type SearchPlayersRow struct {
	ID          uuid.UUID
	Username    string
	DisplayName string
	Level       int32
	Gold        int64
	Diamonds    int64
	State       string
	IsBot       bool
	KingdomID   *uuid.UUID
	CreatedAt   time.Time
	LastSeenAt  time.Time
}

func (q *Queries) SearchPlayers(ctx context.Context, lower string) ([]SearchPlayersRow, error) {
	rows, err := q.db.Query(ctx, searchPlayers, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlayersRow{}
	for rows.Next() {
		var i SearchPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Level,
			&i.Gold,
			&i.Diamonds,
			&i.State,
			&i.IsBot,
			&i.KingdomID,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAdminLogin = `-- name: TouchAdminLogin :exec
UPDATE admin.users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) TouchAdminLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAdminLogin, id)
	return err
}

const writeAudit = `-- name: WriteAudit :exec
INSERT INTO admin.audit_log (admin_id, admin_name, action, subject, before, after, note)
VALUES ($1,$2,$3,$4,$5,$6,$7)
`

type WriteAuditParams struct {
	AdminID   *uuid.UUID
	AdminName string
	Action    string
	Subject   *string
	Before    []byte
	After     []byte
	Note      string
}

func (q *Queries) WriteAudit(ctx context.Context, arg WriteAuditParams) error {
	_, err := q.db.Exec(ctx, writeAudit,
		arg.AdminID,
		arg.AdminName,
		arg.Action,
		arg.Subject,
		arg.Before,
		arg.After,
		arg.Note,
	)
	return err
}
