// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ads.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAdWatchesPaidSince = `-- name: CountAdWatchesPaidSince :one
SELECT count(*)::bigint FROM app.ad_watches
WHERE player_id = $1 AND paid_at >= $2
`

type CountAdWatchesPaidSinceParams struct {
	PlayerID uuid.UUID
	Since    *time.Time
}

// What the lord has actually been PAID for since a moment: the day's allowance
// is counted from watches that came back, never from taps. A watch started and
// abandoned cost the lord nothing and must cost them nothing.
func (q *Queries) CountAdWatchesPaidSince(ctx context.Context, arg CountAdWatchesPaidSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdWatchesPaidSince, arg.PlayerID, arg.Since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deskAds = `-- name: DeskAds :one
SELECT count(*) FILTER (WHERE paid_at IS NOT NULL)::bigint AS paid,
       count(*)::bigint AS started,
       count(DISTINCT player_id) FILTER (WHERE paid_at IS NOT NULL)::bigint AS lords,
       coalesce(sum(diamonds), 0)::bigint AS diamonds
FROM app.ad_watches
WHERE created_at >= $1
`

type DeskAdsRow struct {
	Paid     int64
	Started  int64
	Lords    int64
	Diamonds int64
}

// What the desk reads: what the herald paid in a window, and to how many lords.
func (q *Queries) DeskAds(ctx context.Context, since time.Time) (DeskAdsRow, error) {
	row := q.db.QueryRow(ctx, deskAds, since)
	var i DeskAdsRow
	err := row.Scan(
		&i.Paid,
		&i.Started,
		&i.Lords,
		&i.Diamonds,
	)
	return i, err
}

const getAdWatch = `-- name: GetAdWatch :one
SELECT id, player_id, unit, created_at, expires_at, transaction_id, paid_at, diamonds, key_id FROM app.ad_watches WHERE id = $1
`

// The ticket a callback names.
func (q *Queries) GetAdWatch(ctx context.Context, id uuid.UUID) (AppAdWatch, error) {
	row := q.db.QueryRow(ctx, getAdWatch, id)
	var i AppAdWatch
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Unit,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.TransactionID,
		&i.PaidAt,
		&i.Diamonds,
		&i.KeyID,
	)
	return i, err
}

const lastAdWatchPaidAt = `-- name: LastAdWatchPaidAt :one
SELECT coalesce(max(paid_at), to_timestamp(0))::timestamptz AS last_paid
FROM app.ad_watches
WHERE player_id = $1
`

// When this lord was last paid for one, for the cooldown between adverts.
func (q *Queries) LastAdWatchPaidAt(ctx context.Context, playerID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, lastAdWatchPaidAt, playerID)
	var last_paid time.Time
	err := row.Scan(&last_paid)
	return last_paid, err
}

const liveAdWatch = `-- name: LiveAdWatch :one
SELECT id, player_id, unit, created_at, expires_at, transaction_id, paid_at, diamonds, key_id FROM app.ad_watches
WHERE player_id = $1 AND paid_at IS NULL AND expires_at > $2
ORDER BY created_at DESC
LIMIT 1
`

type LiveAdWatchParams struct {
	PlayerID uuid.UUID
	Now      time.Time
}

// This lord's watch in flight, if there is one: unpaid and not yet expired.
// One at a time is what keeps a tap from minting tickets by the thousand.
func (q *Queries) LiveAdWatch(ctx context.Context, arg LiveAdWatchParams) (AppAdWatch, error) {
	row := q.db.QueryRow(ctx, liveAdWatch, arg.PlayerID, arg.Now)
	var i AppAdWatch
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Unit,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.TransactionID,
		&i.PaidAt,
		&i.Diamonds,
		&i.KeyID,
	)
	return i, err
}

const lockAdWatch = `-- name: LockAdWatch :one
SELECT id, player_id, unit, created_at, expires_at, transaction_id, paid_at, diamonds, key_id FROM app.ad_watches WHERE id = $1 FOR UPDATE
`

// The same, locked, for the payment about to be made against it.
func (q *Queries) LockAdWatch(ctx context.Context, id uuid.UUID) (AppAdWatch, error) {
	row := q.db.QueryRow(ctx, lockAdWatch, id)
	var i AppAdWatch
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Unit,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.TransactionID,
		&i.PaidAt,
		&i.Diamonds,
		&i.KeyID,
	)
	return i, err
}

const payAdWatch = `-- name: PayAdWatch :one
UPDATE app.ad_watches
SET transaction_id = $1, paid_at = $2,
    diamonds = $3, key_id = $4
WHERE id = $5 AND paid_at IS NULL
RETURNING id, player_id, unit, created_at, expires_at, transaction_id, paid_at, diamonds, key_id
`

type PayAdWatchParams struct {
	TransactionID *string
	Now           *time.Time
	Diamonds      int64
	KeyID         pgtype.Int8
	ID            uuid.UUID
}

// The payment. The WHERE is the guard: a second callback for the same watch
// writes nothing, and the unique index on the transaction id catches a second
// callback that named a different ticket.
func (q *Queries) PayAdWatch(ctx context.Context, arg PayAdWatchParams) (AppAdWatch, error) {
	row := q.db.QueryRow(ctx, payAdWatch,
		arg.TransactionID,
		arg.Now,
		arg.Diamonds,
		arg.KeyID,
		arg.ID,
	)
	var i AppAdWatch
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Unit,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.TransactionID,
		&i.PaidAt,
		&i.Diamonds,
		&i.KeyID,
	)
	return i, err
}

const purgeAdWatches = `-- name: PurgeAdWatches :execrows
DELETE FROM app.ad_watches
WHERE (paid_at IS NULL AND expires_at < $1)
   OR (paid_at IS NOT NULL AND paid_at < $2)
`

type PurgeAdWatchesParams struct {
	Now        time.Time
	KeepBefore *time.Time
}

// Tickets nobody came back for, and payments old enough to be history. The
// sweep keeps the table the size of what it is actually for.
func (q *Queries) PurgeAdWatches(ctx context.Context, arg PurgeAdWatchesParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeAdWatches, arg.Now, arg.KeepBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startAdWatch = `-- name: StartAdWatch :one

INSERT INTO app.ad_watches (player_id, unit, created_at, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, player_id, unit, created_at, expires_at, transaction_id, paid_at, diamonds, key_id
`

type StartAdWatchParams struct {
	PlayerID  uuid.UUID
	Unit      string
	Now       time.Time
	ExpiresAt time.Time
}

// Herald's Tidings (migration 00049): the rewarded advert.
// A watch is started. The row IS the ticket the SDK carries.
func (q *Queries) StartAdWatch(ctx context.Context, arg StartAdWatchParams) (AppAdWatch, error) {
	row := q.db.QueryRow(ctx, startAdWatch,
		arg.PlayerID,
		arg.Unit,
		arg.Now,
		arg.ExpiresAt,
	)
	var i AppAdWatch
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Unit,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.TransactionID,
		&i.PaidAt,
		&i.Diamonds,
		&i.KeyID,
	)
	return i, err
}
