// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deletePlayerEvents = `-- name: DeletePlayerEvents :exec
DELETE FROM app.analytics_events WHERE player_id = $1
`

// A deleted account's events go with it. Its days stay: they happened, and a
// cohort that forgets the players who left reports its retention too high.
func (q *Queries) DeletePlayerEvents(ctx context.Context, playerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlayerEvents, playerID)
	return err
}

const eventCounts = `-- name: EventCounts :many
SELECT name, count(*)::bigint AS events, count(DISTINCT player_id)::bigint AS players
FROM app.analytics_events
WHERE created_at > $1::timestamptz
GROUP BY name
ORDER BY count(*) DESC
`

type EventCountsRow struct {
	Name    string
	Events  int64
	Players int64
}

// Each event name over a window: how often, and by how many players.
func (q *Queries) EventCounts(ctx context.Context, since time.Time) ([]EventCountsRow, error) {
	rows, err := q.db.Query(ctx, eventCounts, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventCountsRow{}
	for rows.Next() {
		var i EventCountsRow
		if err := rows.Scan(&i.Name, &i.Events, &i.Players); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeletedAccount = `-- name: GetDeletedAccount :one
SELECT player_id, joined_at, deleted_at, level, diamonds, diamond_debt FROM app.deleted_accounts WHERE player_id = $1
`

func (q *Queries) GetDeletedAccount(ctx context.Context, playerID uuid.UUID) (AppDeletedAccount, error) {
	row := q.db.QueryRow(ctx, getDeletedAccount, playerID)
	var i AppDeletedAccount
	err := row.Scan(
		&i.PlayerID,
		&i.JoinedAt,
		&i.DeletedAt,
		&i.Level,
		&i.Diamonds,
		&i.DiamondDebt,
	)
	return i, err
}

const purgeDeletedLedger = `-- name: PurgeDeletedLedger :execrows
DELETE FROM app.diamond_ledger l
USING app.deleted_accounts d
WHERE l.player_id = d.player_id AND d.deleted_at < $1::timestamptz
`

// The diamond history of accounts deleted before a cutoff. A refund that comes
// after this finds the deleted_accounts row and nothing to take back.
func (q *Queries) PurgeDeletedLedger(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeDeletedLedger, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeEvents = `-- name: PurgeEvents :execrows
DELETE FROM app.analytics_events WHERE created_at < $1::timestamptz
`

func (q *Queries) PurgeEvents(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeEvents, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgePlayerDays = `-- name: PurgePlayerDays :execrows
DELETE FROM app.player_days WHERE day < $1::date
`

func (q *Queries) PurgePlayerDays(ctx context.Context, before pgtype.Date) (int64, error) {
	result, err := q.db.Exec(ctx, purgePlayerDays, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordDeletedAccount = `-- name: RecordDeletedAccount :exec

INSERT INTO app.deleted_accounts (player_id, joined_at, deleted_at, level, diamonds, diamond_debt)
VALUES ($1, $2, $3, $4,
        $5, $6)
`

type RecordDeletedAccountParams struct {
	PlayerID    uuid.UUID
	JoinedAt    time.Time
	DeletedAt   time.Time
	Level       int32
	Diamonds    int64
	DiamondDebt int64
}

// Deleted accounts, player days and the client's events. See migration 00033.
// What outlives a deleted account: its id, when it came and went, and what it
// held. Written in the deletion's own transaction, before the player row goes.
func (q *Queries) RecordDeletedAccount(ctx context.Context, arg RecordDeletedAccountParams) error {
	_, err := q.db.Exec(ctx, recordDeletedAccount,
		arg.PlayerID,
		arg.JoinedAt,
		arg.DeletedAt,
		arg.Level,
		arg.Diamonds,
		arg.DiamondDebt,
	)
	return err
}

const recordEvents = `-- name: RecordEvents :execrows
INSERT INTO app.analytics_events (player_id, name, props, client_at)
SELECT $1::uuid, e.name, e.props::jsonb,
       CASE WHEN e.at > 0 THEN to_timestamp(e.at) END
FROM (SELECT unnest($2::text[])  AS name,
             unnest($3::text[])  AS props,
             unnest($4::bigint[])  AS at) e
WHERE (SELECT count(*) FROM app.analytics_events x
       WHERE x.player_id = $1::uuid
         AND x.created_at > $5::timestamptz - interval '1 hour') < $6::int
`

type RecordEventsParams struct {
	PlayerID  uuid.UUID
	Names     []string
	Props     []string
	Ats       []int64
	Now       time.Time
	HourlyCap int32
}

// One call's events, in one statement, unless the player has already sent their
// hour's allowance. The arrays are parallel; unnest in a select list walks them
// together. props arrive as JSON text; an at of 0 is "the phone's clock was not
// believable".
func (q *Queries) RecordEvents(ctx context.Context, arg RecordEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordEvents,
		arg.PlayerID,
		arg.Names,
		arg.Props,
		arg.Ats,
		arg.Now,
		arg.HourlyCap,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retentionCohorts = `-- name: RetentionCohorts :many
WITH joined AS (
    SELECT id AS player_id, (created_at AT TIME ZONE 'UTC')::date AS day
    FROM app.players WHERE NOT is_bot
    UNION ALL
    SELECT player_id, (joined_at AT TIME ZONE 'UTC')::date FROM app.deleted_accounts
)
SELECT j.day::date AS day,
       count(*)::bigint AS size,
       count(*) FILTER (WHERE EXISTS (SELECT 1 FROM app.player_days d
                                      WHERE d.player_id = j.player_id AND d.day = j.day + 1))::bigint AS d1,
       count(*) FILTER (WHERE EXISTS (SELECT 1 FROM app.player_days d
                                      WHERE d.player_id = j.player_id AND d.day = j.day + 7))::bigint AS d7,
       count(*) FILTER (WHERE EXISTS (SELECT 1 FROM app.player_days d
                                      WHERE d.player_id = j.player_id AND d.day = j.day + 30))::bigint AS d30
FROM joined j
WHERE j.day >= $1::date
GROUP BY j.day
ORDER BY j.day DESC
`

type RetentionCohortsRow struct {
	Day  pgtype.Date
	Size int64
	D1   int64
	D7   int64
	D30  int64
}

// Classic retention by the UTC day players joined: of those who joined on a day,
// how many were here exactly one, seven and thirty days later. Deleted accounts
// stay in the cohort they joined. Bots never send a request, so never join one.
func (q *Queries) RetentionCohorts(ctx context.Context, since pgtype.Date) ([]RetentionCohortsRow, error) {
	rows, err := q.db.Query(ctx, retentionCohorts, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RetentionCohortsRow{}
	for rows.Next() {
		var i RetentionCohortsRow
		if err := rows.Scan(
			&i.Day,
			&i.Size,
			&i.D1,
			&i.D7,
			&i.D30,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const screenCounts = `-- name: ScreenCounts :many
SELECT coalesce(props->>'name', '')::text AS screen, count(*)::bigint AS views,
       count(DISTINCT player_id)::bigint AS players
FROM app.analytics_events
WHERE name = 'screen' AND created_at > $1::timestamptz
GROUP BY props->>'name'
ORDER BY count(*) DESC
LIMIT 40
`

type ScreenCountsRow struct {
	Screen  string
	Views   int64
	Players int64
}

// The screens opened over a window, most visited first.
func (q *Queries) ScreenCounts(ctx context.Context, since time.Time) ([]ScreenCountsRow, error) {
	rows, err := q.db.Query(ctx, screenCounts, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScreenCountsRow{}
	for rows.Next() {
		var i ScreenCountsRow
		if err := rows.Scan(&i.Screen, &i.Views, &i.Players); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionLengths = `-- name: SessionLengths :many
SELECT CASE WHEN s < 60 THEN 0 WHEN s < 180 THEN 1 WHEN s < 600 THEN 2
            WHEN s < 1800 THEN 3 ELSE 4 END::int AS band,
       count(*)::bigint AS sessions
FROM (SELECT (props->>'seconds')::bigint AS s FROM app.analytics_events
      WHERE name = 'app_close' AND created_at > $1::timestamptz) x
GROUP BY 1
ORDER BY 1
`

type SessionLengthsRow struct {
	Band     int32
	Sessions int64
}

// How long sessions last, in bands, from the phone's own count of its time in
// the foreground. The bands are the panel's rows.
func (q *Queries) SessionLengths(ctx context.Context, since time.Time) ([]SessionLengthsRow, error) {
	rows, err := q.db.Query(ctx, sessionLengths, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionLengthsRow{}
	for rows.Next() {
		var i SessionLengthsRow
		if err := rows.Scan(&i.Band, &i.Sessions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
