// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balance.sql

package sqlcdb

import (
	"context"
	"time"
)

const activateBalanceVersion = `-- name: ActivateBalanceVersion :one
INSERT INTO admin.balance_activations (version_id, activated_by, reason)
VALUES ($1, $2, $3)
RETURNING id, version_id, activated_by, reason, activated_at
`

type ActivateBalanceVersionParams struct {
	VersionID   int64
	ActivatedBy string
	Reason      string
}

func (q *Queries) ActivateBalanceVersion(ctx context.Context, arg ActivateBalanceVersionParams) (AdminBalanceActivation, error) {
	row := q.db.QueryRow(ctx, activateBalanceVersion, arg.VersionID, arg.ActivatedBy, arg.Reason)
	var i AdminBalanceActivation
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.ActivatedBy,
		&i.Reason,
		&i.ActivatedAt,
	)
	return i, err
}

const activeBalance = `-- name: ActiveBalance :one
SELECT v.id, v.doc, v.sha256, v.note, v.created_at, a.activated_at, a.activated_by
FROM admin.balance_activations a
JOIN admin.balance_versions v ON v.id = a.version_id
ORDER BY a.activated_at DESC, a.id DESC
LIMIT 1
`

type ActiveBalanceRow struct {
	ID          int64
	Doc         string
	Sha256      []byte
	Note        string
	CreatedAt   time.Time
	ActivatedAt time.Time
	ActivatedBy string
}

// The newest activation is the live configuration. Joining rather than storing
// an "active" flag means a rollback is another append, and the history of what
// was live when survives — the only way to explain an old battle after a
// rebalance.
func (q *Queries) ActiveBalance(ctx context.Context) (ActiveBalanceRow, error) {
	row := q.db.QueryRow(ctx, activeBalance)
	var i ActiveBalanceRow
	err := row.Scan(
		&i.ID,
		&i.Doc,
		&i.Sha256,
		&i.Note,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.ActivatedBy,
	)
	return i, err
}

const countBalanceVersions = `-- name: CountBalanceVersions :one
SELECT count(*) FROM admin.balance_versions
`

func (q *Queries) CountBalanceVersions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBalanceVersions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBalanceVersion = `-- name: CreateBalanceVersion :one
INSERT INTO admin.balance_versions (doc, sha256, note, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, doc, doc_json, sha256, note, created_by, created_at
`

type CreateBalanceVersionParams struct {
	Doc       string
	Sha256    []byte
	Note      string
	CreatedBy string
}

func (q *Queries) CreateBalanceVersion(ctx context.Context, arg CreateBalanceVersionParams) (AdminBalanceVersion, error) {
	row := q.db.QueryRow(ctx, createBalanceVersion,
		arg.Doc,
		arg.Sha256,
		arg.Note,
		arg.CreatedBy,
	)
	var i AdminBalanceVersion
	err := row.Scan(
		&i.ID,
		&i.Doc,
		&i.DocJson,
		&i.Sha256,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getBalanceVersion = `-- name: GetBalanceVersion :one
SELECT id, doc, doc_json, sha256, note, created_by, created_at FROM admin.balance_versions WHERE id = $1
`

func (q *Queries) GetBalanceVersion(ctx context.Context, id int64) (AdminBalanceVersion, error) {
	row := q.db.QueryRow(ctx, getBalanceVersion, id)
	var i AdminBalanceVersion
	err := row.Scan(
		&i.ID,
		&i.Doc,
		&i.DocJson,
		&i.Sha256,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listBalanceVersions = `-- name: ListBalanceVersions :many
SELECT v.id, v.doc, v.doc_json, v.sha256, v.note, v.created_by, v.created_at,
       EXISTS (SELECT 1 FROM admin.balance_activations a WHERE a.version_id = v.id)::boolean
         AS ever_activated
FROM admin.balance_versions v
ORDER BY v.id DESC
LIMIT $1
`

type ListBalanceVersionsRow struct {
	ID            int64
	Doc           string
	DocJson       []byte
	Sha256        []byte
	Note          string
	CreatedBy     string
	CreatedAt     time.Time
	EverActivated bool
}

func (q *Queries) ListBalanceVersions(ctx context.Context, limit int32) ([]ListBalanceVersionsRow, error) {
	rows, err := q.db.Query(ctx, listBalanceVersions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBalanceVersionsRow{}
	for rows.Next() {
		var i ListBalanceVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Doc,
			&i.DocJson,
			&i.Sha256,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.EverActivated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
