// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: battles.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const applyBattleAttacker = `-- name: ApplyBattleAttacker :one
UPDATE app.players
SET gold = gold + $2, xp = $3, level = $4,
    stat_points_unspent = stat_points_unspent + $5,
    energy_milli = $6, energy_updated_at = $7,
    action_seq = $8
WHERE id = $1
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might
`

type ApplyBattleAttackerParams struct {
	ID                uuid.UUID
	Gold              int64
	Xp                int64
	Level             int32
	StatPointsUnspent int32
	EnergyMilli       int64
	EnergyUpdatedAt   time.Time
	ActionSeq         int64
}

func (q *Queries) ApplyBattleAttacker(ctx context.Context, arg ApplyBattleAttackerParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, applyBattleAttacker,
		arg.ID,
		arg.Gold,
		arg.Xp,
		arg.Level,
		arg.StatPointsUnspent,
		arg.EnergyMilli,
		arg.EnergyUpdatedAt,
		arg.ActionSeq,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
	)
	return i, err
}

const applyBattleDefender = `-- name: ApplyBattleDefender :one
UPDATE app.players
SET gold = gold + $2, shield_until = $3
WHERE id = $1
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might
`

type ApplyBattleDefenderParams struct {
	ID          uuid.UUID
	Gold        int64
	ShieldUntil *time.Time
}

func (q *Queries) ApplyBattleDefender(ctx context.Context, arg ApplyBattleDefenderParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, applyBattleDefender, arg.ID, arg.Gold, arg.ShieldUntil)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
	)
	return i, err
}

const countBots = `-- name: CountBots :one
SELECT count(*) FROM app.players WHERE is_bot
`

func (q *Queries) CountBots(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBots)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRaidsSince = `-- name: CountRaidsSince :one
SELECT count(*) AS raids,
       coalesce(sum(b.gold_stolen), 0)::bigint AS gold_lost,
       coalesce(sum(b.ransom_paid), 0)::bigint AS ransom_earned
FROM app.battles b
WHERE b.defender_id = $1
  AND b.created_at > $2::timestamptz
`

type CountRaidsSinceParams struct {
	PlayerID uuid.UUID
	Since    time.Time
}

type CountRaidsSinceRow struct {
	Raids        int64
	GoldLost     int64
	RansomEarned int64
}

// How many raids landed on this player since a given moment, for the
// "while you were away" summary. Counts only fights they did not start.
func (q *Queries) CountRaidsSince(ctx context.Context, arg CountRaidsSinceParams) (CountRaidsSinceRow, error) {
	row := q.db.QueryRow(ctx, countRaidsSince, arg.PlayerID, arg.Since)
	var i CountRaidsSinceRow
	err := row.Scan(&i.Raids, &i.GoldLost, &i.RansomEarned)
	return i, err
}

const createBot = `-- name: CreateBot :one
INSERT INTO app.players (username, display_name, level, gold, is_bot, soldier_slots,
                         stat_attack, stat_defense, energy_milli, avatar)
VALUES ($1,$2,$3,$4,true,$5,$6,$7,0,$8)
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might
`

type CreateBotParams struct {
	Username     string
	DisplayName  string
	Level        int32
	Gold         int64
	SoldierSlots int32
	StatAttack   int32
	StatDefense  int32
	Avatar       string
}

func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, createBot,
		arg.Username,
		arg.DisplayName,
		arg.Level,
		arg.Gold,
		arg.SoldierSlots,
		arg.StatAttack,
		arg.StatDefense,
		arg.Avatar,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
	)
	return i, err
}

const findTargets = `-- name: FindTargets :many
SELECT id, username, display_name, avatar, level, gold, is_bot, shield_until, kingdom_id
FROM app.players
WHERE state = 'active'
  AND id <> $1
  AND level BETWEEN $2 AND $3
  AND (shield_until IS NULL OR shield_until < now())
ORDER BY random()
LIMIT $4
`

type FindTargetsParams struct {
	ID      uuid.UUID
	Level   int32
	Level_2 int32
	Limit   int32
}

type FindTargetsRow struct {
	ID          uuid.UUID
	Username    string
	DisplayName string
	Avatar      string
	Level       int32
	Gold        int64
	IsBot       bool
	ShieldUntil *time.Time
	KingdomID   *uuid.UUID
}

// Candidate opponents inside a level band, excluding the player, bots-or-not by
// flag, the shielded, and anyone banned. Ordered by a stable pseudo-random key
// so the list changes between refreshes without a table scan.
func (q *Queries) FindTargets(ctx context.Context, arg FindTargetsParams) ([]FindTargetsRow, error) {
	rows, err := q.db.Query(ctx, findTargets,
		arg.ID,
		arg.Level,
		arg.Level_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindTargetsRow{}
	for rows.Next() {
		var i FindTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Avatar,
			&i.Level,
			&i.Gold,
			&i.IsBot,
			&i.ShieldUntil,
			&i.KingdomID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBattle = `-- name: GetBattle :one
SELECT id, attacker_id, defender_id, seed, config_version, attacker_won, rounds, attacker_might, defender_might, gold_stolen, ransom_paid, xp_awarded, energy_spent, replay, created_at FROM app.battles WHERE id = $1
`

func (q *Queries) GetBattle(ctx context.Context, id uuid.UUID) (AppBattle, error) {
	row := q.db.QueryRow(ctx, getBattle, id)
	var i AppBattle
	err := row.Scan(
		&i.ID,
		&i.AttackerID,
		&i.DefenderID,
		&i.Seed,
		&i.ConfigVersion,
		&i.AttackerWon,
		&i.Rounds,
		&i.AttackerMight,
		&i.DefenderMight,
		&i.GoldStolen,
		&i.RansomPaid,
		&i.XpAwarded,
		&i.EnergySpent,
		&i.Replay,
		&i.CreatedAt,
	)
	return i, err
}

const getCooldown = `-- name: GetCooldown :one
SELECT attacker_id, defender_id, last_at, count_24h FROM app.attack_cooldowns WHERE attacker_id = $1 AND defender_id = $2
`

type GetCooldownParams struct {
	AttackerID uuid.UUID
	DefenderID uuid.UUID
}

func (q *Queries) GetCooldown(ctx context.Context, arg GetCooldownParams) (AppAttackCooldown, error) {
	row := q.db.QueryRow(ctx, getCooldown, arg.AttackerID, arg.DefenderID)
	var i AppAttackCooldown
	err := row.Scan(
		&i.AttackerID,
		&i.DefenderID,
		&i.LastAt,
		&i.Count24h,
	)
	return i, err
}

const grantRevenge = `-- name: GrantRevenge :exec
INSERT INTO app.revenge_tokens (battle_id, player_id, target_id, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (battle_id) DO NOTHING
`

type GrantRevengeParams struct {
	BattleID  uuid.UUID
	PlayerID  uuid.UUID
	TargetID  uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) GrantRevenge(ctx context.Context, arg GrantRevengeParams) error {
	_, err := q.db.Exec(ctx, grantRevenge,
		arg.BattleID,
		arg.PlayerID,
		arg.TargetID,
		arg.ExpiresAt,
	)
	return err
}

const insertBattle = `-- name: InsertBattle :one
INSERT INTO app.battles (
    id, attacker_id, defender_id, seed, config_version, attacker_won, rounds,
    attacker_might, defender_might, gold_stolen, ransom_paid, xp_awarded,
    energy_spent, replay
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
RETURNING id, attacker_id, defender_id, seed, config_version, attacker_won, rounds, attacker_might, defender_might, gold_stolen, ransom_paid, xp_awarded, energy_spent, replay, created_at
`

type InsertBattleParams struct {
	ID            uuid.UUID
	AttackerID    uuid.UUID
	DefenderID    uuid.UUID
	Seed          int64
	ConfigVersion int32
	AttackerWon   bool
	Rounds        int32
	AttackerMight int64
	DefenderMight int64
	GoldStolen    int64
	RansomPaid    int64
	XpAwarded     int64
	EnergySpent   int64
	Replay        []byte
}

// The id is supplied, not defaulted.
//
// It is minted in Go before the fight because the combat seed is derived from
// it, and it is what the attack response hands the client. Letting the database
// default a different one meant the id the player was given did not name any
// stored row: every replay link was dead, and nothing could reference the battle
// afterwards.
func (q *Queries) InsertBattle(ctx context.Context, arg InsertBattleParams) (AppBattle, error) {
	row := q.db.QueryRow(ctx, insertBattle,
		arg.ID,
		arg.AttackerID,
		arg.DefenderID,
		arg.Seed,
		arg.ConfigVersion,
		arg.AttackerWon,
		arg.Rounds,
		arg.AttackerMight,
		arg.DefenderMight,
		arg.GoldStolen,
		arg.RansomPaid,
		arg.XpAwarded,
		arg.EnergySpent,
		arg.Replay,
	)
	var i AppBattle
	err := row.Scan(
		&i.ID,
		&i.AttackerID,
		&i.DefenderID,
		&i.Seed,
		&i.ConfigVersion,
		&i.AttackerWon,
		&i.Rounds,
		&i.AttackerMight,
		&i.DefenderMight,
		&i.GoldStolen,
		&i.RansomPaid,
		&i.XpAwarded,
		&i.EnergySpent,
		&i.Replay,
		&i.CreatedAt,
	)
	return i, err
}

const listBattleLog = `-- name: ListBattleLog :many
SELECT b.id, b.attacker_id, b.defender_id, b.attacker_won, b.rounds,
       b.attacker_might, b.defender_might, b.gold_stolen, b.ransom_paid,
       b.xp_awarded, b.created_at,
       o.display_name AS opponent_name,
       o.avatar       AS opponent_avatar,
       o.level        AS opponent_level,
       o.is_bot       AS opponent_is_bot
FROM app.battles b
JOIN app.players o
  ON o.id = CASE WHEN b.attacker_id = $1 THEN b.defender_id
                 ELSE b.attacker_id END
WHERE b.attacker_id = $1 OR b.defender_id = $1
ORDER BY b.created_at DESC
LIMIT $2
`

type ListBattleLogParams struct {
	PlayerID uuid.UUID
	Lim      int32
}

type ListBattleLogRow struct {
	ID             uuid.UUID
	AttackerID     uuid.UUID
	DefenderID     uuid.UUID
	AttackerWon    bool
	Rounds         int32
	AttackerMight  int64
	DefenderMight  int64
	GoldStolen     int64
	RansomPaid     int64
	XpAwarded      int64
	CreatedAt      time.Time
	OpponentName   string
	OpponentAvatar string
	OpponentLevel  int32
	OpponentIsBot  bool
}

// Battle history with the OTHER party's identity resolved in the same round
// trip. A log that says "you lost 4,120 gold" without saying to whom is not a
// log, and fetching the names separately would be one query per row.
//
// The join key flips on which side the player was: their opponent is the
// defender when they attacked, and the attacker when they were raided.
func (q *Queries) ListBattleLog(ctx context.Context, arg ListBattleLogParams) ([]ListBattleLogRow, error) {
	rows, err := q.db.Query(ctx, listBattleLog, arg.PlayerID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBattleLogRow{}
	for rows.Next() {
		var i ListBattleLogRow
		if err := rows.Scan(
			&i.ID,
			&i.AttackerID,
			&i.DefenderID,
			&i.AttackerWon,
			&i.Rounds,
			&i.AttackerMight,
			&i.DefenderMight,
			&i.GoldStolen,
			&i.RansomPaid,
			&i.XpAwarded,
			&i.CreatedAt,
			&i.OpponentName,
			&i.OpponentAvatar,
			&i.OpponentLevel,
			&i.OpponentIsBot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBattles = `-- name: ListBattles :many
SELECT id, attacker_id, defender_id, seed, config_version, attacker_won, rounds, attacker_might, defender_might, gold_stolen, ransom_paid, xp_awarded, energy_spent, replay, created_at FROM app.battles
WHERE attacker_id = $1 OR defender_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListBattlesParams struct {
	AttackerID uuid.UUID
	Limit      int32
}

func (q *Queries) ListBattles(ctx context.Context, arg ListBattlesParams) ([]AppBattle, error) {
	rows, err := q.db.Query(ctx, listBattles, arg.AttackerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppBattle{}
	for rows.Next() {
		var i AppBattle
		if err := rows.Scan(
			&i.ID,
			&i.AttackerID,
			&i.DefenderID,
			&i.Seed,
			&i.ConfigVersion,
			&i.AttackerWon,
			&i.Rounds,
			&i.AttackerMight,
			&i.DefenderMight,
			&i.GoldStolen,
			&i.RansomPaid,
			&i.XpAwarded,
			&i.EnergySpent,
			&i.Replay,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevenge = `-- name: ListRevenge :many
SELECT r.battle_id, r.target_id, r.expires_at,
       t.display_name AS target_name,
       t.avatar       AS target_avatar,
       t.level        AS target_level
FROM app.revenge_tokens r
JOIN app.players t ON t.id = r.target_id
WHERE r.player_id = $1
  AND r.used_at IS NULL
  AND r.expires_at > now()
ORDER BY r.expires_at ASC
`

type ListRevengeRow struct {
	BattleID     uuid.UUID
	TargetID     uuid.UUID
	ExpiresAt    time.Time
	TargetName   string
	TargetAvatar string
	TargetLevel  int32
}

// Live, unspent tokens with the person to be avenged upon resolved in the same
// round trip.
func (q *Queries) ListRevenge(ctx context.Context, playerID uuid.UUID) ([]ListRevengeRow, error) {
	rows, err := q.db.Query(ctx, listRevenge, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRevengeRow{}
	for rows.Next() {
		var i ListRevengeRow
		if err := rows.Scan(
			&i.BattleID,
			&i.TargetID,
			&i.ExpiresAt,
			&i.TargetName,
			&i.TargetAvatar,
			&i.TargetLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTwoPlayers = `-- name: LockTwoPlayers :many
SELECT id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might FROM app.players WHERE id = ANY($1::uuid[]) ORDER BY id FOR UPDATE
`

func (q *Queries) LockTwoPlayers(ctx context.Context, dollar_1 []uuid.UUID) ([]AppPlayer, error) {
	rows, err := q.db.Query(ctx, lockTwoPlayers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPlayer{}
	for rows.Next() {
		var i AppPlayer
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Level,
			&i.Xp,
			&i.Gold,
			&i.TreasuryGold,
			&i.Diamonds,
			&i.EnergyMilli,
			&i.EnergyUpdatedAt,
			&i.StatEnergy,
			&i.StatAttack,
			&i.StatDefense,
			&i.StatPointsUnspent,
			&i.ShieldUntil,
			&i.ActionSeq,
			&i.State,
			&i.ResetOffsetMinutes,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.SoldierSlots,
			&i.FreeSlotClaimed,
			&i.FreeRecruitClaimed,
			&i.IsBot,
			&i.TaxMilliAccrued,
			&i.TaxUpdatedAt,
			&i.KingdomID,
			&i.KingdomRole,
			&i.KingdomJoinedAt,
			&i.KingdomDonatedTotal,
			&i.KingdomFavour,
			&i.KingdomRepToday,
			&i.KingdomDonatedToday,
			&i.KingdomDay,
			&i.Avatar,
			&i.TaxMilliPerHour,
			&i.TaxUnlogged,
			&i.LuckBp,
			&i.LuckExpiresAt,
			&i.XpBoostBp,
			&i.XpBoostExpiresAt,
			&i.DailyStreak,
			&i.DailyClaimedOn,
			&i.Might,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchCooldown = `-- name: TouchCooldown :exec
INSERT INTO app.attack_cooldowns (attacker_id, defender_id, last_at, count_24h)
VALUES ($1, $2, now(), 1)
ON CONFLICT (attacker_id, defender_id) DO UPDATE
SET last_at = now(),
    count_24h = CASE WHEN app.attack_cooldowns.last_at > now() - interval '24 hours'
                     THEN app.attack_cooldowns.count_24h + 1 ELSE 1 END
`

type TouchCooldownParams struct {
	AttackerID uuid.UUID
	DefenderID uuid.UUID
}

func (q *Queries) TouchCooldown(ctx context.Context, arg TouchCooldownParams) error {
	_, err := q.db.Exec(ctx, touchCooldown, arg.AttackerID, arg.DefenderID)
	return err
}

const useRevenge = `-- name: UseRevenge :one
UPDATE app.revenge_tokens
SET used_at = now()
WHERE player_id = $1 AND target_id = $2
  AND used_at IS NULL AND expires_at > now()
RETURNING battle_id
`

type UseRevengeParams struct {
	PlayerID uuid.UUID
	TargetID uuid.UUID
}

// Spends a token, and only if it is still live and still theirs. Zero rows means
// it was already used or has expired, so the check and the spend cannot race.
func (q *Queries) UseRevenge(ctx context.Context, arg UseRevengeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, useRevenge, arg.PlayerID, arg.TargetID)
	var battle_id uuid.UUID
	err := row.Scan(&battle_id)
	return battle_id, err
}
