// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collect.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const applyCollect = `-- name: ApplyCollect :one
UPDATE app.players
SET energy_milli      = $2,
    energy_updated_at = $3,
    gold              = gold + $4,
    xp                = $5,
    level             = $6,
    stat_points_unspent = stat_points_unspent + $7,
    diamonds          = diamonds + $8,
    action_seq        = $9
WHERE id = $1
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at
`

type ApplyCollectParams struct {
	ID                uuid.UUID
	EnergyMilli       int64
	EnergyUpdatedAt   time.Time
	Gold              int64
	Xp                int64
	Level             int32
	StatPointsUnspent int32
	Diamonds          int64
	ActionSeq         int64
}

// Applies one collect: spends energy, credits gold and XP, and advances the
// action sequence. Energy is written back already settled by the caller.
func (q *Queries) ApplyCollect(ctx context.Context, arg ApplyCollectParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, applyCollect,
		arg.ID,
		arg.EnergyMilli,
		arg.EnergyUpdatedAt,
		arg.Gold,
		arg.Xp,
		arg.Level,
		arg.StatPointsUnspent,
		arg.Diamonds,
		arg.ActionSeq,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
	)
	return i, err
}

const bumpJobProgress = `-- name: BumpJobProgress :one
INSERT INTO app.player_job_progress (player_id, job_id, collects)
VALUES ($1, $2, 1)
ON CONFLICT (player_id, job_id)
DO UPDATE SET collects = app.player_job_progress.collects + 1
RETURNING player_id, job_id, collects
`

type BumpJobProgressParams struct {
	PlayerID uuid.UUID
	JobID    string
}

func (q *Queries) BumpJobProgress(ctx context.Context, arg BumpJobProgressParams) (AppPlayerJobProgress, error) {
	row := q.db.QueryRow(ctx, bumpJobProgress, arg.PlayerID, arg.JobID)
	var i AppPlayerJobProgress
	err := row.Scan(&i.PlayerID, &i.JobID, &i.Collects)
	return i, err
}

const bumpJobProgressBy = `-- name: BumpJobProgressBy :one
INSERT INTO app.player_job_progress (player_id, job_id, collects)
VALUES ($1, $2, $3::bigint)
ON CONFLICT (player_id, job_id)
DO UPDATE SET collects = app.player_job_progress.collects + $3::bigint
RETURNING player_id, job_id, collects
`

type BumpJobProgressByParams struct {
	PlayerID uuid.UUID
	JobID    string
	N        int64
}

// Advances a job's lifetime count by several collects at once.
//
// A burst of taps on one job is the single most common thing that happens in
// this game, and doing it a row at a time meant one database round trip per tap
// inside the transaction. The mastery bonus still has to be computed per collect
// -- it depends on the count BEFORE each one -- but that is arithmetic the
// caller can do in a loop from the returned total.
func (q *Queries) BumpJobProgressBy(ctx context.Context, arg BumpJobProgressByParams) (AppPlayerJobProgress, error) {
	row := q.db.QueryRow(ctx, bumpJobProgressBy, arg.PlayerID, arg.JobID, arg.N)
	var i AppPlayerJobProgress
	err := row.Scan(&i.PlayerID, &i.JobID, &i.Collects)
	return i, err
}

const getJobProgress = `-- name: GetJobProgress :one
SELECT player_id, job_id, collects FROM app.player_job_progress WHERE player_id = $1 AND job_id = $2
`

type GetJobProgressParams struct {
	PlayerID uuid.UUID
	JobID    string
}

func (q *Queries) GetJobProgress(ctx context.Context, arg GetJobProgressParams) (AppPlayerJobProgress, error) {
	row := q.db.QueryRow(ctx, getJobProgress, arg.PlayerID, arg.JobID)
	var i AppPlayerJobProgress
	err := row.Scan(&i.PlayerID, &i.JobID, &i.Collects)
	return i, err
}

const listJobProgress = `-- name: ListJobProgress :many
SELECT player_id, job_id, collects FROM app.player_job_progress WHERE player_id = $1
`

func (q *Queries) ListJobProgress(ctx context.Context, playerID uuid.UUID) ([]AppPlayerJobProgress, error) {
	rows, err := q.db.Query(ctx, listJobProgress, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPlayerJobProgress{}
	for rows.Next() {
		var i AppPlayerJobProgress
		if err := rows.Scan(&i.PlayerID, &i.JobID, &i.Collects); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settleEnergy = `-- name: SettleEnergy :exec
UPDATE app.players SET energy_milli = $2, energy_updated_at = $3 WHERE id = $1
`

type SettleEnergyParams struct {
	ID              uuid.UUID
	EnergyMilli     int64
	EnergyUpdatedAt time.Time
}

func (q *Queries) SettleEnergy(ctx context.Context, arg SettleEnergyParams) error {
	_, err := q.db.Exec(ctx, settleEnergy, arg.ID, arg.EnergyMilli, arg.EnergyUpdatedAt)
	return err
}
