// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collect.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const applyCollect = `-- name: ApplyCollect :one
UPDATE app.players
SET energy_milli      = $2,
    energy_updated_at = $3,
    gold              = gold + $4,
    xp                = $5,
    level             = $6,
    stat_points_unspent = stat_points_unspent + $7,
    action_seq        = $8,
    last_seen_at      = now()
WHERE id = $1
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at
`

type ApplyCollectParams struct {
	ID                uuid.UUID
	EnergyMilli       int64
	EnergyUpdatedAt   time.Time
	Gold              int64
	Xp                int64
	Level             int32
	StatPointsUnspent int32
	ActionSeq         int64
}

// Applies one collect: spends energy, credits gold and XP, and advances the
// action sequence. Energy is written back already settled by the caller.
func (q *Queries) ApplyCollect(ctx context.Context, arg ApplyCollectParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, applyCollect,
		arg.ID,
		arg.EnergyMilli,
		arg.EnergyUpdatedAt,
		arg.Gold,
		arg.Xp,
		arg.Level,
		arg.StatPointsUnspent,
		arg.ActionSeq,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const bumpJobProgress = `-- name: BumpJobProgress :one
INSERT INTO app.player_job_progress (player_id, job_id, collects)
VALUES ($1, $2, 1)
ON CONFLICT (player_id, job_id)
DO UPDATE SET collects = app.player_job_progress.collects + 1
RETURNING player_id, job_id, collects
`

type BumpJobProgressParams struct {
	PlayerID uuid.UUID
	JobID    string
}

func (q *Queries) BumpJobProgress(ctx context.Context, arg BumpJobProgressParams) (AppPlayerJobProgress, error) {
	row := q.db.QueryRow(ctx, bumpJobProgress, arg.PlayerID, arg.JobID)
	var i AppPlayerJobProgress
	err := row.Scan(&i.PlayerID, &i.JobID, &i.Collects)
	return i, err
}

const getJobProgress = `-- name: GetJobProgress :one
SELECT player_id, job_id, collects FROM app.player_job_progress WHERE player_id = $1 AND job_id = $2
`

type GetJobProgressParams struct {
	PlayerID uuid.UUID
	JobID    string
}

func (q *Queries) GetJobProgress(ctx context.Context, arg GetJobProgressParams) (AppPlayerJobProgress, error) {
	row := q.db.QueryRow(ctx, getJobProgress, arg.PlayerID, arg.JobID)
	var i AppPlayerJobProgress
	err := row.Scan(&i.PlayerID, &i.JobID, &i.Collects)
	return i, err
}

const listJobProgress = `-- name: ListJobProgress :many
SELECT player_id, job_id, collects FROM app.player_job_progress WHERE player_id = $1
`

func (q *Queries) ListJobProgress(ctx context.Context, playerID uuid.UUID) ([]AppPlayerJobProgress, error) {
	rows, err := q.db.Query(ctx, listJobProgress, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPlayerJobProgress{}
	for rows.Next() {
		var i AppPlayerJobProgress
		if err := rows.Scan(&i.PlayerID, &i.JobID, &i.Collects); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settleEnergy = `-- name: SettleEnergy :exec
UPDATE app.players SET energy_milli = $2, energy_updated_at = $3 WHERE id = $1
`

type SettleEnergyParams struct {
	ID              uuid.UUID
	EnergyMilli     int64
	EnergyUpdatedAt time.Time
}

func (q *Queries) SettleEnergy(ctx context.Context, arg SettleEnergyParams) error {
	_, err := q.db.Exec(ctx, settleEnergy, arg.ID, arg.EnergyMilli, arg.EnergyUpdatedAt)
	return err
}
