// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_loop.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimCalendarDay = `-- name: ClaimCalendarDay :one
UPDATE app.players
SET daily_streak     = $1,
    daily_claimed_on = $2,
    calendar_pos     = $3,
    calendar_cycle   = $4
WHERE id = $5
  AND (daily_claimed_on IS NULL OR daily_claimed_on < $2)
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs
`

type ClaimCalendarDayParams struct {
	Streak int32
	Today  pgtype.Date
	Pos    int16
	Cycle  int32
	ID     uuid.UUID
}

// Takes today's square. The rule lives in the WHERE: it lands only when the
// lord has not claimed on this local date, so two taps or two devices cannot
// both take it. The square's reward is paid by the caller through grantBundle.
func (q *Queries) ClaimCalendarDay(ctx context.Context, arg ClaimCalendarDayParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, claimCalendarDay,
		arg.Streak,
		arg.Today,
		arg.Pos,
		arg.Cycle,
		arg.ID,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const claimRoad = `-- name: ClaimRoad :one
UPDATE app.players
SET road_claimed = road_claimed | $1::int
WHERE id = $2 AND road_claimed & $1::int = 0
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs
`

type ClaimRoadParams struct {
	Mask int32
	ID   uuid.UUID
}

// Claims Victory Road milestones: every bit must still be clear, so a claim
// raced by another pays once.
func (q *Queries) ClaimRoad(ctx context.Context, arg ClaimRoadParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, claimRoad, arg.Mask, arg.ID)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const claimWeeklyChest = `-- name: ClaimWeeklyChest :one
UPDATE app.player_weekly
SET chests = chests | $1::int
WHERE player_id = $2 AND week = $3
  AND chests & $1::int = 0 AND points >= $4::int
RETURNING player_id, week, task_ids, claimed, chests, points
`

type ClaimWeeklyChestParams struct {
	Bit      int32
	PlayerID uuid.UUID
	Week     pgtype.Date
	At       int32
}

// A chest opens once, and only on points already earned.
func (q *Queries) ClaimWeeklyChest(ctx context.Context, arg ClaimWeeklyChestParams) (AppPlayerWeekly, error) {
	row := q.db.QueryRow(ctx, claimWeeklyChest,
		arg.Bit,
		arg.PlayerID,
		arg.Week,
		arg.At,
	)
	var i AppPlayerWeekly
	err := row.Scan(
		&i.PlayerID,
		&i.Week,
		&i.TaskIds,
		&i.Claimed,
		&i.Chests,
		&i.Points,
	)
	return i, err
}

const claimWeeklyTask = `-- name: ClaimWeeklyTask :one
UPDATE app.player_weekly
SET claimed = claimed | $1::int, points = points + $2::int
WHERE player_id = $3 AND week = $4 AND claimed & $1::int = 0
RETURNING player_id, week, task_ids, claimed, chests, points
`

type ClaimWeeklyTaskParams struct {
	Bit      int32
	Points   int32
	PlayerID uuid.UUID
	Week     pgtype.Date
}

// Setting the slot's bit is the claim; zero rows means it was already set.
func (q *Queries) ClaimWeeklyTask(ctx context.Context, arg ClaimWeeklyTaskParams) (AppPlayerWeekly, error) {
	row := q.db.QueryRow(ctx, claimWeeklyTask,
		arg.Bit,
		arg.Points,
		arg.PlayerID,
		arg.Week,
	)
	var i AppPlayerWeekly
	err := row.Scan(
		&i.PlayerID,
		&i.Week,
		&i.TaskIds,
		&i.Claimed,
		&i.Chests,
		&i.Points,
	)
	return i, err
}

const countHeroEquipped = `-- name: CountHeroEquipped :one
SELECT count(*)::bigint FROM app.player_items WHERE player_id = $1 AND equipped_on_hero
`

func (q *Queries) CountHeroEquipped(ctx context.Context, playerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countHeroEquipped, playerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const drinkFlask = `-- name: DrinkFlask :one
UPDATE app.players
SET energy_milli = $1, energy_updated_at = $2,
    action_seq = $3
WHERE id = $4
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs
`

type DrinkFlaskParams struct {
	EnergyMilli     int64
	EnergyUpdatedAt time.Time
	ActionSeq       int64
	ID              uuid.UUID
}

// A flask drunk: the lord's own sequenced action, so it moves action_seq like
// any other the client predicts.
func (q *Queries) DrinkFlask(ctx context.Context, arg DrinkFlaskParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, drinkFlask,
		arg.EnergyMilli,
		arg.EnergyUpdatedAt,
		arg.ActionSeq,
		arg.ID,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const ensureWeekly = `-- name: EnsureWeekly :one
INSERT INTO app.player_weekly (player_id, week, task_ids)
VALUES ($1, $2, $3::text[])
ON CONFLICT (player_id, week) DO UPDATE SET task_ids = app.player_weekly.task_ids
RETURNING player_id, week, task_ids, claimed, chests, points
`

type EnsureWeeklyParams struct {
	PlayerID uuid.UUID
	Week     pgtype.Date
	TaskIds  []string
}

// The week's board, drawn on its first look and frozen for the week.
func (q *Queries) EnsureWeekly(ctx context.Context, arg EnsureWeeklyParams) (AppPlayerWeekly, error) {
	row := q.db.QueryRow(ctx, ensureWeekly, arg.PlayerID, arg.Week, arg.TaskIds)
	var i AppPlayerWeekly
	err := row.Scan(
		&i.PlayerID,
		&i.Week,
		&i.TaskIds,
		&i.Claimed,
		&i.Chests,
		&i.Points,
	)
	return i, err
}

const getWeekly = `-- name: GetWeekly :one
SELECT player_id, week, task_ids, claimed, chests, points FROM app.player_weekly WHERE player_id = $1 AND week = $2
`

type GetWeeklyParams struct {
	PlayerID uuid.UUID
	Week     pgtype.Date
}

// The week's board as it stands, if it has been drawn: read first, so the
// heartbeat's badge stays a read.
func (q *Queries) GetWeekly(ctx context.Context, arg GetWeeklyParams) (AppPlayerWeekly, error) {
	row := q.db.QueryRow(ctx, getWeekly, arg.PlayerID, arg.Week)
	var i AppPlayerWeekly
	err := row.Scan(
		&i.PlayerID,
		&i.Week,
		&i.TaskIds,
		&i.Claimed,
		&i.Chests,
		&i.Points,
	)
	return i, err
}

const lifeDeed = `-- name: LifeDeed :one
SELECT coalesce(sum(value), 0)::bigint FROM app.player_deeds
WHERE player_id = $1 AND scope = 'life' AND deed = $2
`

type LifeDeedParams struct {
	PlayerID uuid.UUID
	Deed     string
}

// A lord's lifetime count of one deed, for the guide's steps.
func (q *Queries) LifeDeed(ctx context.Context, arg LifeDeedParams) (int64, error) {
	row := q.db.QueryRow(ctx, lifeDeed, arg.PlayerID, arg.Deed)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listWinbackDue = `-- name: ListWinbackDue :many
SELECT id, last_seen_at, winback_at, winback_tier FROM app.players
WHERE NOT is_bot AND state = 'active'
  AND last_seen_at < $1::timestamptz
  AND (
        (winback_at IS NULL OR (winback_at < last_seen_at AND winback_at < $2::timestamptz))
     OR (winback_tier = 1 AND winback_at >= last_seen_at AND last_seen_at < $3::timestamptz)
  )
ORDER BY last_seen_at
LIMIT $4
`

type ListWinbackDueParams struct {
	AwayBefore     time.Time
	CooldownBefore time.Time
	LongBefore     time.Time
	MaxRows        int32
}

type ListWinbackDueRow struct {
	ID          uuid.UUID
	LastSeenAt  time.Time
	WinbackAt   *time.Time
	WinbackTier int16
}

// Lords away long enough for a welcome back, whose last one did not answer
// this absence (sent before they were last seen) and is past its cooldown --
// or who were welcomed for this absence and have now been away long enough
// for the second letter.
func (q *Queries) ListWinbackDue(ctx context.Context, arg ListWinbackDueParams) ([]ListWinbackDueRow, error) {
	rows, err := q.db.Query(ctx, listWinbackDue,
		arg.AwayBefore,
		arg.CooldownBefore,
		arg.LongBefore,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWinbackDueRow{}
	for rows.Next() {
		var i ListWinbackDueRow
		if err := rows.Scan(
			&i.ID,
			&i.LastSeenAt,
			&i.WinbackAt,
			&i.WinbackTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWinback = `-- name: MarkWinback :one
UPDATE app.players
SET winback_at = $1, winback_tier = $2
WHERE id = $3 AND winback_tier = $4
  AND winback_at IS NOT DISTINCT FROM $5::timestamptz
RETURNING id
`

type MarkWinbackParams struct {
	At       *time.Time
	Tier     int16
	ID       uuid.UUID
	FromTier int16
	FromAt   *time.Time
}

// Records the letter sent, pinned to what the job read, so two runs send one.
func (q *Queries) MarkWinback(ctx context.Context, arg MarkWinbackParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, markWinback,
		arg.At,
		arg.Tier,
		arg.ID,
		arg.FromTier,
		arg.FromAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const moveGuide = `-- name: MoveGuide :one
UPDATE app.players
SET guide_step = $1, guide_done_at = $2, guide_skipped = $3
WHERE id = $4 AND guide_step = $5 AND guide_done_at IS NULL
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs
`

type MoveGuideParams struct {
	Step     int16
	DoneAt   *time.Time
	Skipped  bool
	ID       uuid.UUID
	FromStep int16
}

// Moves the guide from one step to the next, or ends it. The WHERE pins the
// step it moves from, so a double tap moves it once.
func (q *Queries) MoveGuide(ctx context.Context, arg MoveGuideParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, moveGuide,
		arg.Step,
		arg.DoneAt,
		arg.Skipped,
		arg.ID,
		arg.FromStep,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const setCartYard = `-- name: SetCartYard :one

UPDATE app.players
SET cart_stock = $1, cart_at = $2,
    carts_opened = carts_opened + $3::int
WHERE id = $4
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs
`

type SetCartYardParams struct {
	Stock  int16
	At     time.Time
	Opened int32
	ID     uuid.UUID
}

// The daily loop (migration 00041): the Tax Cart, the 28-day calendar, the
// week's quests, the Golden Hour, the Victory Road, the guide, welcome back.
// The Tax Cart's yard after a settle or an opening. opened is how many carts
// this statement opened (0 for a settle alone).
func (q *Queries) SetCartYard(ctx context.Context, arg SetCartYardParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, setCartYard,
		arg.Stock,
		arg.At,
		arg.Opened,
		arg.ID,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const setFrenzy = `-- name: SetFrenzy :exec
UPDATE app.players
SET frenzy_meter_milli = $1,
    frenzy_last_at     = $2,
    frenzy_until       = $3,
    frenzy_energy_left = $4,
    frenzy_day         = $5,
    frenzy_used        = $6,
    frenzy_ready_at    = $7
WHERE id = $8
`

type SetFrenzyParams struct {
	MeterMilli int64
	LastAt     *time.Time
	Until      *time.Time
	EnergyLeft int64
	Day        pgtype.Date
	Used       int16
	ReadyAt    *time.Time
	ID         uuid.UUID
}

// The Golden Hour's state after a collect (game/frenzy.Step).
func (q *Queries) SetFrenzy(ctx context.Context, arg SetFrenzyParams) error {
	_, err := q.db.Exec(ctx, setFrenzy,
		arg.MeterMilli,
		arg.LastAt,
		arg.Until,
		arg.EnergyLeft,
		arg.Day,
		arg.Used,
		arg.ReadyAt,
		arg.ID,
	)
	return err
}
