// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deals.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDealSlot = `-- name: ClaimDealSlot :one
UPDATE app.player_deals SET claimed = claimed | $1::int
WHERE player_id = $2 AND day = $3
  AND claimed & $1::int = 0
RETURNING player_id, day, slots, claimed
`

type ClaimDealSlotParams struct {
	Bit      int32
	PlayerID uuid.UUID
	Day      pgtype.Date
}

// Marks one slot claimed, once, on its own day. No row: stale or already taken.
func (q *Queries) ClaimDealSlot(ctx context.Context, arg ClaimDealSlotParams) (AppPlayerDeal, error) {
	row := q.db.QueryRow(ctx, claimDealSlot, arg.Bit, arg.PlayerID, arg.Day)
	var i AppPlayerDeal
	err := row.Scan(
		&i.PlayerID,
		&i.Day,
		&i.Slots,
		&i.Claimed,
	)
	return i, err
}

const getDeals = `-- name: GetDeals :one

SELECT player_id, day, slots, claimed FROM app.player_deals WHERE player_id = $1
`

// The Royal Store's daily deals. See migration 00035 and service/deals.go.
func (q *Queries) GetDeals(ctx context.Context, playerID uuid.UUID) (AppPlayerDeal, error) {
	row := q.db.QueryRow(ctx, getDeals, playerID)
	var i AppPlayerDeal
	err := row.Scan(
		&i.PlayerID,
		&i.Day,
		&i.Slots,
		&i.Claimed,
	)
	return i, err
}

const putDeals = `-- name: PutDeals :one
INSERT INTO app.player_deals (player_id, day, slots, claimed)
VALUES ($1, $2, $3, 0)
ON CONFLICT (player_id) DO UPDATE
SET day = EXCLUDED.day, slots = EXCLUDED.slots, claimed = 0
WHERE app.player_deals.day <> EXCLUDED.day
RETURNING player_id, day, slots, claimed
`

type PutDealsParams struct {
	PlayerID uuid.UUID
	Day      pgtype.Date
	Slots    []byte
}

// Writes a day's deals. A row for the same day is left as it is -- whoever
// looked first fixed it -- and the row as it now stands comes back.
func (q *Queries) PutDeals(ctx context.Context, arg PutDealsParams) (AppPlayerDeal, error) {
	row := q.db.QueryRow(ctx, putDeals, arg.PlayerID, arg.Day, arg.Slots)
	var i AppPlayerDeal
	err := row.Scan(
		&i.PlayerID,
		&i.Day,
		&i.Slots,
		&i.Claimed,
	)
	return i, err
}
