// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diamonds.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const creditDiamonds = `-- name: CreditDiamonds :one
UPDATE app.players
SET diamonds     = diamonds + GREATEST(0, $1::bigint - diamond_debt),
    diamond_debt = GREATEST(0, diamond_debt - $1::bigint)
WHERE id = $2
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs
`

type CreditDiamondsParams struct {
	Amount int64
	ID     uuid.UUID
}

// Credits diamonds, repaying any refund debt first.
//
// Both right-hand sides read the row as it was, so the pair is exact in one
// statement: a player owing 50 who is granted 30 keeps 0 and owes 20; granted
// 80, they keep 30 and owe nothing. players_debt_means_empty holds either way.
func (q *Queries) CreditDiamonds(ctx context.Context, arg CreditDiamondsParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, creditDiamonds, arg.Amount, arg.ID)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const diamondFlows = `-- name: DiamondFlows :many
SELECT reason, class,
       sum(CASE WHEN gross > 0 THEN gross ELSE 0 END)::bigint AS created,
       sum(CASE WHEN gross < 0 THEN -gross ELSE 0 END)::bigint AS destroyed,
       count(*)::bigint AS entries
FROM app.diamond_ledger
WHERE created_at > now() - ($1::int * interval '1 day')
  AND class <> 'opening'
GROUP BY reason, class
ORDER BY greatest(sum(CASE WHEN gross > 0 THEN gross ELSE 0 END),
                  sum(CASE WHEN gross < 0 THEN -gross ELSE 0 END)) DESC
`

type DiamondFlowsRow struct {
	Reason    string
	Class     string
	Created   int64
	Destroyed int64
	Entries   int64
}

// Diamonds created and destroyed by reason over a window: the premium half of
// the economy dashboard. Opening balances are left out -- they are not a flow.
func (q *Queries) DiamondFlows(ctx context.Context, days int32) ([]DiamondFlowsRow, error) {
	rows, err := q.db.Query(ctx, diamondFlows, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiamondFlowsRow{}
	for rows.Next() {
		var i DiamondFlowsRow
		if err := rows.Scan(
			&i.Reason,
			&i.Class,
			&i.Created,
			&i.Destroyed,
			&i.Entries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiamondLedger = `-- name: ListDiamondLedger :many
SELECT id, delta, gross, balance_after, debt_after, reason, class, ref_id, created_at
FROM app.diamond_ledger
WHERE player_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListDiamondLedgerParams struct {
	PlayerID uuid.UUID
	Off      int32
	Lim      int32
}

type ListDiamondLedgerRow struct {
	ID           int64
	Delta        int64
	Gross        int64
	BalanceAfter int64
	DebtAfter    int64
	Reason       string
	Class        string
	RefID        *string
	CreatedAt    time.Time
}

// A player's diamond history, newest first, for the admin panel.
func (q *Queries) ListDiamondLedger(ctx context.Context, arg ListDiamondLedgerParams) ([]ListDiamondLedgerRow, error) {
	rows, err := q.db.Query(ctx, listDiamondLedger, arg.PlayerID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDiamondLedgerRow{}
	for rows.Next() {
		var i ListDiamondLedgerRow
		if err := rows.Scan(
			&i.ID,
			&i.Delta,
			&i.Gross,
			&i.BalanceAfter,
			&i.DebtAfter,
			&i.Reason,
			&i.Class,
			&i.RefID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDiamonds = `-- name: RecordDiamonds :exec

INSERT INTO app.diamond_ledger (player_id, delta, gross, balance_after, debt_after, reason, class, ref_id)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8)
`

type RecordDiamondsParams struct {
	PlayerID     uuid.UUID
	Delta        int64
	Gross        int64
	BalanceAfter int64
	DebtAfter    int64
	Reason       string
	Class        string
	RefID        *string
}

// The diamond ledger. See migration 00027 for why it has no foreign key.
func (q *Queries) RecordDiamonds(ctx context.Context, arg RecordDiamondsParams) error {
	_, err := q.db.Exec(ctx, recordDiamonds,
		arg.PlayerID,
		arg.Delta,
		arg.Gross,
		arg.BalanceAfter,
		arg.DebtAfter,
		arg.Reason,
		arg.Class,
		arg.RefID,
	)
	return err
}
