// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: estates.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const buyHoldingLevel = `-- name: BuyHoldingLevel :one
INSERT INTO app.player_holdings (player_id, holding_id, level)
VALUES ($1, $2, 1)
ON CONFLICT (player_id, holding_id) DO UPDATE
SET level = app.player_holdings.level + 1
WHERE app.player_holdings.level = $3
RETURNING player_id, holding_id, level
`

type BuyHoldingLevelParams struct {
	PlayerID  uuid.UUID
	HoldingID string
	Level     int32
}

func (q *Queries) BuyHoldingLevel(ctx context.Context, arg BuyHoldingLevelParams) (AppPlayerHolding, error) {
	row := q.db.QueryRow(ctx, buyHoldingLevel, arg.PlayerID, arg.HoldingID, arg.Level)
	var i AppPlayerHolding
	err := row.Scan(&i.PlayerID, &i.HoldingID, &i.Level)
	return i, err
}

const buyUpgradeLevel = `-- name: BuyUpgradeLevel :one
INSERT INTO app.player_upgrades (player_id, upgrade_id, level)
VALUES ($1, $2, 1)
ON CONFLICT (player_id, upgrade_id) DO UPDATE
SET level = app.player_upgrades.level + 1
WHERE app.player_upgrades.level = $3
RETURNING player_id, upgrade_id, level
`

type BuyUpgradeLevelParams struct {
	PlayerID  uuid.UUID
	UpgradeID string
	Level     int32
}

// Buys one level. The current level is in the WHERE clause, so two concurrent
// taps cannot both see the same level and both succeed.
func (q *Queries) BuyUpgradeLevel(ctx context.Context, arg BuyUpgradeLevelParams) (AppPlayerUpgrade, error) {
	row := q.db.QueryRow(ctx, buyUpgradeLevel, arg.PlayerID, arg.UpgradeID, arg.Level)
	var i AppPlayerUpgrade
	err := row.Scan(&i.PlayerID, &i.UpgradeID, &i.Level)
	return i, err
}

const claimTax = `-- name: ClaimTax :one
UPDATE app.players
SET gold = gold + $2,
    tax_milli_accrued = 0,
    tax_updated_at = $3,
    action_seq = $4
WHERE id = $1
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might
`

type ClaimTaxParams struct {
	ID           uuid.UUID
	Gold         int64
	TaxUpdatedAt time.Time
	ActionSeq    int64
}

func (q *Queries) ClaimTax(ctx context.Context, arg ClaimTaxParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, claimTax,
		arg.ID,
		arg.Gold,
		arg.TaxUpdatedAt,
		arg.ActionSeq,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
	)
	return i, err
}

const clearTaxUnlogged = `-- name: ClearTaxUnlogged :exec
UPDATE app.players SET tax_unlogged = 0 WHERE id = $1
`

// Clears the unlogged counter once its total has been written to the ledger.
func (q *Queries) ClearTaxUnlogged(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearTaxUnlogged, id)
	return err
}

const creditTax = `-- name: CreditTax :one
WITH calc AS (
    SELECT app.players.id AS pid,
           tax_milli_accrued + tax_milli_per_hour
               * GREATEST(0, (EXTRACT(EPOCH FROM ($1::timestamptz - tax_updated_at)) * 1000)::bigint)
               / 3600000 AS total
    FROM app.players
    WHERE app.players.id = $2
)
UPDATE app.players p
SET gold              = p.gold + calc.total / 1000,
    tax_milli_accrued = calc.total % 1000,
    -- Banked for the ledger. Flushed as one row when it is worth a row, rather
    -- than a row per request for a few milli each.
    tax_unlogged      = p.tax_unlogged + calc.total / 1000,
    tax_updated_at    = $1::timestamptz
FROM calc
WHERE p.id = calc.pid
  AND calc.total > p.tax_milli_accrued
RETURNING p.id, p.username, p.display_name, p.level, p.xp, p.gold, p.treasury_gold, p.diamonds, p.energy_milli, p.energy_updated_at, p.stat_energy, p.stat_attack, p.stat_defense, p.stat_points_unspent, p.shield_until, p.action_seq, p.state, p.reset_offset_minutes, p.created_at, p.last_seen_at, p.soldier_slots, p.free_slot_claimed, p.free_recruit_claimed, p.is_bot, p.tax_milli_accrued, p.tax_updated_at, p.kingdom_id, p.kingdom_role, p.kingdom_joined_at, p.kingdom_donated_total, p.kingdom_favour, p.kingdom_rep_today, p.kingdom_donated_today, p.kingdom_day, p.avatar, p.tax_milli_per_hour, p.tax_unlogged, p.luck_bp, p.luck_expires_at, p.xp_boost_bp, p.xp_boost_expires_at, p.daily_streak, p.daily_claimed_on, p.might
`

type CreditTaxParams struct {
	Now      time.Time
	PlayerID uuid.UUID
}

// Credits whatever the estates have earned since the last settle.
//
// Whole gold moves into the purse; the sub-gold remainder stays in the
// accumulator so nothing is lost to rounding on a fast poll.
//
// Two details that decide whether this is correct:
//
//   - elapsed is measured in MILLISECONDS. Truncating it to whole seconds meant
//     that a client polling four times a second earned exactly nothing, because
//     every individual call saw zero seconds elapsed and moved the anchor
//     anyway. Polling faster must never earn less.
//   - the anchor only moves when something was actually earned. Integer division
//     always rounds down, so a call that earns nothing must leave the clock
//     alone or the remainder is thrown away on every single request.
func (q *Queries) CreditTax(ctx context.Context, arg CreditTaxParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, creditTax, arg.Now, arg.PlayerID)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
	)
	return i, err
}

const listHoldings = `-- name: ListHoldings :many
SELECT player_id, holding_id, level FROM app.player_holdings WHERE player_id = $1
`

func (q *Queries) ListHoldings(ctx context.Context, playerID uuid.UUID) ([]AppPlayerHolding, error) {
	rows, err := q.db.Query(ctx, listHoldings, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPlayerHolding{}
	for rows.Next() {
		var i AppPlayerHolding
		if err := rows.Scan(&i.PlayerID, &i.HoldingID, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpgrades = `-- name: ListUpgrades :many
SELECT player_id, upgrade_id, level FROM app.player_upgrades WHERE player_id = $1
`

func (q *Queries) ListUpgrades(ctx context.Context, playerID uuid.UUID) ([]AppPlayerUpgrade, error) {
	rows, err := q.db.Query(ctx, listUpgrades, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPlayerUpgrade{}
	for rows.Next() {
		var i AppPlayerUpgrade
		if err := rows.Scan(&i.PlayerID, &i.UpgradeID, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaxRate = `-- name: SetTaxRate :exec
UPDATE app.players SET tax_milli_per_hour = $2 WHERE id = $1
`

type SetTaxRateParams struct {
	ID              uuid.UUID
	TaxMilliPerHour int64
}

// Rewrites the cached hourly rate. Must be called only after CreditTax, so the
// time already earned is paid at the OLD rate.
func (q *Queries) SetTaxRate(ctx context.Context, arg SetTaxRateParams) error {
	_, err := q.db.Exec(ctx, setTaxRate, arg.ID, arg.TaxMilliPerHour)
	return err
}

const settleTax = `-- name: SettleTax :exec
UPDATE app.players
SET tax_milli_accrued = $2, tax_updated_at = $3
WHERE id = $1
`

type SettleTaxParams struct {
	ID              uuid.UUID
	TaxMilliAccrued int64
	TaxUpdatedAt    time.Time
}

func (q *Queries) SettleTax(ctx context.Context, arg SettleTaxParams) error {
	_, err := q.db.Exec(ctx, settleTax, arg.ID, arg.TaxMilliAccrued, arg.TaxUpdatedAt)
	return err
}
