// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO app.identities (player_id, kind, subject, secret_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, player_id, kind, subject, secret_hash, created_at, last_used_at
`

type CreateIdentityParams struct {
	PlayerID   uuid.UUID
	Kind       string
	Subject    string
	SecretHash *string
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (AppIdentity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.PlayerID,
		arg.Kind,
		arg.Subject,
		arg.SecretHash,
	)
	var i AppIdentity
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Kind,
		&i.Subject,
		&i.SecretHash,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getIdentityBySubject = `-- name: GetIdentityBySubject :one
SELECT id, player_id, kind, subject, secret_hash, created_at, last_used_at FROM app.identities WHERE kind = $1 AND subject = $2
`

type GetIdentityBySubjectParams struct {
	Kind    string
	Subject string
}

func (q *Queries) GetIdentityBySubject(ctx context.Context, arg GetIdentityBySubjectParams) (AppIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentityBySubject, arg.Kind, arg.Subject)
	var i AppIdentity
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Kind,
		&i.Subject,
		&i.SecretHash,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const markIdentityUsed = `-- name: MarkIdentityUsed :exec
UPDATE app.identities SET last_used_at = now() WHERE id = $1
`

func (q *Queries) MarkIdentityUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markIdentityUsed, id)
	return err
}

const renameIdentitySubject = `-- name: RenameIdentitySubject :exec
UPDATE app.identities SET subject = $3 WHERE player_id = $1 AND kind = $2
`

type RenameIdentitySubjectParams struct {
	PlayerID uuid.UUID
	Kind     string
	Subject  string
}

// Moves the password login onto a renamed player's new name, so the name they
// see is the name they sign in with.
func (q *Queries) RenameIdentitySubject(ctx context.Context, arg RenameIdentitySubjectParams) error {
	_, err := q.db.Exec(ctx, renameIdentitySubject, arg.PlayerID, arg.Kind, arg.Subject)
	return err
}
