// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const countPlayerItems = `-- name: CountPlayerItems :one
SELECT count(*) FROM app.player_items WHERE player_id = $1
`

func (q *Queries) CountPlayerItems(ctx context.Context, playerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayerItems, playerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePlayerItem = `-- name: DeletePlayerItem :exec
DELETE FROM app.player_items WHERE id = $1 AND player_id = $2
`

type DeletePlayerItemParams struct {
	ID       uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) DeletePlayerItem(ctx context.Context, arg DeletePlayerItemParams) error {
	_, err := q.db.Exec(ctx, deletePlayerItem, arg.ID, arg.PlayerID)
	return err
}

const donateToCollection = `-- name: DonateToCollection :one
INSERT INTO app.player_collection (player_id, def_id)
VALUES ($1, $2)
ON CONFLICT (player_id, def_id) DO NOTHING
RETURNING def_id
`

type DonateToCollectionParams struct {
	PlayerID uuid.UUID
	DefID    string
}

// Records a donation. Zero rows means they already had that one, which the
// caller turns into a refusal BEFORE the item is destroyed.
func (q *Queries) DonateToCollection(ctx context.Context, arg DonateToCollectionParams) (string, error) {
	row := q.db.QueryRow(ctx, donateToCollection, arg.PlayerID, arg.DefID)
	var def_id string
	err := row.Scan(&def_id)
	return def_id, err
}

const getPlayerItem = `-- name: GetPlayerItem :one
SELECT id, player_id, def_id, slot, tier, ilvl, quality_pct, masterwork, attack, defense, speed, equipped_on_hero, equipped_soldier_id, acquired_at, acquired_from, rolled_config_version FROM app.player_items WHERE id = $1 AND player_id = $2
`

type GetPlayerItemParams struct {
	ID       uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) GetPlayerItem(ctx context.Context, arg GetPlayerItemParams) (AppPlayerItem, error) {
	row := q.db.QueryRow(ctx, getPlayerItem, arg.ID, arg.PlayerID)
	var i AppPlayerItem
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.DefID,
		&i.Slot,
		&i.Tier,
		&i.Ilvl,
		&i.QualityPct,
		&i.Masterwork,
		&i.Attack,
		&i.Defense,
		&i.Speed,
		&i.EquippedOnHero,
		&i.EquippedSoldierID,
		&i.AcquiredAt,
		&i.AcquiredFrom,
		&i.RolledConfigVersion,
	)
	return i, err
}

const insertPlayerItem = `-- name: InsertPlayerItem :one
INSERT INTO app.player_items (
    player_id, def_id, slot, tier, ilvl, quality_pct, masterwork,
    attack, defense, speed, acquired_from, rolled_config_version
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
RETURNING id, player_id, def_id, slot, tier, ilvl, quality_pct, masterwork, attack, defense, speed, equipped_on_hero, equipped_soldier_id, acquired_at, acquired_from, rolled_config_version
`

type InsertPlayerItemParams struct {
	PlayerID            uuid.UUID
	DefID               string
	Slot                string
	Tier                string
	Ilvl                int32
	QualityPct          int32
	Masterwork          bool
	Attack              int64
	Defense             int64
	Speed               int64
	AcquiredFrom        string
	RolledConfigVersion int32
}

func (q *Queries) InsertPlayerItem(ctx context.Context, arg InsertPlayerItemParams) (AppPlayerItem, error) {
	row := q.db.QueryRow(ctx, insertPlayerItem,
		arg.PlayerID,
		arg.DefID,
		arg.Slot,
		arg.Tier,
		arg.Ilvl,
		arg.QualityPct,
		arg.Masterwork,
		arg.Attack,
		arg.Defense,
		arg.Speed,
		arg.AcquiredFrom,
		arg.RolledConfigVersion,
	)
	var i AppPlayerItem
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.DefID,
		&i.Slot,
		&i.Tier,
		&i.Ilvl,
		&i.QualityPct,
		&i.Masterwork,
		&i.Attack,
		&i.Defense,
		&i.Speed,
		&i.EquippedOnHero,
		&i.EquippedSoldierID,
		&i.AcquiredAt,
		&i.AcquiredFrom,
		&i.RolledConfigVersion,
	)
	return i, err
}

const listCollection = `-- name: ListCollection :many
SELECT def_id FROM app.player_collection WHERE player_id = $1
`

func (q *Queries) ListCollection(ctx context.Context, playerID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listCollection, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var def_id string
		if err := rows.Scan(&def_id); err != nil {
			return nil, err
		}
		items = append(items, def_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeroEquipped = `-- name: ListHeroEquipped :many
SELECT id, player_id, def_id, slot, tier, ilvl, quality_pct, masterwork, attack, defense, speed, equipped_on_hero, equipped_soldier_id, acquired_at, acquired_from, rolled_config_version FROM app.player_items WHERE player_id = $1 AND equipped_on_hero
`

func (q *Queries) ListHeroEquipped(ctx context.Context, playerID uuid.UUID) ([]AppPlayerItem, error) {
	rows, err := q.db.Query(ctx, listHeroEquipped, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPlayerItem{}
	for rows.Next() {
		var i AppPlayerItem
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.DefID,
			&i.Slot,
			&i.Tier,
			&i.Ilvl,
			&i.QualityPct,
			&i.Masterwork,
			&i.Attack,
			&i.Defense,
			&i.Speed,
			&i.EquippedOnHero,
			&i.EquippedSoldierID,
			&i.AcquiredAt,
			&i.AcquiredFrom,
			&i.RolledConfigVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerItems = `-- name: ListPlayerItems :many
SELECT id, player_id, def_id, slot, tier, ilvl, quality_pct, masterwork, attack, defense, speed, equipped_on_hero, equipped_soldier_id, acquired_at, acquired_from, rolled_config_version FROM app.player_items WHERE player_id = $1 ORDER BY acquired_at DESC
`

func (q *Queries) ListPlayerItems(ctx context.Context, playerID uuid.UUID) ([]AppPlayerItem, error) {
	rows, err := q.db.Query(ctx, listPlayerItems, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPlayerItem{}
	for rows.Next() {
		var i AppPlayerItem
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.DefID,
			&i.Slot,
			&i.Tier,
			&i.Ilvl,
			&i.QualityPct,
			&i.Masterwork,
			&i.Attack,
			&i.Defense,
			&i.Speed,
			&i.EquippedOnHero,
			&i.EquippedSoldierID,
			&i.AcquiredAt,
			&i.AcquiredFrom,
			&i.RolledConfigVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPlayerItem = `-- name: LockPlayerItem :one
SELECT id, player_id, def_id, slot, tier, ilvl, quality_pct, masterwork, attack, defense, speed, equipped_on_hero, equipped_soldier_id, acquired_at, acquired_from, rolled_config_version FROM app.player_items WHERE id = $1 AND player_id = $2 FOR UPDATE
`

type LockPlayerItemParams struct {
	ID       uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) LockPlayerItem(ctx context.Context, arg LockPlayerItemParams) (AppPlayerItem, error) {
	row := q.db.QueryRow(ctx, lockPlayerItem, arg.ID, arg.PlayerID)
	var i AppPlayerItem
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.DefID,
		&i.Slot,
		&i.Tier,
		&i.Ilvl,
		&i.QualityPct,
		&i.Masterwork,
		&i.Attack,
		&i.Defense,
		&i.Speed,
		&i.EquippedOnHero,
		&i.EquippedSoldierID,
		&i.AcquiredAt,
		&i.AcquiredFrom,
		&i.RolledConfigVersion,
	)
	return i, err
}

const reforgePlayerItem = `-- name: ReforgePlayerItem :one
UPDATE app.player_items
SET quality_pct = $1,
    masterwork  = $2,
    attack      = $3,
    defense     = $4,
    speed       = $5
WHERE id = $6 AND player_id = $7
RETURNING id, player_id, def_id, slot, tier, ilvl, quality_pct, masterwork, attack, defense, speed, equipped_on_hero, equipped_soldier_id, acquired_at, acquired_from, rolled_config_version
`

type ReforgePlayerItemParams struct {
	QualityPct int32
	Masterwork bool
	Attack     int64
	Defense    int64
	Speed      int64
	ID         uuid.UUID
	PlayerID   uuid.UUID
}

// Rewrites the rolled half of an item: quality, the masterwork flag, and the
// stats they produce. Identity -- what it IS -- never moves.
func (q *Queries) ReforgePlayerItem(ctx context.Context, arg ReforgePlayerItemParams) (AppPlayerItem, error) {
	row := q.db.QueryRow(ctx, reforgePlayerItem,
		arg.QualityPct,
		arg.Masterwork,
		arg.Attack,
		arg.Defense,
		arg.Speed,
		arg.ID,
		arg.PlayerID,
	)
	var i AppPlayerItem
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.DefID,
		&i.Slot,
		&i.Tier,
		&i.Ilvl,
		&i.QualityPct,
		&i.Masterwork,
		&i.Attack,
		&i.Defense,
		&i.Speed,
		&i.EquippedOnHero,
		&i.EquippedSoldierID,
		&i.AcquiredAt,
		&i.AcquiredFrom,
		&i.RolledConfigVersion,
	)
	return i, err
}

const releaseItem = `-- name: ReleaseItem :exec
UPDATE app.player_items
SET equipped_on_hero = false, equipped_soldier_id = NULL
WHERE id = $1 AND player_id = $2
`

type ReleaseItemParams struct {
	ID       uuid.UUID
	PlayerID uuid.UUID
}

// Takes an item off whoever is wearing it: the hero, a soldier, or nobody.
//
// There are two holder columns, so "worn" is not one flag. Clearing only the
// hero's left a soldier's claim in place, and equipping a soldier's item onto
// the hero hit the one-item-per-slot index and surfaced as a 500.
func (q *Queries) ReleaseItem(ctx context.Context, arg ReleaseItemParams) error {
	_, err := q.db.Exec(ctx, releaseItem, arg.ID, arg.PlayerID)
	return err
}

const setHeroEquipped = `-- name: SetHeroEquipped :exec
UPDATE app.player_items
SET equipped_on_hero = $3
WHERE id = $1 AND player_id = $2
`

type SetHeroEquippedParams struct {
	ID             uuid.UUID
	PlayerID       uuid.UUID
	EquippedOnHero bool
}

func (q *Queries) SetHeroEquipped(ctx context.Context, arg SetHeroEquippedParams) error {
	_, err := q.db.Exec(ctx, setHeroEquipped, arg.ID, arg.PlayerID, arg.EquippedOnHero)
	return err
}

const unequipHeroSlot = `-- name: UnequipHeroSlot :exec
UPDATE app.player_items
SET equipped_on_hero = false
WHERE player_id = $1 AND slot = $2 AND equipped_on_hero
`

type UnequipHeroSlotParams struct {
	PlayerID uuid.UUID
	Slot     string
}

// Clears whatever the player is wearing in this slot, so equipping is a
// two-step swap that cannot transiently violate the one-item-per-slot index.
func (q *Queries) UnequipHeroSlot(ctx context.Context, arg UnequipHeroSlotParams) error {
	_, err := q.db.Exec(ctx, unequipHeroSlot, arg.PlayerID, arg.Slot)
	return err
}
