// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kingdoms.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addKingdomReputation = `-- name: AddKingdomReputation :exec
UPDATE app.kingdoms SET reputation = reputation + $2 WHERE id = $1
`

type AddKingdomReputationParams struct {
	ID         uuid.UUID
	Reputation int64
}

// Reputation from a raid, honouring the per-member daily cap.
func (q *Queries) AddKingdomReputation(ctx context.Context, arg AddKingdomReputationParams) error {
	_, err := q.db.Exec(ctx, addKingdomReputation, arg.ID, arg.Reputation)
	return err
}

const addKingdomTreasury = `-- name: AddKingdomTreasury :one
UPDATE app.kingdoms
SET treasury = treasury + $2, xp = xp + $3, level = $4
WHERE id = $1
RETURNING id, name, tag, leader_id, level, xp, treasury, reputation, created_at
`

type AddKingdomTreasuryParams struct {
	ID       uuid.UUID
	Treasury int64
	Xp       int64
	Level    int32
}

func (q *Queries) AddKingdomTreasury(ctx context.Context, arg AddKingdomTreasuryParams) (AppKingdom, error) {
	row := q.db.QueryRow(ctx, addKingdomTreasury,
		arg.ID,
		arg.Treasury,
		arg.Xp,
		arg.Level,
	)
	var i AppKingdom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.LeaderID,
		&i.Level,
		&i.Xp,
		&i.Treasury,
		&i.Reputation,
		&i.CreatedAt,
	)
	return i, err
}

const bumpMemberReputation = `-- name: BumpMemberReputation :one
UPDATE app.players
SET kingdom_rep_today = CASE WHEN kingdom_day = $3 THEN kingdom_rep_today + $2 ELSE $2 END,
    kingdom_day = $3
WHERE id = $1
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour
`

type BumpMemberReputationParams struct {
	ID              uuid.UUID
	KingdomRepToday int32
	KingdomDay      pgtype.Date
}

func (q *Queries) BumpMemberReputation(ctx context.Context, arg BumpMemberReputationParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, bumpMemberReputation, arg.ID, arg.KingdomRepToday, arg.KingdomDay)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
	)
	return i, err
}

const buyKingdomUpgradeLevel = `-- name: BuyKingdomUpgradeLevel :one
INSERT INTO app.kingdom_upgrades (kingdom_id, upgrade_id, level)
VALUES ($1, $2, 1)
ON CONFLICT (kingdom_id, upgrade_id) DO UPDATE
SET level = app.kingdom_upgrades.level + 1
WHERE app.kingdom_upgrades.level = $3
RETURNING kingdom_id, upgrade_id, level
`

type BuyKingdomUpgradeLevelParams struct {
	KingdomID uuid.UUID
	UpgradeID string
	Level     int32
}

func (q *Queries) BuyKingdomUpgradeLevel(ctx context.Context, arg BuyKingdomUpgradeLevelParams) (AppKingdomUpgrade, error) {
	row := q.db.QueryRow(ctx, buyKingdomUpgradeLevel, arg.KingdomID, arg.UpgradeID, arg.Level)
	var i AppKingdomUpgrade
	err := row.Scan(&i.KingdomID, &i.UpgradeID, &i.Level)
	return i, err
}

const countKingdomMembers = `-- name: CountKingdomMembers :one
SELECT count(*) FROM app.players WHERE kingdom_id = $1
`

func (q *Queries) CountKingdomMembers(ctx context.Context, kingdomID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countKingdomMembers, kingdomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO app.kingdom_invites (kingdom_id, player_id, invited_by)
VALUES ($1, $2, $3)
ON CONFLICT (kingdom_id, player_id) DO UPDATE SET created_at = now(), invited_by = EXCLUDED.invited_by
`

type CreateInviteParams struct {
	KingdomID uuid.UUID
	PlayerID  uuid.UUID
	InvitedBy *uuid.UUID
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.Exec(ctx, createInvite, arg.KingdomID, arg.PlayerID, arg.InvitedBy)
	return err
}

const createKingdom = `-- name: CreateKingdom :one
INSERT INTO app.kingdoms (name, tag, leader_id) VALUES ($1, $2, $3) RETURNING id, name, tag, leader_id, level, xp, treasury, reputation, created_at
`

type CreateKingdomParams struct {
	Name     string
	Tag      string
	LeaderID *uuid.UUID
}

func (q *Queries) CreateKingdom(ctx context.Context, arg CreateKingdomParams) (AppKingdom, error) {
	row := q.db.QueryRow(ctx, createKingdom, arg.Name, arg.Tag, arg.LeaderID)
	var i AppKingdom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.LeaderID,
		&i.Level,
		&i.Xp,
		&i.Treasury,
		&i.Reputation,
		&i.CreatedAt,
	)
	return i, err
}

const decayReputation = `-- name: DecayReputation :exec
UPDATE app.kingdoms SET reputation = reputation * (10000 - $1) / 10000 WHERE reputation > 0
`

// Nightly decay. 2% a day is what stops a kingdom that quit in month one from
// squatting at rank 1 forever.
func (q *Queries) DecayReputation(ctx context.Context, dollar_1 interface{}) error {
	_, err := q.db.Exec(ctx, decayReputation, dollar_1)
	return err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM app.kingdom_invites WHERE kingdom_id = $1 AND player_id = $2
`

type DeleteInviteParams struct {
	KingdomID uuid.UUID
	PlayerID  uuid.UUID
}

func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) error {
	_, err := q.db.Exec(ctx, deleteInvite, arg.KingdomID, arg.PlayerID)
	return err
}

const deleteInvitesForPlayer = `-- name: DeleteInvitesForPlayer :exec
DELETE FROM app.kingdom_invites WHERE player_id = $1
`

func (q *Queries) DeleteInvitesForPlayer(ctx context.Context, playerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvitesForPlayer, playerID)
	return err
}

const donateGold = `-- name: DonateGold :one
UPDATE app.players
SET gold = gold - $2,
    kingdom_donated_total = kingdom_donated_total + $2,
    kingdom_donated_today = CASE WHEN kingdom_day = $3 THEN kingdom_donated_today + $2 ELSE $2 END,
    kingdom_day = $3,
    kingdom_favour = kingdom_favour + $4,
    action_seq = $5,
    last_seen_at = now()
WHERE id = $1 AND gold >= $2
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour
`

type DonateGoldParams struct {
	ID            uuid.UUID
	Gold          int64
	KingdomDay    pgtype.Date
	KingdomFavour int64
	ActionSeq     int64
}

// Donating: take the gold, credit the treasury, and record the daily total in
// one place so the cap cannot be bypassed by racing two requests.
func (q *Queries) DonateGold(ctx context.Context, arg DonateGoldParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, donateGold,
		arg.ID,
		arg.Gold,
		arg.KingdomDay,
		arg.KingdomFavour,
		arg.ActionSeq,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
	)
	return i, err
}

const getInvite = `-- name: GetInvite :one
SELECT kingdom_id, player_id, invited_by, created_at FROM app.kingdom_invites WHERE kingdom_id = $1 AND player_id = $2
`

type GetInviteParams struct {
	KingdomID uuid.UUID
	PlayerID  uuid.UUID
}

func (q *Queries) GetInvite(ctx context.Context, arg GetInviteParams) (AppKingdomInvite, error) {
	row := q.db.QueryRow(ctx, getInvite, arg.KingdomID, arg.PlayerID)
	var i AppKingdomInvite
	err := row.Scan(
		&i.KingdomID,
		&i.PlayerID,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getKingdom = `-- name: GetKingdom :one
SELECT id, name, tag, leader_id, level, xp, treasury, reputation, created_at FROM app.kingdoms WHERE id = $1
`

func (q *Queries) GetKingdom(ctx context.Context, id uuid.UUID) (AppKingdom, error) {
	row := q.db.QueryRow(ctx, getKingdom, id)
	var i AppKingdom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.LeaderID,
		&i.Level,
		&i.Xp,
		&i.Treasury,
		&i.Reputation,
		&i.CreatedAt,
	)
	return i, err
}

const leaveKingdom = `-- name: LeaveKingdom :one
UPDATE app.players
SET kingdom_id = NULL, kingdom_role = 'none', kingdom_joined_at = NULL
WHERE id = $1
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour
`

func (q *Queries) LeaveKingdom(ctx context.Context, id uuid.UUID) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, leaveKingdom, id)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
	)
	return i, err
}

const listInvitesForPlayer = `-- name: ListInvitesForPlayer :many
SELECT i.kingdom_id, i.created_at, k.name, k.tag, k.level, k.reputation
FROM app.kingdom_invites i JOIN app.kingdoms k ON k.id = i.kingdom_id
WHERE i.player_id = $1
ORDER BY i.created_at DESC
`

type ListInvitesForPlayerRow struct {
	KingdomID  uuid.UUID
	CreatedAt  time.Time
	Name       string
	Tag        string
	Level      int32
	Reputation int64
}

func (q *Queries) ListInvitesForPlayer(ctx context.Context, playerID uuid.UUID) ([]ListInvitesForPlayerRow, error) {
	rows, err := q.db.Query(ctx, listInvitesForPlayer, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitesForPlayerRow{}
	for rows.Next() {
		var i ListInvitesForPlayerRow
		if err := rows.Scan(
			&i.KingdomID,
			&i.CreatedAt,
			&i.Name,
			&i.Tag,
			&i.Level,
			&i.Reputation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKingdomMembers = `-- name: ListKingdomMembers :many
SELECT id, display_name, level, kingdom_role, kingdom_joined_at,
       kingdom_donated_total, kingdom_favour
FROM app.players
WHERE kingdom_id = $1
ORDER BY CASE kingdom_role WHEN 'king' THEN 0 WHEN 'marshal' THEN 1 ELSE 2 END,
         kingdom_donated_total DESC
`

type ListKingdomMembersRow struct {
	ID                  uuid.UUID
	DisplayName         string
	Level               int32
	KingdomRole         string
	KingdomJoinedAt     *time.Time
	KingdomDonatedTotal int64
	KingdomFavour       int64
}

// Ordered by rank then contribution, which is the order the roster should read:
// who leads, then who has actually carried the kingdom.
func (q *Queries) ListKingdomMembers(ctx context.Context, kingdomID *uuid.UUID) ([]ListKingdomMembersRow, error) {
	rows, err := q.db.Query(ctx, listKingdomMembers, kingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKingdomMembersRow{}
	for rows.Next() {
		var i ListKingdomMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Level,
			&i.KingdomRole,
			&i.KingdomJoinedAt,
			&i.KingdomDonatedTotal,
			&i.KingdomFavour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKingdomUpgrades = `-- name: ListKingdomUpgrades :many
SELECT kingdom_id, upgrade_id, level FROM app.kingdom_upgrades WHERE kingdom_id = $1
`

func (q *Queries) ListKingdomUpgrades(ctx context.Context, kingdomID uuid.UUID) ([]AppKingdomUpgrade, error) {
	rows, err := q.db.Query(ctx, listKingdomUpgrades, kingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppKingdomUpgrade{}
	for rows.Next() {
		var i AppKingdomUpgrade
		if err := rows.Scan(&i.KingdomID, &i.UpgradeID, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockKingdom = `-- name: LockKingdom :one
SELECT id, name, tag, leader_id, level, xp, treasury, reputation, created_at FROM app.kingdoms WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockKingdom(ctx context.Context, id uuid.UUID) (AppKingdom, error) {
	row := q.db.QueryRow(ctx, lockKingdom, id)
	var i AppKingdom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.LeaderID,
		&i.Level,
		&i.Xp,
		&i.Treasury,
		&i.Reputation,
		&i.CreatedAt,
	)
	return i, err
}

const payAndJoinKingdom = `-- name: PayAndJoinKingdom :one
UPDATE app.players
SET gold = gold - $2, kingdom_id = $3, kingdom_role = $4,
    kingdom_joined_at = now(), action_seq = $5, last_seen_at = now()
WHERE id = $1 AND gold >= $2 AND kingdom_id IS NULL
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour
`

type PayAndJoinKingdomParams struct {
	ID          uuid.UUID
	Gold        int64
	KingdomID   *uuid.UUID
	KingdomRole string
	ActionSeq   int64
}

// Founding: pay, and join in the same statement so a crash cannot leave a
// kingdom with no king.
func (q *Queries) PayAndJoinKingdom(ctx context.Context, arg PayAndJoinKingdomParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, payAndJoinKingdom,
		arg.ID,
		arg.Gold,
		arg.KingdomID,
		arg.KingdomRole,
		arg.ActionSeq,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
	)
	return i, err
}

const searchKingdoms = `-- name: SearchKingdoms :many
SELECT k.id, k.name, k.tag, k.leader_id, k.level, k.xp, k.treasury, k.reputation, k.created_at, (SELECT count(*) FROM app.players p WHERE p.kingdom_id = k.id) AS members
FROM app.kingdoms k
WHERE lower(k.name) LIKE lower($1) OR lower(k.tag) LIKE lower($1)
ORDER BY k.reputation DESC
LIMIT 20
`

type SearchKingdomsRow struct {
	ID         uuid.UUID
	Name       string
	Tag        string
	LeaderID   *uuid.UUID
	Level      int32
	Xp         int64
	Treasury   int64
	Reputation int64
	CreatedAt  time.Time
	Members    int64
}

func (q *Queries) SearchKingdoms(ctx context.Context, lower string) ([]SearchKingdomsRow, error) {
	rows, err := q.db.Query(ctx, searchKingdoms, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchKingdomsRow{}
	for rows.Next() {
		var i SearchKingdomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tag,
			&i.LeaderID,
			&i.Level,
			&i.Xp,
			&i.Treasury,
			&i.Reputation,
			&i.CreatedAt,
			&i.Members,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setKingdomRole = `-- name: SetKingdomRole :one
UPDATE app.players SET kingdom_role = $2 WHERE id = $1 AND kingdom_id = $3 RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour
`

type SetKingdomRoleParams struct {
	ID          uuid.UUID
	KingdomRole string
	KingdomID   *uuid.UUID
}

func (q *Queries) SetKingdomRole(ctx context.Context, arg SetKingdomRoleParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, setKingdomRole, arg.ID, arg.KingdomRole, arg.KingdomID)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
	)
	return i, err
}

const setPlayerKingdom = `-- name: SetPlayerKingdom :one
UPDATE app.players
SET kingdom_id = $2, kingdom_role = $3, kingdom_joined_at = $4
WHERE id = $1
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour
`

type SetPlayerKingdomParams struct {
	ID              uuid.UUID
	KingdomID       *uuid.UUID
	KingdomRole     string
	KingdomJoinedAt *time.Time
}

func (q *Queries) SetPlayerKingdom(ctx context.Context, arg SetPlayerKingdomParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, setPlayerKingdom,
		arg.ID,
		arg.KingdomID,
		arg.KingdomRole,
		arg.KingdomJoinedAt,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
	)
	return i, err
}

const spendKingdomTreasury = `-- name: SpendKingdomTreasury :one
UPDATE app.kingdoms SET treasury = treasury - $2 WHERE id = $1 AND treasury >= $2 RETURNING id, name, tag, leader_id, level, xp, treasury, reputation, created_at
`

type SpendKingdomTreasuryParams struct {
	ID       uuid.UUID
	Treasury int64
}

func (q *Queries) SpendKingdomTreasury(ctx context.Context, arg SpendKingdomTreasuryParams) (AppKingdom, error) {
	row := q.db.QueryRow(ctx, spendKingdomTreasury, arg.ID, arg.Treasury)
	var i AppKingdom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.LeaderID,
		&i.Level,
		&i.Xp,
		&i.Treasury,
		&i.Reputation,
		&i.CreatedAt,
	)
	return i, err
}

const topKingdoms = `-- name: TopKingdoms :many
SELECT k.id, k.name, k.tag, k.leader_id, k.level, k.xp, k.treasury, k.reputation, k.created_at, (SELECT count(*) FROM app.players p WHERE p.kingdom_id = k.id) AS members
FROM app.kingdoms k
ORDER BY k.reputation DESC, k.xp DESC
LIMIT $1
`

type TopKingdomsRow struct {
	ID         uuid.UUID
	Name       string
	Tag        string
	LeaderID   *uuid.UUID
	Level      int32
	Xp         int64
	Treasury   int64
	Reputation int64
	CreatedAt  time.Time
	Members    int64
}

func (q *Queries) TopKingdoms(ctx context.Context, limit int32) ([]TopKingdomsRow, error) {
	rows, err := q.db.Query(ctx, topKingdoms, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopKingdomsRow{}
	for rows.Next() {
		var i TopKingdomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tag,
			&i.LeaderID,
			&i.Level,
			&i.Xp,
			&i.Treasury,
			&i.Reputation,
			&i.CreatedAt,
			&i.Members,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
