// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kingdoms.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addKingdomReputation = `-- name: AddKingdomReputation :exec
UPDATE app.kingdoms SET reputation = reputation + $2 WHERE id = $1
`

type AddKingdomReputationParams struct {
	ID         uuid.UUID
	Reputation int64
}

// Reputation from a raid, honouring the per-member daily cap.
func (q *Queries) AddKingdomReputation(ctx context.Context, arg AddKingdomReputationParams) error {
	_, err := q.db.Exec(ctx, addKingdomReputation, arg.ID, arg.Reputation)
	return err
}

const addKingdomTreasury = `-- name: AddKingdomTreasury :one
UPDATE app.kingdoms
SET treasury = treasury + $2, xp = xp + $3, level = $4
WHERE id = $1
RETURNING id, name, tag, leader_id, level, xp, treasury, reputation, created_at, join_policy
`

type AddKingdomTreasuryParams struct {
	ID       uuid.UUID
	Treasury int64
	Xp       int64
	Level    int32
}

func (q *Queries) AddKingdomTreasury(ctx context.Context, arg AddKingdomTreasuryParams) (AppKingdom, error) {
	row := q.db.QueryRow(ctx, addKingdomTreasury,
		arg.ID,
		arg.Treasury,
		arg.Xp,
		arg.Level,
	)
	var i AppKingdom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.LeaderID,
		&i.Level,
		&i.Xp,
		&i.Treasury,
		&i.Reputation,
		&i.CreatedAt,
		&i.JoinPolicy,
	)
	return i, err
}

const bumpMemberReputation = `-- name: BumpMemberReputation :one
UPDATE app.players
SET kingdom_rep_today = CASE WHEN kingdom_day = $3 THEN kingdom_rep_today + $2 ELSE $2 END,
    kingdom_day = $3
WHERE id = $1
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at
`

type BumpMemberReputationParams struct {
	ID              uuid.UUID
	KingdomRepToday int32
	KingdomDay      pgtype.Date
}

func (q *Queries) BumpMemberReputation(ctx context.Context, arg BumpMemberReputationParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, bumpMemberReputation, arg.ID, arg.KingdomRepToday, arg.KingdomDay)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
	)
	return i, err
}

const buyKingdomUpgradeLevel = `-- name: BuyKingdomUpgradeLevel :one
INSERT INTO app.kingdom_upgrades (kingdom_id, upgrade_id, level)
VALUES ($1, $2, 1)
ON CONFLICT (kingdom_id, upgrade_id) DO UPDATE
SET level = app.kingdom_upgrades.level + 1
WHERE app.kingdom_upgrades.level = $3
RETURNING kingdom_id, upgrade_id, level
`

type BuyKingdomUpgradeLevelParams struct {
	KingdomID uuid.UUID
	UpgradeID string
	Level     int32
}

func (q *Queries) BuyKingdomUpgradeLevel(ctx context.Context, arg BuyKingdomUpgradeLevelParams) (AppKingdomUpgrade, error) {
	row := q.db.QueryRow(ctx, buyKingdomUpgradeLevel, arg.KingdomID, arg.UpgradeID, arg.Level)
	var i AppKingdomUpgrade
	err := row.Scan(&i.KingdomID, &i.UpgradeID, &i.Level)
	return i, err
}

const claimDecayDay = `-- name: ClaimDecayDay :one
INSERT INTO app.server_info (key, value, updated_at)
VALUES ('reputation_decay_day', $1, now())
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, updated_at = now()
WHERE app.server_info.value < EXCLUDED.value
RETURNING value
`

// Claims one calendar day's reputation decay, atomically.
//
// The whole point is the WHERE: two API replicas, or one that restarted twice in
// an evening, must not both decay the same day. The insert only lands when the
// stored marker is behind the day being claimed, so whoever gets there first
// does the work and everyone else gets zero rows back.
func (q *Queries) ClaimDecayDay(ctx context.Context, day string) (string, error) {
	row := q.db.QueryRow(ctx, claimDecayDay, day)
	var value string
	err := row.Scan(&value)
	return value, err
}

const countKingdomMembers = `-- name: CountKingdomMembers :one
SELECT count(*) FROM app.players WHERE kingdom_id = $1
`

func (q *Queries) CountKingdomMembers(ctx context.Context, kingdomID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countKingdomMembers, kingdomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsForPlayer = `-- name: CountRequestsForPlayer :one
SELECT count(*) FROM app.kingdom_invites WHERE player_id = $1 AND direction = 'request'
`

func (q *Queries) CountRequestsForPlayer(ctx context.Context, playerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsForPlayer, playerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvite = `-- name: CreateInvite :execrows
INSERT INTO app.kingdom_invites (kingdom_id, player_id, invited_by, direction)
VALUES ($1, $2, $3, 'invite')
ON CONFLICT (kingdom_id, player_id) DO UPDATE
SET created_at = now(), invited_by = EXCLUDED.invited_by
WHERE app.kingdom_invites.direction = 'invite'
`

type CreateInviteParams struct {
	KingdomID uuid.UUID
	PlayerID  uuid.UUID
	InvitedBy *uuid.UUID
}

// An invitation and a request share one row per (kingdom, player). Refreshing
// an invitation must never turn a pending request into one -- the WHERE on the
// update is what stops it -- so zero rows means a request was standing.
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, createInvite, arg.KingdomID, arg.PlayerID, arg.InvitedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createJoinRequest = `-- name: CreateJoinRequest :execrows
INSERT INTO app.kingdom_invites (kingdom_id, player_id, invited_by, direction)
VALUES ($1, $2, NULL, 'request')
ON CONFLICT (kingdom_id, player_id) DO NOTHING
`

type CreateJoinRequestParams struct {
	KingdomID uuid.UUID
	PlayerID  uuid.UUID
}

func (q *Queries) CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, createJoinRequest, arg.KingdomID, arg.PlayerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createKingdom = `-- name: CreateKingdom :one
INSERT INTO app.kingdoms (name, tag, leader_id) VALUES ($1, $2, $3) RETURNING id, name, tag, leader_id, level, xp, treasury, reputation, created_at, join_policy
`

type CreateKingdomParams struct {
	Name     string
	Tag      string
	LeaderID *uuid.UUID
}

func (q *Queries) CreateKingdom(ctx context.Context, arg CreateKingdomParams) (AppKingdom, error) {
	row := q.db.QueryRow(ctx, createKingdom, arg.Name, arg.Tag, arg.LeaderID)
	var i AppKingdom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.LeaderID,
		&i.Level,
		&i.Xp,
		&i.Treasury,
		&i.Reputation,
		&i.CreatedAt,
		&i.JoinPolicy,
	)
	return i, err
}

const decayReputation = `-- name: DecayReputation :exec
UPDATE app.kingdoms SET reputation = reputation * (10000 - $1) / 10000 WHERE reputation > 0
`

// Nightly decay. 2% a day is what stops a kingdom that quit in month one from
// squatting at rank 1 forever.
func (q *Queries) DecayReputation(ctx context.Context, dollar_1 interface{}) error {
	_, err := q.db.Exec(ctx, decayReputation, dollar_1)
	return err
}

const deleteInvite = `-- name: DeleteInvite :execrows
DELETE FROM app.kingdom_invites WHERE kingdom_id = $1 AND player_id = $2 AND direction = $3
`

type DeleteInviteParams struct {
	KingdomID uuid.UUID
	PlayerID  uuid.UUID
	Direction string
}

func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvite, arg.KingdomID, arg.PlayerID, arg.Direction)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteInvitesForPlayer = `-- name: DeleteInvitesForPlayer :exec
DELETE FROM app.kingdom_invites WHERE player_id = $1
`

func (q *Queries) DeleteInvitesForPlayer(ctx context.Context, playerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvitesForPlayer, playerID)
	return err
}

const deleteKingdomIfEmpty = `-- name: DeleteKingdomIfEmpty :execrows
DELETE FROM app.kingdoms k
WHERE k.id = $1
  AND NOT EXISTS (SELECT 1 FROM app.players p WHERE p.kingdom_id = k.id)
`

// A kingdom is deleted when its last lord leaves -- and only then. The guard is
// not a courtesy: players_kingdom_role_consistent would abort a delete that
// nulled a member's kingdom_id under a role that is still 'member'.
func (q *Queries) DeleteKingdomIfEmpty(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteKingdomIfEmpty, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const donateGold = `-- name: DonateGold :one
UPDATE app.players
SET gold = gold - $2,
    kingdom_donated_total = kingdom_donated_total + $2,
    kingdom_donated_today = CASE WHEN kingdom_day = $3 THEN kingdom_donated_today + $2 ELSE $2 END,
    kingdom_day = $3,
    kingdom_favour = kingdom_favour + $4,
    action_seq = $5
WHERE id = $1 AND gold >= $2
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at
`

type DonateGoldParams struct {
	ID            uuid.UUID
	Gold          int64
	KingdomDay    pgtype.Date
	KingdomFavour int64
	ActionSeq     int64
}

// Donating: take the gold, credit the treasury, and record the daily total in
// one place so the cap cannot be bypassed by racing two requests.
func (q *Queries) DonateGold(ctx context.Context, arg DonateGoldParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, donateGold,
		arg.ID,
		arg.Gold,
		arg.KingdomDay,
		arg.KingdomFavour,
		arg.ActionSeq,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
	)
	return i, err
}

const getInvite = `-- name: GetInvite :one
SELECT kingdom_id, player_id, invited_by, created_at, direction FROM app.kingdom_invites
WHERE kingdom_id = $1 AND player_id = $2 AND direction = 'invite'
`

type GetInviteParams struct {
	KingdomID uuid.UUID
	PlayerID  uuid.UUID
}

// Only an invitation. Unscoped, /accept would seat a player in a kingdom they
// had merely asked to join.
func (q *Queries) GetInvite(ctx context.Context, arg GetInviteParams) (AppKingdomInvite, error) {
	row := q.db.QueryRow(ctx, getInvite, arg.KingdomID, arg.PlayerID)
	var i AppKingdomInvite
	err := row.Scan(
		&i.KingdomID,
		&i.PlayerID,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.Direction,
	)
	return i, err
}

const getJoinRequest = `-- name: GetJoinRequest :one
SELECT kingdom_id, player_id, invited_by, created_at, direction FROM app.kingdom_invites
WHERE kingdom_id = $1 AND player_id = $2 AND direction = 'request'
`

type GetJoinRequestParams struct {
	KingdomID uuid.UUID
	PlayerID  uuid.UUID
}

func (q *Queries) GetJoinRequest(ctx context.Context, arg GetJoinRequestParams) (AppKingdomInvite, error) {
	row := q.db.QueryRow(ctx, getJoinRequest, arg.KingdomID, arg.PlayerID)
	var i AppKingdomInvite
	err := row.Scan(
		&i.KingdomID,
		&i.PlayerID,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.Direction,
	)
	return i, err
}

const getKingdom = `-- name: GetKingdom :one
SELECT id, name, tag, leader_id, level, xp, treasury, reputation, created_at, join_policy FROM app.kingdoms WHERE id = $1
`

func (q *Queries) GetKingdom(ctx context.Context, id uuid.UUID) (AppKingdom, error) {
	row := q.db.QueryRow(ctx, getKingdom, id)
	var i AppKingdom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.LeaderID,
		&i.Level,
		&i.Xp,
		&i.Treasury,
		&i.Reputation,
		&i.CreatedAt,
		&i.JoinPolicy,
	)
	return i, err
}

const grantXPBoost = `-- name: GrantXPBoost :exec
UPDATE app.players
SET xp_boost_bp = $1, xp_boost_expires_at = $2
WHERE id = $3
`

type GrantXPBoostParams struct {
	Bp        int32
	ExpiresAt *time.Time
	ID        uuid.UUID
}

func (q *Queries) GrantXPBoost(ctx context.Context, arg GrantXPBoostParams) error {
	_, err := q.db.Exec(ctx, grantXPBoost, arg.Bp, arg.ExpiresAt, arg.ID)
	return err
}

const kickFromKingdom = `-- name: KickFromKingdom :one
UPDATE app.players
SET kingdom_id = NULL, kingdom_role = 'none', kingdom_joined_at = NULL,
    kingdom_left_at = $1
WHERE id = $2 AND kingdom_id = $3
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at
`

type KickFromKingdomParams struct {
	LeftAt    *time.Time
	ID        uuid.UUID
	KingdomID *uuid.UUID
}

// Removal by a king or captain. Guarded by the kingdom, so a removal that races
// the lord's own leave-and-join cannot take them out of the kingdom they moved to.
func (q *Queries) KickFromKingdom(ctx context.Context, arg KickFromKingdomParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, kickFromKingdom, arg.LeftAt, arg.ID, arg.KingdomID)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
	)
	return i, err
}

const leaveKingdom = `-- name: LeaveKingdom :one
UPDATE app.players
SET kingdom_id = NULL, kingdom_role = 'none', kingdom_joined_at = NULL,
    kingdom_left_at = $1
WHERE id = $2
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at
`

type LeaveKingdomParams struct {
	LeftAt *time.Time
	ID     uuid.UUID
}

// Leaving stamps the time, which is what the rejoin cooldown is measured from.
func (q *Queries) LeaveKingdom(ctx context.Context, arg LeaveKingdomParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, leaveKingdom, arg.LeftAt, arg.ID)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
	)
	return i, err
}

const listInvitesForPlayer = `-- name: ListInvitesForPlayer :many
SELECT k.id, k.name, k.tag, k.level, k.reputation, k.join_policy, i.created_at,
       (SELECT count(*) FROM app.players m WHERE m.kingdom_id = k.id)::int AS members,
       coalesce((SELECT u.level FROM app.kingdom_upgrades u
                 WHERE u.kingdom_id = k.id AND u.upgrade_id = $1), 0)::int AS court_level,
       coalesce((SELECT m.display_name FROM app.players m
                 WHERE m.kingdom_id = k.id AND m.kingdom_role = 'king' LIMIT 1), '')::text AS king_name
FROM app.kingdom_invites i JOIN app.kingdoms k ON k.id = i.kingdom_id
WHERE i.player_id = $2 AND i.direction = 'invite'
ORDER BY i.created_at DESC
`

type ListInvitesForPlayerParams struct {
	CourtID  string
	PlayerID uuid.UUID
}

type ListInvitesForPlayerRow struct {
	ID         uuid.UUID
	Name       string
	Tag        string
	Level      int32
	Reputation int64
	JoinPolicy string
	CreatedAt  time.Time
	Members    int32
	CourtLevel int32
	KingName   string
}

// The invitations a kingdomless player holds, as cards: everything the hall
// shows about a kingdom, so an invitation reads like any other kingdom.
func (q *Queries) ListInvitesForPlayer(ctx context.Context, arg ListInvitesForPlayerParams) ([]ListInvitesForPlayerRow, error) {
	rows, err := q.db.Query(ctx, listInvitesForPlayer, arg.CourtID, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitesForPlayerRow{}
	for rows.Next() {
		var i ListInvitesForPlayerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tag,
			&i.Level,
			&i.Reputation,
			&i.JoinPolicy,
			&i.CreatedAt,
			&i.Members,
			&i.CourtLevel,
			&i.KingName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKingdomMembers = `-- name: ListKingdomMembers :many
SELECT id, display_name, level, kingdom_role, kingdom_joined_at,
       kingdom_donated_total, kingdom_favour
FROM app.players
WHERE kingdom_id = $1
ORDER BY CASE kingdom_role WHEN 'king' THEN 0 WHEN 'marshal' THEN 1 ELSE 2 END,
         kingdom_donated_total DESC
`

type ListKingdomMembersRow struct {
	ID                  uuid.UUID
	DisplayName         string
	Level               int32
	KingdomRole         string
	KingdomJoinedAt     *time.Time
	KingdomDonatedTotal int64
	KingdomFavour       int64
}

// Ordered by rank then contribution, which is the order the roster should read:
// who leads, then who has actually carried the kingdom.
func (q *Queries) ListKingdomMembers(ctx context.Context, kingdomID *uuid.UUID) ([]ListKingdomMembersRow, error) {
	rows, err := q.db.Query(ctx, listKingdomMembers, kingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKingdomMembersRow{}
	for rows.Next() {
		var i ListKingdomMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Level,
			&i.KingdomRole,
			&i.KingdomJoinedAt,
			&i.KingdomDonatedTotal,
			&i.KingdomFavour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKingdomUpgrades = `-- name: ListKingdomUpgrades :many
SELECT kingdom_id, upgrade_id, level FROM app.kingdom_upgrades WHERE kingdom_id = $1
`

func (q *Queries) ListKingdomUpgrades(ctx context.Context, kingdomID uuid.UUID) ([]AppKingdomUpgrade, error) {
	rows, err := q.db.Query(ctx, listKingdomUpgrades, kingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppKingdomUpgrade{}
	for rows.Next() {
		var i AppKingdomUpgrade
		if err := rows.Scan(&i.KingdomID, &i.UpgradeID, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsForKingdom = `-- name: ListRequestsForKingdom :many
SELECT p.id, p.display_name, p.level, i.created_at
FROM app.kingdom_invites i JOIN app.players p ON p.id = i.player_id
WHERE i.kingdom_id = $1 AND i.direction = 'request' AND p.kingdom_id IS NULL
ORDER BY i.created_at
LIMIT 50
`

type ListRequestsForKingdomRow struct {
	ID          uuid.UUID
	DisplayName string
	Level       int32
	CreatedAt   time.Time
}

// Who has asked to join, oldest first: the Lords tab answers them in order.
func (q *Queries) ListRequestsForKingdom(ctx context.Context, kingdomID uuid.UUID) ([]ListRequestsForKingdomRow, error) {
	rows, err := q.db.Query(ctx, listRequestsForKingdom, kingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsForKingdomRow{}
	for rows.Next() {
		var i ListRequestsForKingdomRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Level,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsForPlayer = `-- name: ListRequestsForPlayer :many
SELECT kingdom_id FROM app.kingdom_invites WHERE player_id = $1 AND direction = 'request'
`

func (q *Queries) ListRequestsForPlayer(ctx context.Context, playerID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listRequestsForPlayer, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var kingdom_id uuid.UUID
		if err := rows.Scan(&kingdom_id); err != nil {
			return nil, err
		}
		items = append(items, kingdom_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockKingdom = `-- name: LockKingdom :one
SELECT id, name, tag, leader_id, level, xp, treasury, reputation, created_at, join_policy FROM app.kingdoms WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockKingdom(ctx context.Context, id uuid.UUID) (AppKingdom, error) {
	row := q.db.QueryRow(ctx, lockKingdom, id)
	var i AppKingdom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.LeaderID,
		&i.Level,
		&i.Xp,
		&i.Treasury,
		&i.Reputation,
		&i.CreatedAt,
		&i.JoinPolicy,
	)
	return i, err
}

const payAndJoinKingdom = `-- name: PayAndJoinKingdom :one
UPDATE app.players
SET gold = gold - $2, kingdom_id = $3, kingdom_role = $4,
    kingdom_joined_at = now(), action_seq = $5
WHERE id = $1 AND gold >= $2 AND kingdom_id IS NULL
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at
`

type PayAndJoinKingdomParams struct {
	ID          uuid.UUID
	Gold        int64
	KingdomID   *uuid.UUID
	KingdomRole string
	ActionSeq   int64
}

// Founding: pay, and join in the same statement so a crash cannot leave a
// kingdom with no king.
func (q *Queries) PayAndJoinKingdom(ctx context.Context, arg PayAndJoinKingdomParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, payAndJoinKingdom,
		arg.ID,
		arg.Gold,
		arg.KingdomID,
		arg.KingdomRole,
		arg.ActionSeq,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
	)
	return i, err
}

const recommendKingdoms = `-- name: RecommendKingdoms :many
SELECT k.id, k.name, k.tag, k.level, k.reputation, k.join_policy,
       count(p.id)::int AS members,
       (count(p.id) FILTER (WHERE p.last_seen_at > $1))::int AS active,
       coalesce((SELECT u.level FROM app.kingdom_upgrades u
                 WHERE u.kingdom_id = k.id AND u.upgrade_id = $2), 0)::int AS court_level,
       coalesce(max(p.display_name) FILTER (WHERE p.kingdom_role = 'king'), '')::text AS king_name
FROM app.kingdoms k
JOIN app.players p ON p.kingdom_id = k.id
GROUP BY k.id
ORDER BY active DESC, k.reputation DESC, k.level DESC, k.created_at
LIMIT $3
`

type RecommendKingdomsParams struct {
	ActiveSince time.Time
	CourtID     string
	MaxRows     int32
}

type RecommendKingdomsRow struct {
	ID         uuid.UUID
	Name       string
	Tag        string
	Level      int32
	Reputation int64
	JoinPolicy string
	Members    int32
	Active     int32
	CourtLevel int32
	KingName   string
}

// Kingdoms worth suggesting to someone with none: every kingdom that still has
// lords, the busiest first -- a kingdom whose members were here this week is a
// kingdom that will answer, which a big quiet one will not -- then by renown.
// The service drops the full ones against the real cap, Royal Court included,
// which SQL cannot see; hence more candidates than it shows.
func (q *Queries) RecommendKingdoms(ctx context.Context, arg RecommendKingdomsParams) ([]RecommendKingdomsRow, error) {
	rows, err := q.db.Query(ctx, recommendKingdoms, arg.ActiveSince, arg.CourtID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecommendKingdomsRow{}
	for rows.Next() {
		var i RecommendKingdomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tag,
			&i.Level,
			&i.Reputation,
			&i.JoinPolicy,
			&i.Members,
			&i.Active,
			&i.CourtLevel,
			&i.KingName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refillEnergy = `-- name: RefillEnergy :exec
UPDATE app.players
SET energy_milli = $1, energy_updated_at = $2
WHERE id = $3
`

type RefillEnergyParams struct {
	EnergyMilli int64
	Now         time.Time
	ID          uuid.UUID
}

func (q *Queries) RefillEnergy(ctx context.Context, arg RefillEnergyParams) error {
	_, err := q.db.Exec(ctx, refillEnergy, arg.EnergyMilli, arg.Now, arg.ID)
	return err
}

const renameKingdom = `-- name: RenameKingdom :one
UPDATE app.kingdoms
SET name = $1
WHERE id = $2 AND leader_id = $3
RETURNING id, name, tag, leader_id, level, xp, treasury, reputation, created_at, join_policy
`

type RenameKingdomParams struct {
	Name     string
	ID       uuid.UUID
	LeaderID *uuid.UUID
}

// Renames a kingdom, and only for its king. The WHERE carries the permission,
// so a lord who reaches the endpoint gets no rows rather than a rename.
func (q *Queries) RenameKingdom(ctx context.Context, arg RenameKingdomParams) (AppKingdom, error) {
	row := q.db.QueryRow(ctx, renameKingdom, arg.Name, arg.ID, arg.LeaderID)
	var i AppKingdom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.LeaderID,
		&i.Level,
		&i.Xp,
		&i.Treasury,
		&i.Reputation,
		&i.CreatedAt,
		&i.JoinPolicy,
	)
	return i, err
}

const searchKingdoms = `-- name: SearchKingdoms :many
SELECT k.id, k.name, k.tag, k.level, k.reputation, k.join_policy,
       count(p.id)::int AS members,
       coalesce((SELECT u.level FROM app.kingdom_upgrades u
                 WHERE u.kingdom_id = k.id AND u.upgrade_id = $1), 0)::int AS court_level,
       coalesce(max(p.display_name) FILTER (WHERE p.kingdom_role = 'king'), '')::text AS king_name
FROM app.kingdoms k
JOIN app.players p ON p.kingdom_id = k.id
WHERE lower(k.name) LIKE $2::text ESCAPE '\'
   OR lower(k.tag) LIKE $2::text ESCAPE '\'
GROUP BY k.id
ORDER BY (lower(k.tag) = $3::text) DESC, k.reputation DESC, k.level DESC
LIMIT 20
`

type SearchKingdomsParams struct {
	CourtID string
	Pattern string
	Exact   string
}

type SearchKingdomsRow struct {
	ID         uuid.UUID
	Name       string
	Tag        string
	Level      int32
	Reputation int64
	JoinPolicy string
	Members    int32
	CourtLevel int32
	KingName   string
}

// Kingdoms by name or tag. The pattern arrives escaped and lower-cased from the
// service ('%', '_' and '\' are literal in a name), and an exact tag reads first:
// someone typing LION wants [LION], not every kingdom with a lion in its name.
func (q *Queries) SearchKingdoms(ctx context.Context, arg SearchKingdomsParams) ([]SearchKingdomsRow, error) {
	rows, err := q.db.Query(ctx, searchKingdoms, arg.CourtID, arg.Pattern, arg.Exact)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchKingdomsRow{}
	for rows.Next() {
		var i SearchKingdomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tag,
			&i.Level,
			&i.Reputation,
			&i.JoinPolicy,
			&i.Members,
			&i.CourtLevel,
			&i.KingName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setJoinPolicy = `-- name: SetJoinPolicy :exec
UPDATE app.kingdoms SET join_policy = $2 WHERE id = $1
`

type SetJoinPolicyParams struct {
	ID         uuid.UUID
	JoinPolicy string
}

func (q *Queries) SetJoinPolicy(ctx context.Context, arg SetJoinPolicyParams) error {
	_, err := q.db.Exec(ctx, setJoinPolicy, arg.ID, arg.JoinPolicy)
	return err
}

const setKingdomRole = `-- name: SetKingdomRole :one
UPDATE app.players SET kingdom_role = $2 WHERE id = $1 AND kingdom_id = $3 RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at
`

type SetKingdomRoleParams struct {
	ID          uuid.UUID
	KingdomRole string
	KingdomID   *uuid.UUID
}

func (q *Queries) SetKingdomRole(ctx context.Context, arg SetKingdomRoleParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, setKingdomRole, arg.ID, arg.KingdomRole, arg.KingdomID)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
	)
	return i, err
}

const setLeader = `-- name: SetLeader :exec
UPDATE app.kingdoms SET leader_id = $2 WHERE id = $1
`

type SetLeaderParams struct {
	ID       uuid.UUID
	LeaderID *uuid.UUID
}

func (q *Queries) SetLeader(ctx context.Context, arg SetLeaderParams) error {
	_, err := q.db.Exec(ctx, setLeader, arg.ID, arg.LeaderID)
	return err
}

const setPlayerKingdom = `-- name: SetPlayerKingdom :one
UPDATE app.players
SET kingdom_id = $2, kingdom_role = $3, kingdom_joined_at = $4
WHERE id = $1 AND kingdom_id IS NULL
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at
`

type SetPlayerKingdomParams struct {
	ID              uuid.UUID
	KingdomID       *uuid.UUID
	KingdomRole     string
	KingdomJoinedAt *time.Time
}

// Seats a player. The kingdom_id IS NULL guard is the last word on "one
// kingdom at a time": a king answering a request seats someone other than
// himself, and that someone may have joined elsewhere a moment before. Zero
// rows means they had.
func (q *Queries) SetPlayerKingdom(ctx context.Context, arg SetPlayerKingdomParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, setPlayerKingdom,
		arg.ID,
		arg.KingdomID,
		arg.KingdomRole,
		arg.KingdomJoinedAt,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
	)
	return i, err
}

const spendFavour = `-- name: SpendFavour :one
UPDATE app.players
SET kingdom_favour = kingdom_favour - $1, action_seq = $2
WHERE id = $3 AND kingdom_favour >= $1
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at
`

type SpendFavourParams struct {
	Cost      int64
	ActionSeq int64
	ID        uuid.UUID
}

// Spends favour. Zero rows means they could not afford it, so the check and the
// deduction are the same statement and a double-tap cannot overdraw.
func (q *Queries) SpendFavour(ctx context.Context, arg SpendFavourParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, spendFavour, arg.Cost, arg.ActionSeq, arg.ID)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
	)
	return i, err
}

const spendKingdomTreasury = `-- name: SpendKingdomTreasury :one
UPDATE app.kingdoms SET treasury = treasury - $2 WHERE id = $1 AND treasury >= $2 RETURNING id, name, tag, leader_id, level, xp, treasury, reputation, created_at, join_policy
`

type SpendKingdomTreasuryParams struct {
	ID       uuid.UUID
	Treasury int64
}

func (q *Queries) SpendKingdomTreasury(ctx context.Context, arg SpendKingdomTreasuryParams) (AppKingdom, error) {
	row := q.db.QueryRow(ctx, spendKingdomTreasury, arg.ID, arg.Treasury)
	var i AppKingdom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.LeaderID,
		&i.Level,
		&i.Xp,
		&i.Treasury,
		&i.Reputation,
		&i.CreatedAt,
		&i.JoinPolicy,
	)
	return i, err
}

const topKingdoms = `-- name: TopKingdoms :many
SELECT k.id, k.name, k.tag, k.level, k.xp, k.treasury, k.reputation, k.join_policy,
       (SELECT count(*) FROM app.players p WHERE p.kingdom_id = k.id)::int AS members,
       coalesce((SELECT u.level FROM app.kingdom_upgrades u
                 WHERE u.kingdom_id = k.id AND u.upgrade_id = $1), 0)::int AS court_level
FROM app.kingdoms k
WHERE EXISTS (SELECT 1 FROM app.players p WHERE p.kingdom_id = k.id)
ORDER BY k.reputation DESC, k.xp DESC
LIMIT $2
`

type TopKingdomsParams struct {
	CourtID string
	MaxRows int32
}

type TopKingdomsRow struct {
	ID         uuid.UUID
	Name       string
	Tag        string
	Level      int32
	Xp         int64
	Treasury   int64
	Reputation int64
	JoinPolicy string
	Members    int32
	CourtLevel int32
}

// The table. A kingdom whose last lord has gone is not a kingdom, so it is not
// ranked, however much renown it left behind.
func (q *Queries) TopKingdoms(ctx context.Context, arg TopKingdomsParams) ([]TopKingdomsRow, error) {
	rows, err := q.db.Query(ctx, topKingdoms, arg.CourtID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopKingdomsRow{}
	for rows.Next() {
		var i TopKingdomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tag,
			&i.Level,
			&i.Xp,
			&i.Treasury,
			&i.Reputation,
			&i.JoinPolicy,
			&i.Members,
			&i.CourtLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
