// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kpi.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listKPIDays = `-- name: ListKPIDays :many
SELECT day, dau, new_lords, payers, purchases, gross_cents, refund_cents, diamonds_earned, diamonds_bought, diamonds_spent, computed_at FROM app.daily_kpi WHERE day >= $1::date ORDER BY day
`

// The rolled-up days of a window, oldest first.
func (q *Queries) ListKPIDays(ctx context.Context, since pgtype.Date) ([]AppDailyKpi, error) {
	rows, err := q.db.Query(ctx, listKPIDays, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppDailyKpi{}
	for rows.Next() {
		var i AppDailyKpi
		if err := rows.Scan(
			&i.Day,
			&i.Dau,
			&i.NewLords,
			&i.Payers,
			&i.Purchases,
			&i.GrossCents,
			&i.RefundCents,
			&i.DiamondsEarned,
			&i.DiamondsBought,
			&i.DiamondsSpent,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupKPIDay = `-- name: RollupKPIDay :exec

INSERT INTO app.daily_kpi (day, dau, new_lords, payers, purchases, gross_cents, refund_cents,
                           diamonds_earned, diamonds_bought, diamonds_spent, computed_at)
SELECT d.day,
       (SELECT count(*) FROM app.player_days pd WHERE pd.day = d.day)::int,
       ((SELECT count(*) FROM app.players p
         WHERE NOT p.is_bot AND p.created_at >= d.lo AND p.created_at < d.hi)
        + (SELECT count(*) FROM app.deleted_accounts x
           WHERE x.joined_at >= d.lo AND x.joined_at < d.hi))::int,
       (SELECT count(DISTINCT t.player_id) FROM app.iap_transactions t
        WHERE t.environment = 'Production' AND t.purchased_at >= d.lo AND t.purchased_at < d.hi)::int,
       (SELECT count(*) FROM app.iap_transactions t
        WHERE t.environment = 'Production' AND t.purchased_at >= d.lo AND t.purchased_at < d.hi)::int,
       (SELECT coalesce(sum(t.usd_cents), 0) FROM app.iap_transactions t
        WHERE t.environment = 'Production' AND t.purchased_at >= d.lo AND t.purchased_at < d.hi)::bigint,
       (SELECT coalesce(sum(t.usd_cents), 0) FROM app.iap_transactions t
        WHERE t.environment = 'Production' AND t.state = 'refunded'
          AND t.refunded_at >= d.lo AND t.refunded_at < d.hi)::bigint,
       (SELECT coalesce(sum(l.gross), 0) FROM app.diamond_ledger l
        WHERE l.class = 'earned' AND l.created_at >= d.lo AND l.created_at < d.hi)::bigint,
       (SELECT coalesce(sum(l.gross), 0) FROM app.diamond_ledger l
        WHERE l.class = 'purchased' AND l.created_at >= d.lo AND l.created_at < d.hi)::bigint,
       (SELECT coalesce(-sum(l.gross), 0) FROM app.diamond_ledger l
        WHERE l.class = 'spent' AND l.created_at >= d.lo AND l.created_at < d.hi)::bigint,
       now()
FROM (SELECT $1::date AS day,
             ($1::date::timestamp AT TIME ZONE 'UTC') AS lo,
             (($1::date + 1)::timestamp AT TIME ZONE 'UTC') AS hi) d
ON CONFLICT (day) DO UPDATE
SET dau = EXCLUDED.dau, new_lords = EXCLUDED.new_lords, payers = EXCLUDED.payers,
    purchases = EXCLUDED.purchases, gross_cents = EXCLUDED.gross_cents, refund_cents = EXCLUDED.refund_cents,
    diamonds_earned = EXCLUDED.diamonds_earned, diamonds_bought = EXCLUDED.diamonds_bought,
    diamonds_spent = EXCLUDED.diamonds_spent, computed_at = EXCLUDED.computed_at
`

// The daily KPI rollup (migration 00039, the kpi_rollup job).
// One UTC day's figures, written again if they were written before. The day's
// bounds are UTC midnights whatever the session's time zone.
func (q *Queries) RollupKPIDay(ctx context.Context, day pgtype.Date) error {
	_, err := q.db.Exec(ctx, rollupKPIDay, day)
	return err
}
