// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboards.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const clearBoard = `-- name: ClearBoard :exec
DELETE FROM app.leaderboard_entries WHERE board = $1
`

// Rebuilds one board. Called inside a transaction with the delete below, so
// readers never see a half-filled board.
func (q *Queries) ClearBoard(ctx context.Context, board string) error {
	_, err := q.db.Exec(ctx, clearBoard, board)
	return err
}

const fillBoardLevel = `-- name: FillBoardLevel :exec
INSERT INTO app.leaderboard_entries (board, rank, player_id, value)
SELECT 'level', row_number() OVER (ORDER BY level DESC, xp DESC, id), id, level
FROM app.players
WHERE state = 'active' AND NOT is_bot
LIMIT $1
`

func (q *Queries) FillBoardLevel(ctx context.Context, lim int32) error {
	_, err := q.db.Exec(ctx, fillBoardLevel, lim)
	return err
}

const fillBoardMight = `-- name: FillBoardMight :exec
INSERT INTO app.leaderboard_entries (board, rank, player_id, value)
SELECT 'might', row_number() OVER (ORDER BY might DESC, id), id, might
FROM app.players
WHERE state = 'active' AND NOT is_bot AND might > 0
LIMIT $1
`

// The ranking itself, done in the database rather than in Go: sorting every
// player in application memory is the thing this table exists to avoid.
// Bots are excluded — a board topped by the filler opponents would be a lie.
func (q *Queries) FillBoardMight(ctx context.Context, lim int32) error {
	_, err := q.db.Exec(ctx, fillBoardMight, lim)
	return err
}

const fillBoardWealth = `-- name: FillBoardWealth :exec
INSERT INTO app.leaderboard_entries (board, rank, player_id, value)
SELECT 'wealth', row_number() OVER (ORDER BY (gold + treasury_gold) DESC, id),
       id, gold + treasury_gold
FROM app.players
WHERE state = 'active' AND NOT is_bot
LIMIT $1
`

// Net worth: what they are carrying plus what they have banked. Treasury alone
// would reward hoarding and purse alone would reward being about to be robbed.
func (q *Queries) FillBoardWealth(ctx context.Context, lim int32) error {
	_, err := q.db.Exec(ctx, fillBoardWealth, lim)
	return err
}

const myRank = `-- name: MyRank :one
SELECT rank, value FROM app.leaderboard_entries
WHERE board = $1 AND player_id = $2
`

type MyRankParams struct {
	Board    string
	PlayerID uuid.UUID
}

type MyRankRow struct {
	Rank  int32
	Value int64
}

func (q *Queries) MyRank(ctx context.Context, arg MyRankParams) (MyRankRow, error) {
	row := q.db.QueryRow(ctx, myRank, arg.Board, arg.PlayerID)
	var i MyRankRow
	err := row.Scan(&i.Rank, &i.Value)
	return i, err
}

const readBoard = `-- name: ReadBoard :many
SELECT e.rank, e.value, p.display_name, p.avatar, p.level, p.kingdom_id
FROM app.leaderboard_entries e
JOIN app.players p ON p.id = e.player_id
WHERE e.board = $1
ORDER BY e.rank
LIMIT $2
`

type ReadBoardParams struct {
	Board string
	Lim   int32
}

type ReadBoardRow struct {
	Rank        int32
	Value       int64
	DisplayName string
	Avatar      string
	Level       int32
	KingdomID   *uuid.UUID
}

func (q *Queries) ReadBoard(ctx context.Context, arg ReadBoardParams) ([]ReadBoardRow, error) {
	rows, err := q.db.Query(ctx, readBoard, arg.Board, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadBoardRow{}
	for rows.Next() {
		var i ReadBoardRow
		if err := rows.Scan(
			&i.Rank,
			&i.Value,
			&i.DisplayName,
			&i.Avatar,
			&i.Level,
			&i.KingdomID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMight = `-- name: SetMight :exec
UPDATE app.players SET might = $2 WHERE id = $1
`

type SetMightParams struct {
	ID    uuid.UUID
	Might int64
}

func (q *Queries) SetMight(ctx context.Context, arg SetMightParams) error {
	_, err := q.db.Exec(ctx, setMight, arg.ID, arg.Might)
	return err
}
