// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: liveops.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addEventPoints = `-- name: AddEventPoints :exec
INSERT INTO app.player_event (player_id, event_id, points_milli, day, day_milli, points_at)
VALUES ($1, $2, LEAST($3::bigint, $4::bigint),
        $5::smallint, LEAST($3::bigint, $4::bigint), $6)
ON CONFLICT (player_id, event_id) DO UPDATE
SET points_milli = app.player_event.points_milli + CASE
        WHEN app.player_event.day = EXCLUDED.day
        THEN GREATEST(0, LEAST(app.player_event.day_milli + $3::bigint, $4::bigint) - app.player_event.day_milli)
        ELSE LEAST($3::bigint, $4::bigint) END,
    day_milli = CASE
        WHEN app.player_event.day = EXCLUDED.day
        THEN GREATEST(app.player_event.day_milli, LEAST(app.player_event.day_milli + $3::bigint, $4::bigint))
        ELSE LEAST($3::bigint, $4::bigint) END,
    day = EXCLUDED.day,
    points_at = CASE
        WHEN app.player_event.day = EXCLUDED.day AND app.player_event.day_milli >= $4::bigint
        THEN app.player_event.points_at ELSE EXCLUDED.points_at END
`

type AddEventPointsParams struct {
	PlayerID uuid.UUID
	EventID  int64
	Add      int64
	Cap      int64
	Day      int16
	Now      time.Time
}

// Points for one action, under the festival day's cap. Only what the day still
// has room for is added; a cap lowered mid-day never takes points back.
func (q *Queries) AddEventPoints(ctx context.Context, arg AddEventPointsParams) error {
	_, err := q.db.Exec(ctx, addEventPoints,
		arg.PlayerID,
		arg.EventID,
		arg.Add,
		arg.Cap,
		arg.Day,
		arg.Now,
	)
	return err
}

const addSeasonPoints = `-- name: AddSeasonPoints :exec

INSERT INTO app.player_season (player_id, season, points_milli, day, day_milli, points_at, might_start)
VALUES ($1, $2, LEAST($3::bigint, $4::bigint),
        $5::smallint, LEAST($3::bigint, $4::bigint), $6,
        $7::bigint)
ON CONFLICT (player_id, season) DO UPDATE
SET points_milli = app.player_season.points_milli + CASE
        WHEN app.player_season.day = EXCLUDED.day
        THEN GREATEST(0, LEAST(app.player_season.day_milli + $3::bigint, $4::bigint) - app.player_season.day_milli)
        ELSE LEAST($3::bigint, $4::bigint) END,
    day_milli = CASE
        WHEN app.player_season.day = EXCLUDED.day
        THEN GREATEST(app.player_season.day_milli, LEAST(app.player_season.day_milli + $3::bigint, $4::bigint))
        ELSE LEAST($3::bigint, $4::bigint) END,
    day = EXCLUDED.day,
    points_at = CASE
        WHEN app.player_season.day = EXCLUDED.day AND app.player_season.day_milli >= $4::bigint
        THEN app.player_season.points_at ELSE EXCLUDED.points_at END
`

type AddSeasonPointsParams struct {
	PlayerID uuid.UUID
	Season   int32
	Add      int64
	Cap      int64
	Day      int16
	Now      time.Time
	Might    int64
}

// ---------------------------------------------------------------------------
// The season
// ---------------------------------------------------------------------------
// Charter points for one action, under the season day's cap (as AddEventPoints).
// The row's might_start is the lord's Might when the row is first written,
// and never moves after.
func (q *Queries) AddSeasonPoints(ctx context.Context, arg AddSeasonPointsParams) error {
	_, err := q.db.Exec(ctx, addSeasonPoints,
		arg.PlayerID,
		arg.Season,
		arg.Add,
		arg.Cap,
		arg.Day,
		arg.Now,
		arg.Might,
	)
	return err
}

const backfillLifeDeeds = `-- name: BackfillLifeDeeds :execrows
INSERT INTO app.player_deeds (player_id, scope, period, deed, value)
SELECT player_id, 'life', 0, deed, value FROM (
    SELECT attacker_id AS player_id, 'raids' AS deed, count(*)::bigint AS value
      FROM app.battles GROUP BY attacker_id
    UNION ALL
    SELECT attacker_id, 'raid_wins', count(*)::bigint FROM app.battles WHERE attacker_won GROUP BY attacker_id
    UNION ALL
    SELECT attacker_id, 'gold_stolen', sum(gold_stolen)::bigint FROM app.battles
      WHERE attacker_won GROUP BY attacker_id HAVING sum(gold_stolen) > 0
    UNION ALL
    SELECT defender_id, 'defenses_held', count(*)::bigint FROM app.battles WHERE NOT attacker_won GROUP BY defender_id
    UNION ALL
    SELECT player_id, 'collects', sum(collects)::bigint FROM app.player_job_progress
      GROUP BY player_id HAVING sum(collects) > 0
    UNION ALL
    SELECT player_id, 'upgrades', sum(level)::bigint FROM app.player_upgrades
      GROUP BY player_id HAVING sum(level) > 0
    UNION ALL
    SELECT player_id, 'holdings', sum(level)::bigint FROM app.player_holdings
      GROUP BY player_id HAVING sum(level) > 0
    UNION ALL
    SELECT player_id, 'buys', count(*)::bigint FROM app.gold_ledger WHERE reason = 'shop_buy' GROUP BY player_id
    UNION ALL
    SELECT player_id, 'shop_gold', sum(-delta)::bigint FROM app.gold_ledger
      WHERE reason = 'shop_buy' AND delta < 0 GROUP BY player_id
    UNION ALL
    SELECT player_id, 'sells', count(*)::bigint FROM app.gold_ledger WHERE reason = 'item_sell' GROUP BY player_id
    UNION ALL
    SELECT player_id, 'recruits', count(*)::bigint FROM app.gold_ledger WHERE reason = 'recruit' GROUP BY player_id
    UNION ALL
    SELECT player_id, 'rerolls', count(*)::bigint FROM app.gold_ledger WHERE reason = 'reroll' GROUP BY player_id
    UNION ALL
    SELECT player_id, 'donated_gold', sum(-delta)::bigint FROM app.gold_ledger
      WHERE reason = 'kingdom_donate' AND delta < 0 GROUP BY player_id
    UNION ALL
    SELECT player_id, 'mail_claims', count(*)::bigint FROM app.mail WHERE claimed_at IS NOT NULL GROUP BY player_id
    UNION ALL
    SELECT id, 'daily_claims', (calendar_cycle * 28 + calendar_pos)::bigint FROM app.players
      WHERE NOT is_bot AND calendar_cycle * 28 + calendar_pos > 0
    UNION ALL
    SELECT id, 'carts_opened', carts_opened::bigint FROM app.players WHERE NOT is_bot AND carts_opened > 0
) derived
WHERE value > 0 AND EXISTS (SELECT 1 FROM app.players p WHERE p.id = derived.player_id AND NOT p.is_bot)
ON CONFLICT (player_id, scope, period, deed)
DO UPDATE SET value = GREATEST(app.player_deeds.value, EXCLUDED.value)
`

// The lifetime counters, raised to what the records kept before the counters
// began (Wave 0) show. GREATEST, never a sum: a record since then is already
// counted, and the backfill may run again safely. (Energy is priced by the
// balance's jobs, so it is summed in Go: JobCollects, RaiseLifeDeeds.)
func (q *Queries) BackfillLifeDeeds(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, backfillLifeDeeds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimAchievement = `-- name: ClaimAchievement :one
INSERT INTO app.player_achievements (player_id, achievement, claimed)
VALUES ($1, $2, $3::smallint)
ON CONFLICT (player_id, achievement) DO UPDATE
SET claimed = EXCLUDED.claimed, claimed_at = now()
WHERE app.player_achievements.claimed = $4::smallint
RETURNING claimed
`

type ClaimAchievementParams struct {
	PlayerID    uuid.UUID
	Achievement string
	ToTier      int16
	FromTier    int16
}

// Moves a deed's claimed tiers from what the caller read to what it pays.
func (q *Queries) ClaimAchievement(ctx context.Context, arg ClaimAchievementParams) (int16, error) {
	row := q.db.QueryRow(ctx, claimAchievement,
		arg.PlayerID,
		arg.Achievement,
		arg.ToTier,
		arg.FromTier,
	)
	var claimed int16
	err := row.Scan(&claimed)
	return claimed, err
}

const claimEventRewards = `-- name: ClaimEventRewards :one
UPDATE app.player_event
SET tasks = tasks | $1::int, milestones = milestones | $2::int
WHERE player_id = $3 AND event_id = $4
  AND tasks & $1::int = 0 AND milestones & $2::int = 0
RETURNING player_id, event_id, points_milli, day, day_milli, points_at, tasks, milestones
`

type ClaimEventRewardsParams struct {
	Tasks      int32
	Milestones int32
	PlayerID   uuid.UUID
	EventID    int64
}

// Setting the bits is the claim; zero rows means one was already set.
func (q *Queries) ClaimEventRewards(ctx context.Context, arg ClaimEventRewardsParams) (AppPlayerEvent, error) {
	row := q.db.QueryRow(ctx, claimEventRewards,
		arg.Tasks,
		arg.Milestones,
		arg.PlayerID,
		arg.EventID,
	)
	var i AppPlayerEvent
	err := row.Scan(
		&i.PlayerID,
		&i.EventID,
		&i.PointsMilli,
		&i.Day,
		&i.DayMilli,
		&i.PointsAt,
		&i.Tasks,
		&i.Milestones,
	)
	return i, err
}

const claimSeasonTiers = `-- name: ClaimSeasonTiers :one
UPDATE app.player_season
SET free_claimed = free_claimed | $1::bigint, royal_claimed = royal_claimed | $2::bigint
WHERE player_id = $3 AND season = $4
  AND free_claimed & $1::bigint = 0 AND royal_claimed & $2::bigint = 0
RETURNING player_id, season, points_milli, day, day_milli, points_at, free_claimed, royal_claimed, royal_at, royal_ref, might_start
`

type ClaimSeasonTiersParams struct {
	Free     int64
	Royal    int64
	PlayerID uuid.UUID
	Season   int32
}

// Setting the bits is the claim; zero rows means one was already set.
func (q *Queries) ClaimSeasonTiers(ctx context.Context, arg ClaimSeasonTiersParams) (AppPlayerSeason, error) {
	row := q.db.QueryRow(ctx, claimSeasonTiers,
		arg.Free,
		arg.Royal,
		arg.PlayerID,
		arg.Season,
	)
	var i AppPlayerSeason
	err := row.Scan(
		&i.PlayerID,
		&i.Season,
		&i.PointsMilli,
		&i.Day,
		&i.DayMilli,
		&i.PointsAt,
		&i.FreeClaimed,
		&i.RoyalClaimed,
		&i.RoyalAt,
		&i.RoyalRef,
		&i.MightStart,
	)
	return i, err
}

const clearHourly = `-- name: ClearHourly :execrows
DELETE FROM admin.hourly_events WHERE hour = $1
`

// Gives a future hour back to the roll.
func (q *Queries) ClearHourly(ctx context.Context, hour int64) (int64, error) {
	result, err := q.db.Exec(ctx, clearHourly, hour)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closePeriod = `-- name: ClosePeriod :exec
INSERT INTO admin.period_closes (what, period, lords) VALUES ($1, $2, $3)
ON CONFLICT (what, period) DO NOTHING
`

type ClosePeriodParams struct {
	What   string
	Period int64
	Lords  int32
}

func (q *Queries) ClosePeriod(ctx context.Context, arg ClosePeriodParams) error {
	_, err := q.db.Exec(ctx, closePeriod, arg.What, arg.Period, arg.Lords)
	return err
}

const countCollection = `-- name: CountCollection :one
SELECT count(*)::int FROM app.player_collection WHERE player_id = $1
`

func (q *Queries) CountCollection(ctx context.Context, playerID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countCollection, playerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countEventLords = `-- name: CountEventLords :one
SELECT count(*)::int FROM app.player_event WHERE event_id = $1 AND points_milli > 0
`

func (q *Queries) CountEventLords(ctx context.Context, eventID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countEventLords, eventID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countHourlyUses = `-- name: CountHourlyUses :many
SELECT hour, count(*)::int AS lords FROM app.player_hourly
WHERE hour BETWEEN $1::bigint AND $2::bigint
GROUP BY hour
`

type CountHourlyUsesParams struct {
	FromHour int64
	ToHour   int64
}

type CountHourlyUsesRow struct {
	Hour  int64
	Lords int32
}

// How many lords used an hour's event: the panel's schedule.
func (q *Queries) CountHourlyUses(ctx context.Context, arg CountHourlyUsesParams) ([]CountHourlyUsesRow, error) {
	rows, err := q.db.Query(ctx, countHourlyUses, arg.FromHour, arg.ToHour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountHourlyUsesRow{}
	for rows.Next() {
		var i CountHourlyUsesRow
		if err := rows.Scan(&i.Hour, &i.Lords); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMastered = `-- name: CountMastered :one
SELECT count(*)::int FROM app.player_job_progress
WHERE player_id = $1 AND collects >= $2::bigint
`

type CountMasteredParams struct {
	PlayerID uuid.UUID
	Collects int64
}

// Jobs a lord has worked to their last mastery milestone.
func (q *Queries) CountMastered(ctx context.Context, arg CountMasteredParams) (int32, error) {
	row := q.db.QueryRow(ctx, countMastered, arg.PlayerID, arg.Collects)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countOverlappingEvents = `-- name: CountOverlappingEvents :one
SELECT count(*)::int FROM admin.live_events
WHERE revoked_at IS NULL AND starts_at < $1 AND ends_at > $2
`

type CountOverlappingEventsParams struct {
	EndsAt   time.Time
	StartsAt time.Time
}

// Festivals that would share any moment with a window.
func (q *Queries) CountOverlappingEvents(ctx context.Context, arg CountOverlappingEventsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countOverlappingEvents, arg.EndsAt, arg.StartsAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const currentEvents = `-- name: CurrentEvents :many
SELECT id, template_id, starts_at, ends_at, frozen, note, created_by, created_at, revoked_at, revoked_by, settled_at FROM admin.live_events
WHERE revoked_at IS NULL AND ends_at > $1 AND starts_at < $2
ORDER BY starts_at
`

type CurrentEventsParams struct {
	Now   time.Time
	Until time.Time
}

// What is running or announced: the poll's read.
func (q *Queries) CurrentEvents(ctx context.Context, arg CurrentEventsParams) ([]AdminLiveEvent, error) {
	rows, err := q.db.Query(ctx, currentEvents, arg.Now, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminLiveEvent{}
	for rows.Next() {
		var i AdminLiveEvent
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Frozen,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deedStandings = `-- name: DeedStandings :many
SELECT player_id, value, place FROM (
    SELECT d.player_id, d.value, rank() OVER (ORDER BY d.value DESC)::int AS place
    FROM app.player_deeds d
    JOIN app.players p ON p.id = d.player_id
    WHERE d.scope = $1 AND d.period = $2 AND d.deed = $3
      AND d.value > 0 AND p.state = 'active' AND NOT p.is_bot
) ranked
WHERE place <= $4::int
ORDER BY place, player_id
`

type DeedStandingsParams struct {
	Scope  string
	Period int64
	Deed   string
	Lim    int32
}

type DeedStandingsRow struct {
	PlayerID uuid.UUID
	Value    int64
	Place    int32
}

// A closed period's places on a deed's board, as far as its rewards reach.
func (q *Queries) DeedStandings(ctx context.Context, arg DeedStandingsParams) ([]DeedStandingsRow, error) {
	rows, err := q.db.Query(ctx, deedStandings,
		arg.Scope,
		arg.Period,
		arg.Deed,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeedStandingsRow{}
	for rows.Next() {
		var i DeedStandingsRow
		if err := rows.Scan(&i.PlayerID, &i.Value, &i.Place); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensurePlayerEvent = `-- name: EnsurePlayerEvent :one
INSERT INTO app.player_event (player_id, event_id) VALUES ($1, $2)
ON CONFLICT (player_id, event_id) DO UPDATE SET tasks = app.player_event.tasks
RETURNING player_id, event_id, points_milli, day, day_milli, points_at, tasks, milestones
`

type EnsurePlayerEventParams struct {
	PlayerID uuid.UUID
	EventID  int64
}

func (q *Queries) EnsurePlayerEvent(ctx context.Context, arg EnsurePlayerEventParams) (AppPlayerEvent, error) {
	row := q.db.QueryRow(ctx, ensurePlayerEvent, arg.PlayerID, arg.EventID)
	var i AppPlayerEvent
	err := row.Scan(
		&i.PlayerID,
		&i.EventID,
		&i.PointsMilli,
		&i.Day,
		&i.DayMilli,
		&i.PointsAt,
		&i.Tasks,
		&i.Milestones,
	)
	return i, err
}

const ensurePlayerSeason = `-- name: EnsurePlayerSeason :one
INSERT INTO app.player_season (player_id, season, might_start)
VALUES ($1, $2, $3::bigint)
ON CONFLICT (player_id, season) DO UPDATE SET free_claimed = app.player_season.free_claimed
RETURNING player_id, season, points_milli, day, day_milli, points_at, free_claimed, royal_claimed, royal_at, royal_ref, might_start
`

type EnsurePlayerSeasonParams struct {
	PlayerID uuid.UUID
	Season   int32
	Might    int64
}

func (q *Queries) EnsurePlayerSeason(ctx context.Context, arg EnsurePlayerSeasonParams) (AppPlayerSeason, error) {
	row := q.db.QueryRow(ctx, ensurePlayerSeason, arg.PlayerID, arg.Season, arg.Might)
	var i AppPlayerSeason
	err := row.Scan(
		&i.PlayerID,
		&i.Season,
		&i.PointsMilli,
		&i.Day,
		&i.DayMilli,
		&i.PointsAt,
		&i.FreeClaimed,
		&i.RoyalClaimed,
		&i.RoyalAt,
		&i.RoyalRef,
		&i.MightStart,
	)
	return i, err
}

const eventBoard = `-- name: EventBoard :many
SELECT pe.player_id, pe.points_milli, p.display_name, p.avatar, p.level,
       p.cos_frame, p.cos_title, p.cos_color, p.cos_crest, p.vip_points
FROM app.player_event pe
JOIN app.players p ON p.id = pe.player_id
WHERE pe.event_id = $1 AND pe.points_milli > 0 AND p.state = 'active' AND NOT p.is_bot
ORDER BY pe.points_milli DESC, pe.points_at, pe.player_id
LIMIT $2
`

type EventBoardParams struct {
	EventID int64
	Lim     int32
}

type EventBoardRow struct {
	PlayerID    uuid.UUID
	PointsMilli int64
	DisplayName string
	Avatar      string
	Level       int32
	CosFrame    *string
	CosTitle    *string
	CosColor    *string
	CosCrest    *string
	VipPoints   int64
}

// A festival's board: first by points, then by who reached them first.
func (q *Queries) EventBoard(ctx context.Context, arg EventBoardParams) ([]EventBoardRow, error) {
	rows, err := q.db.Query(ctx, eventBoard, arg.EventID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventBoardRow{}
	for rows.Next() {
		var i EventBoardRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.PointsMilli,
			&i.DisplayName,
			&i.Avatar,
			&i.Level,
			&i.CosFrame,
			&i.CosTitle,
			&i.CosColor,
			&i.CosCrest,
			&i.VipPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventDeeds = `-- name: EventDeeds :many
SELECT player_id, deed, value FROM app.player_deeds WHERE scope = 'event' AND period = $1
`

type EventDeedsRow struct {
	PlayerID uuid.UUID
	Deed     string
	Value    int64
}

// Every lord's deeds in a festival, for its close.
func (q *Queries) EventDeeds(ctx context.Context, eventID int64) ([]EventDeedsRow, error) {
	rows, err := q.db.Query(ctx, eventDeeds, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventDeedsRow{}
	for rows.Next() {
		var i EventDeedsRow
		if err := rows.Scan(&i.PlayerID, &i.Deed, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventPlace = `-- name: EventPlace :one
SELECT (count(*) + 1)::int FROM app.player_event pe
JOIN app.players p ON p.id = pe.player_id
WHERE pe.event_id = $1 AND p.state = 'active' AND NOT p.is_bot AND pe.points_milli > 0
  AND (pe.points_milli > $2::bigint
       OR (pe.points_milli = $2::bigint AND pe.points_at < $3::timestamptz))
`

type EventPlaceParams struct {
	EventID     int64
	PointsMilli int64
	PointsAt    time.Time
}

// A lord's place: one more than those ahead of them.
func (q *Queries) EventPlace(ctx context.Context, arg EventPlaceParams) (int32, error) {
	row := q.db.QueryRow(ctx, eventPlace, arg.EventID, arg.PointsMilli, arg.PointsAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const eventStandings = `-- name: EventStandings :many
SELECT pe.player_id, pe.event_id, pe.points_milli, pe.day, pe.day_milli, pe.points_at, pe.tasks, pe.milestones, p.is_bot, p.state
FROM app.player_event pe
JOIN app.players p ON p.id = pe.player_id
WHERE pe.event_id = $1
ORDER BY pe.points_milli DESC, pe.points_at, pe.player_id
`

type EventStandingsRow struct {
	PlayerID    uuid.UUID
	EventID     int64
	PointsMilli int64
	Day         int16
	DayMilli    int64
	PointsAt    time.Time
	Tasks       int32
	Milestones  int32
	IsBot       bool
	State       string
}

// Everyone in a closing festival, in board order: the close pays places and
// sends what each left unclaimed.
func (q *Queries) EventStandings(ctx context.Context, eventID int64) ([]EventStandingsRow, error) {
	rows, err := q.db.Query(ctx, eventStandings, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventStandingsRow{}
	for rows.Next() {
		var i EventStandingsRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.EventID,
			&i.PointsMilli,
			&i.Day,
			&i.DayMilli,
			&i.PointsAt,
			&i.Tasks,
			&i.Milestones,
			&i.IsBot,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsToSettle = `-- name: EventsToSettle :many
SELECT id, template_id, starts_at, ends_at, frozen, note, created_by, created_at, revoked_at, revoked_by, settled_at FROM admin.live_events
WHERE revoked_at IS NULL AND settled_at IS NULL AND ends_at <= $1
ORDER BY ends_at
`

// Festivals over and not yet closed.
func (q *Queries) EventsToSettle(ctx context.Context, now time.Time) ([]AdminLiveEvent, error) {
	rows, err := q.db.Query(ctx, eventsToSettle, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminLiveEvent{}
	for rows.Next() {
		var i AdminLiveEvent
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Frozen,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fillDeedBoard = `-- name: FillDeedBoard :exec

INSERT INTO app.leaderboard_entries (board, rank, place, player_id, value)
SELECT $1::text, row_number() OVER w, rank() OVER (ORDER BY d.value DESC), d.player_id, d.value
FROM app.player_deeds d
JOIN app.players p ON p.id = d.player_id
WHERE d.scope = $2 AND d.period = $3 AND d.deed = $4
  AND d.value > 0 AND p.state = 'active' AND NOT p.is_bot
WINDOW w AS (ORDER BY d.value DESC, d.player_id)
ORDER BY d.value DESC, d.player_id
LIMIT $5
`

type FillDeedBoardParams struct {
	Board  string
	Scope  string
	Period int64
	Deed   string
	Lim    int32
}

// ---------------------------------------------------------------------------
// Boards and their closes
// ---------------------------------------------------------------------------
// A board of one deed over one period (a week, a season): lords level with
// each other share a place, and the order among them is fixed by id.
func (q *Queries) FillDeedBoard(ctx context.Context, arg FillDeedBoardParams) error {
	_, err := q.db.Exec(ctx, fillDeedBoard,
		arg.Board,
		arg.Scope,
		arg.Period,
		arg.Deed,
		arg.Lim,
	)
	return err
}

const fillMightGainBoard = `-- name: FillMightGainBoard :exec
INSERT INTO app.leaderboard_entries (board, rank, place, player_id, value)
SELECT $1::text, row_number() OVER w, rank() OVER (ORDER BY p.might - ps.might_start DESC),
       ps.player_id, p.might - ps.might_start
FROM app.player_season ps
JOIN app.players p ON p.id = ps.player_id
WHERE ps.season = $2 AND ps.might_start IS NOT NULL AND p.might > ps.might_start
  AND p.state = 'active' AND NOT p.is_bot
WINDOW w AS (ORDER BY p.might - ps.might_start DESC, ps.player_id)
ORDER BY p.might - ps.might_start DESC, ps.player_id
LIMIT $3
`

type FillMightGainBoardParams struct {
	Board  string
	Season int32
	Lim    int32
}

// The Might a season's lords have gained since their first deed in it (the
// army's cached Might, as the Might board reads it); level lords share a place.
func (q *Queries) FillMightGainBoard(ctx context.Context, arg FillMightGainBoardParams) error {
	_, err := q.db.Exec(ctx, fillMightGainBoard, arg.Board, arg.Season, arg.Lim)
	return err
}

const fillRenownBoard = `-- name: FillRenownBoard :exec
INSERT INTO app.leaderboard_entries (board, rank, place, player_id, value)
SELECT $1::text, row_number() OVER w, row_number() OVER w, ps.player_id, ps.points_milli / 1000
FROM app.player_season ps
JOIN app.players p ON p.id = ps.player_id
WHERE ps.season = $2 AND ps.points_milli > 0 AND p.state = 'active' AND NOT p.is_bot
WINDOW w AS (ORDER BY ps.points_milli DESC, ps.points_at, ps.player_id)
ORDER BY ps.points_milli DESC, ps.points_at, ps.player_id
LIMIT $3
`

type FillRenownBoardParams struct {
	Board  string
	Season int32
	Lim    int32
}

// The season's renown, a place each: whoever reached their points first.
func (q *Queries) FillRenownBoard(ctx context.Context, arg FillRenownBoardParams) error {
	_, err := q.db.Exec(ctx, fillRenownBoard, arg.Board, arg.Season, arg.Lim)
	return err
}

const freezeHourly = `-- name: FreezeHourly :exec
INSERT INTO admin.hourly_events (hour, event_id, source)
VALUES ($1, $2, 'roll')
ON CONFLICT (hour) DO NOTHING
`

type FreezeHourlyParams struct {
	Hour    int64
	EventID string
}

// An hour's roll, written the first time it is made. A row already there (the
// panel's, or another server's roll) stands.
func (q *Queries) FreezeHourly(ctx context.Context, arg FreezeHourlyParams) error {
	_, err := q.db.Exec(ctx, freezeHourly, arg.Hour, arg.EventID)
	return err
}

const getHourlyUse = `-- name: GetHourlyUse :one
SELECT used FROM app.player_hourly WHERE player_id = $1 AND hour = $2
`

type GetHourlyUseParams struct {
	PlayerID uuid.UUID
	Hour     int64
}

func (q *Queries) GetHourlyUse(ctx context.Context, arg GetHourlyUseParams) (int16, error) {
	row := q.db.QueryRow(ctx, getHourlyUse, arg.PlayerID, arg.Hour)
	var used int16
	err := row.Scan(&used)
	return used, err
}

const getLiveEvent = `-- name: GetLiveEvent :one
SELECT id, template_id, starts_at, ends_at, frozen, note, created_by, created_at, revoked_at, revoked_by, settled_at FROM admin.live_events WHERE id = $1
`

func (q *Queries) GetLiveEvent(ctx context.Context, id int64) (AdminLiveEvent, error) {
	row := q.db.QueryRow(ctx, getLiveEvent, id)
	var i AdminLiveEvent
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Frozen,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.SettledAt,
	)
	return i, err
}

const getPlayerEvent = `-- name: GetPlayerEvent :one
SELECT player_id, event_id, points_milli, day, day_milli, points_at, tasks, milestones FROM app.player_event WHERE player_id = $1 AND event_id = $2
`

type GetPlayerEventParams struct {
	PlayerID uuid.UUID
	EventID  int64
}

func (q *Queries) GetPlayerEvent(ctx context.Context, arg GetPlayerEventParams) (AppPlayerEvent, error) {
	row := q.db.QueryRow(ctx, getPlayerEvent, arg.PlayerID, arg.EventID)
	var i AppPlayerEvent
	err := row.Scan(
		&i.PlayerID,
		&i.EventID,
		&i.PointsMilli,
		&i.Day,
		&i.DayMilli,
		&i.PointsAt,
		&i.Tasks,
		&i.Milestones,
	)
	return i, err
}

const getPlayerSeason = `-- name: GetPlayerSeason :one
SELECT player_id, season, points_milli, day, day_milli, points_at, free_claimed, royal_claimed, royal_at, royal_ref, might_start FROM app.player_season WHERE player_id = $1 AND season = $2
`

type GetPlayerSeasonParams struct {
	PlayerID uuid.UUID
	Season   int32
}

func (q *Queries) GetPlayerSeason(ctx context.Context, arg GetPlayerSeasonParams) (AppPlayerSeason, error) {
	row := q.db.QueryRow(ctx, getPlayerSeason, arg.PlayerID, arg.Season)
	var i AppPlayerSeason
	err := row.Scan(
		&i.PlayerID,
		&i.Season,
		&i.PointsMilli,
		&i.Day,
		&i.DayMilli,
		&i.PointsAt,
		&i.FreeClaimed,
		&i.RoyalClaimed,
		&i.RoyalAt,
		&i.RoyalRef,
		&i.MightStart,
	)
	return i, err
}

const insertLiveEvent = `-- name: InsertLiveEvent :one

INSERT INTO admin.live_events (template_id, starts_at, ends_at, frozen, note, created_by)
VALUES ($1, $2, $3, $4,
        $5, $6)
RETURNING id, template_id, starts_at, ends_at, frozen, note, created_by, created_at, revoked_at, revoked_by, settled_at
`

type InsertLiveEventParams struct {
	TemplateID string
	StartsAt   time.Time
	EndsAt     time.Time
	Frozen     []byte
	Note       string
	CreatedBy  string
}

// ---------------------------------------------------------------------------
// Festivals
// ---------------------------------------------------------------------------
func (q *Queries) InsertLiveEvent(ctx context.Context, arg InsertLiveEventParams) (AdminLiveEvent, error) {
	row := q.db.QueryRow(ctx, insertLiveEvent,
		arg.TemplateID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Frozen,
		arg.Note,
		arg.CreatedBy,
	)
	var i AdminLiveEvent
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Frozen,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.SettledAt,
	)
	return i, err
}

const jobCollects = `-- name: JobCollects :many
SELECT jp.player_id, jp.job_id, jp.collects
FROM app.player_job_progress jp
JOIN app.players p ON p.id = jp.player_id
WHERE NOT p.is_bot AND jp.collects > 0
`

// Every lord's collects per job, for the energy they spent (the job's cost is
// in the balance).
func (q *Queries) JobCollects(ctx context.Context) ([]AppPlayerJobProgress, error) {
	rows, err := q.db.Query(ctx, jobCollects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPlayerJobProgress{}
	for rows.Next() {
		var i AppPlayerJobProgress
		if err := rows.Scan(&i.PlayerID, &i.JobID, &i.Collects); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAchievementClaims = `-- name: ListAchievementClaims :many

SELECT achievement, claimed FROM app.player_achievements WHERE player_id = $1
`

type ListAchievementClaimsRow struct {
	Achievement string
	Claimed     int16
}

// ---------------------------------------------------------------------------
// The deeds (achievements)
// ---------------------------------------------------------------------------
func (q *Queries) ListAchievementClaims(ctx context.Context, playerID uuid.UUID) ([]ListAchievementClaimsRow, error) {
	rows, err := q.db.Query(ctx, listAchievementClaims, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAchievementClaimsRow{}
	for rows.Next() {
		var i ListAchievementClaimsRow
		if err := rows.Scan(&i.Achievement, &i.Claimed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHourlyEvents = `-- name: ListHourlyEvents :many


SELECT hour, event_id, source, set_by, set_at, note FROM admin.hourly_events
WHERE hour BETWEEN $1::bigint AND $2::bigint
ORDER BY hour
`

type ListHourlyEventsParams struct {
	FromHour int64
	ToHour   int64
}

// Live ops (migration 00042): the hourly event, the calendar's festivals, the
// season and its Royal Charter, the boards' closes and the deeds.
// ---------------------------------------------------------------------------
// The hourly event
// ---------------------------------------------------------------------------
// Every hour written down in a window: the rolled, the forced and the skipped.
func (q *Queries) ListHourlyEvents(ctx context.Context, arg ListHourlyEventsParams) ([]AdminHourlyEvent, error) {
	rows, err := q.db.Query(ctx, listHourlyEvents, arg.FromHour, arg.ToHour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminHourlyEvent{}
	for rows.Next() {
		var i AdminHourlyEvent
		if err := rows.Scan(
			&i.Hour,
			&i.EventID,
			&i.Source,
			&i.SetBy,
			&i.SetAt,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveEvents = `-- name: ListLiveEvents :many
SELECT e.id, e.template_id, e.starts_at, e.ends_at, e.frozen, e.note, e.created_by, e.created_at, e.revoked_at, e.revoked_by, e.settled_at,
       (SELECT count(*) FROM app.player_event pe WHERE pe.event_id = e.id)::int AS lords
FROM admin.live_events e
ORDER BY e.starts_at DESC
LIMIT $1
`

type ListLiveEventsRow struct {
	ID         int64
	TemplateID string
	StartsAt   time.Time
	EndsAt     time.Time
	Frozen     []byte
	Note       string
	CreatedBy  string
	CreatedAt  time.Time
	RevokedAt  *time.Time
	RevokedBy  *string
	SettledAt  *time.Time
	Lords      int32
}

func (q *Queries) ListLiveEvents(ctx context.Context, lim int32) ([]ListLiveEventsRow, error) {
	rows, err := q.db.Query(ctx, listLiveEvents, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveEventsRow{}
	for rows.Next() {
		var i ListLiveEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Frozen,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.SettledAt,
			&i.Lords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriodCloses = `-- name: ListPeriodCloses :many
SELECT what, period, closed_at, lords FROM admin.period_closes ORDER BY closed_at DESC LIMIT $1
`

func (q *Queries) ListPeriodCloses(ctx context.Context, lim int32) ([]AdminPeriodClose, error) {
	rows, err := q.db.Query(ctx, listPeriodCloses, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminPeriodClose{}
	for rows.Next() {
		var i AdminPeriodClose
		if err := rows.Scan(
			&i.What,
			&i.Period,
			&i.ClosedAt,
			&i.Lords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventSettled = `-- name: MarkEventSettled :exec
UPDATE admin.live_events SET settled_at = $1 WHERE id = $2
`

type MarkEventSettledParams struct {
	At *time.Time
	ID int64
}

func (q *Queries) MarkEventSettled(ctx context.Context, arg MarkEventSettledParams) error {
	_, err := q.db.Exec(ctx, markEventSettled, arg.At, arg.ID)
	return err
}

const mightGainStandings = `-- name: MightGainStandings :many
SELECT player_id, value, place FROM (
    SELECT ps.player_id, (p.might - ps.might_start)::bigint AS value,
           rank() OVER (ORDER BY p.might - ps.might_start DESC)::int AS place
    FROM app.player_season ps
    JOIN app.players p ON p.id = ps.player_id
    WHERE ps.season = $1 AND ps.might_start IS NOT NULL AND p.might > ps.might_start
      AND p.state = 'active' AND NOT p.is_bot
) ranked
WHERE place <= $2::int
ORDER BY place, player_id
`

type MightGainStandingsParams struct {
	Season int32
	Lim    int32
}

type MightGainStandingsRow struct {
	PlayerID uuid.UUID
	Value    int64
	Place    int32
}

// A closed season's places on the Might gained, as far as its rewards reach.
func (q *Queries) MightGainStandings(ctx context.Context, arg MightGainStandingsParams) ([]MightGainStandingsRow, error) {
	rows, err := q.db.Query(ctx, mightGainStandings, arg.Season, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MightGainStandingsRow{}
	for rows.Next() {
		var i MightGainStandingsRow
		if err := rows.Scan(&i.PlayerID, &i.Value, &i.Place); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const periodClosed = `-- name: PeriodClosed :one
SELECT EXISTS (SELECT 1 FROM admin.period_closes WHERE what = $1 AND period = $2)
`

type PeriodClosedParams struct {
	What   string
	Period int64
}

func (q *Queries) PeriodClosed(ctx context.Context, arg PeriodClosedParams) (bool, error) {
	row := q.db.QueryRow(ctx, periodClosed, arg.What, arg.Period)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const purgeHourlyUse = `-- name: PurgeHourlyUse :execrows
DELETE FROM app.player_hourly WHERE hour < $1::bigint
`

func (q *Queries) PurgeHourlyUse(ctx context.Context, beforeHour int64) (int64, error) {
	result, err := q.db.Exec(ctx, purgeHourlyUse, beforeHour)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const raiseLifeDeeds = `-- name: RaiseLifeDeeds :exec
INSERT INTO app.player_deeds (player_id, scope, period, deed, value)
SELECT unnest($1::uuid[]), 'life', 0, unnest($2::text[]), unnest($3::bigint[])
ON CONFLICT (player_id, scope, period, deed)
DO UPDATE SET value = GREATEST(app.player_deeds.value, EXCLUDED.value)
`

type RaiseLifeDeedsParams struct {
	PlayerIds []uuid.UUID
	Deeds     []string
	Vals      []int64
}

// Raises lifetime counters to at least the given values (parallel arrays).
func (q *Queries) RaiseLifeDeeds(ctx context.Context, arg RaiseLifeDeedsParams) error {
	_, err := q.db.Exec(ctx, raiseLifeDeeds, arg.PlayerIds, arg.Deeds, arg.Vals)
	return err
}

const recentEventsFor = `-- name: RecentEventsFor :many
SELECT e.id, e.template_id, e.starts_at, e.ends_at, e.frozen, e.note, e.created_by, e.created_at, e.revoked_at, e.revoked_by, e.settled_at, coalesce(pe.points_milli, 0)::bigint AS my_points_milli
FROM admin.live_events e
LEFT JOIN app.player_event pe ON pe.event_id = e.id AND pe.player_id = $1
WHERE e.revoked_at IS NULL AND e.ends_at <= $2 AND e.ends_at > $3
ORDER BY e.ends_at DESC
LIMIT 3
`

type RecentEventsForParams struct {
	PlayerID uuid.UUID
	Now      time.Time
	Since    time.Time
}

type RecentEventsForRow struct {
	ID            int64
	TemplateID    string
	StartsAt      time.Time
	EndsAt        time.Time
	Frozen        []byte
	Note          string
	CreatedBy     string
	CreatedAt     time.Time
	RevokedAt     *time.Time
	RevokedBy     *string
	SettledAt     *time.Time
	MyPointsMilli int64
}

// Festivals a lord took part in, newest first: the Events page's past cards.
func (q *Queries) RecentEventsFor(ctx context.Context, arg RecentEventsForParams) ([]RecentEventsForRow, error) {
	rows, err := q.db.Query(ctx, recentEventsFor, arg.PlayerID, arg.Now, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentEventsForRow{}
	for rows.Next() {
		var i RecentEventsForRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Frozen,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.SettledAt,
			&i.MyPointsMilli,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeLiveEvent = `-- name: RevokeLiveEvent :one
UPDATE admin.live_events SET revoked_at = $1, revoked_by = $2
WHERE id = $3 AND revoked_at IS NULL AND settled_at IS NULL
RETURNING id, template_id, starts_at, ends_at, frozen, note, created_by, created_at, revoked_at, revoked_by, settled_at
`

type RevokeLiveEventParams struct {
	At *time.Time
	By *string
	ID int64
}

func (q *Queries) RevokeLiveEvent(ctx context.Context, arg RevokeLiveEventParams) (AdminLiveEvent, error) {
	row := q.db.QueryRow(ctx, revokeLiveEvent, arg.At, arg.By, arg.ID)
	var i AdminLiveEvent
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Frozen,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.SettledAt,
	)
	return i, err
}

const revokeRoyal = `-- name: RevokeRoyal :one
WITH old AS (
    SELECT season, royal_claimed FROM app.player_season
    WHERE player_id = $1 AND royal_ref = $2::text
    FOR UPDATE
)
UPDATE app.player_season ps SET royal_at = NULL, royal_ref = NULL, royal_claimed = 0
FROM old
WHERE ps.player_id = $1 AND ps.season = old.season
RETURNING ps.season, old.royal_claimed AS was_claimed
`

type RevokeRoyalParams struct {
	PlayerID uuid.UUID
	Ref      string
}

type RevokeRoyalRow struct {
	Season     int32
	WasClaimed int64
}

// A refunded Charter closes the lane it opened, and forgets what was claimed
// from it (the refund takes that back): the tiers it had claimed come back, so
// their tokens can be counted off.
func (q *Queries) RevokeRoyal(ctx context.Context, arg RevokeRoyalParams) (RevokeRoyalRow, error) {
	row := q.db.QueryRow(ctx, revokeRoyal, arg.PlayerID, arg.Ref)
	var i RevokeRoyalRow
	err := row.Scan(&i.Season, &i.WasClaimed)
	return i, err
}

const seasonBoard = `-- name: SeasonBoard :many
SELECT ps.player_id, ps.points_milli, p.display_name, p.avatar, p.level,
       p.cos_frame, p.cos_title, p.cos_color, p.cos_crest, p.vip_points
FROM app.player_season ps
JOIN app.players p ON p.id = ps.player_id
WHERE ps.season = $1 AND ps.points_milli > 0 AND p.state = 'active' AND NOT p.is_bot
ORDER BY ps.points_milli DESC, ps.points_at, ps.player_id
LIMIT $2
`

type SeasonBoardParams struct {
	Season int32
	Lim    int32
}

type SeasonBoardRow struct {
	PlayerID    uuid.UUID
	PointsMilli int64
	DisplayName string
	Avatar      string
	Level       int32
	CosFrame    *string
	CosTitle    *string
	CosColor    *string
	CosCrest    *string
	VipPoints   int64
}

// A season's board by renown (its Charter points), first there first placed.
func (q *Queries) SeasonBoard(ctx context.Context, arg SeasonBoardParams) ([]SeasonBoardRow, error) {
	rows, err := q.db.Query(ctx, seasonBoard, arg.Season, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SeasonBoardRow{}
	for rows.Next() {
		var i SeasonBoardRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.PointsMilli,
			&i.DisplayName,
			&i.Avatar,
			&i.Level,
			&i.CosFrame,
			&i.CosTitle,
			&i.CosColor,
			&i.CosCrest,
			&i.VipPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonRows = `-- name: SeasonRows :many
SELECT player_id, season, points_milli, day, day_milli, points_at, free_claimed, royal_claimed, royal_at, royal_ref, might_start FROM app.player_season WHERE season = $1 AND points_milli > 0
`

// Every row of a season, for what its lords left unclaimed.
func (q *Queries) SeasonRows(ctx context.Context, season int32) ([]AppPlayerSeason, error) {
	rows, err := q.db.Query(ctx, seasonRows, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPlayerSeason{}
	for rows.Next() {
		var i AppPlayerSeason
		if err := rows.Scan(
			&i.PlayerID,
			&i.Season,
			&i.PointsMilli,
			&i.Day,
			&i.DayMilli,
			&i.PointsAt,
			&i.FreeClaimed,
			&i.RoyalClaimed,
			&i.RoyalAt,
			&i.RoyalRef,
			&i.MightStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonStandings = `-- name: SeasonStandings :many
SELECT ps.player_id, ps.season, ps.points_milli, ps.day, ps.day_milli, ps.points_at, ps.free_claimed, ps.royal_claimed, ps.royal_at, ps.royal_ref, ps.might_start
FROM app.player_season ps
JOIN app.players p ON p.id = ps.player_id
WHERE ps.season = $1 AND ps.points_milli > 0 AND p.state = 'active' AND NOT p.is_bot
ORDER BY ps.points_milli DESC, ps.points_at, ps.player_id
`

// Every lord with renown in a season, in place order, for its close.
func (q *Queries) SeasonStandings(ctx context.Context, season int32) ([]AppPlayerSeason, error) {
	rows, err := q.db.Query(ctx, seasonStandings, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPlayerSeason{}
	for rows.Next() {
		var i AppPlayerSeason
		if err := rows.Scan(
			&i.PlayerID,
			&i.Season,
			&i.PointsMilli,
			&i.Day,
			&i.DayMilli,
			&i.PointsAt,
			&i.FreeClaimed,
			&i.RoyalClaimed,
			&i.RoyalAt,
			&i.RoyalRef,
			&i.MightStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonSummary = `-- name: SeasonSummary :one
SELECT count(*)::int AS lords,
       count(*) FILTER (WHERE royal_at IS NOT NULL)::int AS royal,
       count(*) FILTER (WHERE royal_ref IS NOT NULL)::int AS royal_bought,
       coalesce(sum(points_milli), 0)::bigint AS points_milli,
       coalesce(max(points_milli), 0)::bigint AS top_milli
FROM app.player_season WHERE season = $1
`

type SeasonSummaryRow struct {
	Lords       int32
	Royal       int32
	RoyalBought int32
	PointsMilli int64
	TopMilli    int64
}

// The panel's view of a season.
func (q *Queries) SeasonSummary(ctx context.Context, season int32) (SeasonSummaryRow, error) {
	row := q.db.QueryRow(ctx, seasonSummary, season)
	var i SeasonSummaryRow
	err := row.Scan(
		&i.Lords,
		&i.Royal,
		&i.RoyalBought,
		&i.PointsMilli,
		&i.TopMilli,
	)
	return i, err
}

const seasonTierBands = `-- name: SeasonTierBands :many
SELECT LEAST($1::int, (points_milli / 1000 / $2::bigint)::int) / 10 AS band,
       count(*)::int AS lords
FROM app.player_season WHERE season = $3
GROUP BY 1 ORDER BY 1
`

type SeasonTierBandsParams struct {
	Tiers   int32
	PerTier int64
	Season  int32
}

type SeasonTierBandsRow struct {
	Band  int32
	Lords int32
}

// How the season's lords spread over its tiers, a band of ten at a time.
func (q *Queries) SeasonTierBands(ctx context.Context, arg SeasonTierBandsParams) ([]SeasonTierBandsRow, error) {
	rows, err := q.db.Query(ctx, seasonTierBands, arg.Tiers, arg.PerTier, arg.Season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SeasonTierBandsRow{}
	for rows.Next() {
		var i SeasonTierBandsRow
		if err := rows.Scan(&i.Band, &i.Lords); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHourly = `-- name: SetHourly :one
INSERT INTO admin.hourly_events (hour, event_id, source, set_by, note)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (hour) DO UPDATE
SET event_id = EXCLUDED.event_id, source = EXCLUDED.source, set_by = EXCLUDED.set_by,
    set_at = now(), note = EXCLUDED.note
RETURNING hour, event_id, source, set_by, set_at, note
`

type SetHourlyParams struct {
	Hour    int64
	EventID string
	Source  string
	SetBy   *string
	Note    string
}

// The panel forces or skips an hour that has not begun.
func (q *Queries) SetHourly(ctx context.Context, arg SetHourlyParams) (AdminHourlyEvent, error) {
	row := q.db.QueryRow(ctx, setHourly,
		arg.Hour,
		arg.EventID,
		arg.Source,
		arg.SetBy,
		arg.Note,
	)
	var i AdminHourlyEvent
	err := row.Scan(
		&i.Hour,
		&i.EventID,
		&i.Source,
		&i.SetBy,
		&i.SetAt,
		&i.Note,
	)
	return i, err
}

const unlockRoyal = `-- name: UnlockRoyal :one
UPDATE app.player_season SET royal_at = $1, royal_ref = $2
WHERE player_id = $3 AND season = $4 AND royal_at IS NULL
RETURNING player_id, season, points_milli, day, day_milli, points_at, free_claimed, royal_claimed, royal_at, royal_ref, might_start
`

type UnlockRoyalParams struct {
	At       *time.Time
	Ref      *string
	PlayerID uuid.UUID
	Season   int32
}

// Opens the royal lane for a season, once.
func (q *Queries) UnlockRoyal(ctx context.Context, arg UnlockRoyalParams) (AppPlayerSeason, error) {
	row := q.db.QueryRow(ctx, unlockRoyal,
		arg.At,
		arg.Ref,
		arg.PlayerID,
		arg.Season,
	)
	var i AppPlayerSeason
	err := row.Scan(
		&i.PlayerID,
		&i.Season,
		&i.PointsMilli,
		&i.Day,
		&i.DayMilli,
		&i.PointsAt,
		&i.FreeClaimed,
		&i.RoyalClaimed,
		&i.RoyalAt,
		&i.RoyalRef,
		&i.MightStart,
	)
	return i, err
}

const useHourly = `-- name: UseHourly :one
INSERT INTO app.player_hourly (player_id, hour, used)
VALUES ($1, $2, 1)
ON CONFLICT (player_id, hour) DO UPDATE SET used = app.player_hourly.used + 1
WHERE app.player_hourly.used < $3::smallint
RETURNING used
`

type UseHourlyParams struct {
	PlayerID uuid.UUID
	Hour     int64
	Max      int16
}

// One use of an hour's event, as long as fewer than max have been taken. No row
// back means the hour's allowance is spent.
func (q *Queries) UseHourly(ctx context.Context, arg UseHourlyParams) (int16, error) {
	row := q.db.QueryRow(ctx, useHourly, arg.PlayerID, arg.Hour, arg.Max)
	var used int16
	err := row.Scan(&used)
	return used, err
}
