// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mail.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimMailRow = `-- name: ClaimMailRow :one
UPDATE app.mail SET claimed_at = now(), read_at = coalesce(read_at, now())
WHERE id = $1 AND player_id = $2
  AND claimed_at IS NULL AND deleted_at IS NULL
  AND expires_at > $3::timestamptz
RETURNING id, player_id, kind, sender, title, body, attachments, idem_key, broadcast_id, created_at, expires_at, read_at, claimed_at, deleted_at
`

type ClaimMailRowParams struct {
	ID       int64
	PlayerID uuid.UUID
	Now      time.Time
}

// Claims a letter. The whole rule is in the WHERE -- theirs, unclaimed, not
// deleted, not expired -- so two taps or two devices get one claim.
func (q *Queries) ClaimMailRow(ctx context.Context, arg ClaimMailRowParams) (AppMail, error) {
	row := q.db.QueryRow(ctx, claimMailRow, arg.ID, arg.PlayerID, arg.Now)
	var i AppMail
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Kind,
		&i.Sender,
		&i.Title,
		&i.Body,
		&i.Attachments,
		&i.IdemKey,
		&i.BroadcastID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ReadAt,
		&i.ClaimedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countActivePlayers = `-- name: CountActivePlayers :one
SELECT count(*)::int FROM app.players WHERE NOT is_bot AND state = 'active'
`

func (q *Queries) CountActivePlayers(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countActivePlayers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countMailWaiting = `-- name: CountMailWaiting :one
SELECT count(*)::int FROM app.mail
WHERE player_id = $1
  AND deleted_at IS NULL
  AND expires_at > $2::timestamptz
  AND (read_at IS NULL OR (claimed_at IS NULL AND attachments <> '{}'::jsonb))
`

type CountMailWaitingParams struct {
	PlayerID uuid.UUID
	Now      time.Time
}

// What the heartbeat flags: letters not yet read, or read with something still
// to claim.
func (q *Queries) CountMailWaiting(ctx context.Context, arg CountMailWaitingParams) (int32, error) {
	row := q.db.QueryRow(ctx, countMailWaiting, arg.PlayerID, arg.Now)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSegment = `-- name: CountSegment :one
SELECT count(*)::int FROM app.players p
WHERE NOT p.is_bot AND p.state = 'active'
  AND p.level BETWEEN $1::int AND $2::int
  AND ($3::int = 0
       OR p.last_seen_at > now() - make_interval(days => $3::int))
`

type CountSegmentParams struct {
	MinLevel   int32
	MaxLevel   int32
	ActiveDays int32
}

// How many a segment send would reach, for the composer's preview.
func (q *Queries) CountSegment(ctx context.Context, arg CountSegmentParams) (int32, error) {
	row := q.db.QueryRow(ctx, countSegment, arg.MinLevel, arg.MaxLevel, arg.ActiveDays)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteMail = `-- name: DeleteMail :execrows
UPDATE app.mail SET deleted_at = $1::timestamptz
WHERE id = $2 AND player_id = $3 AND deleted_at IS NULL
  AND (claimed_at IS NOT NULL OR attachments = '{}'::jsonb OR expires_at <= $1::timestamptz)
`

type DeleteMailParams struct {
	Now      time.Time
	ID       int64
	PlayerID uuid.UUID
}

// A letter can be thrown away once there is nothing left in it to claim.
func (q *Queries) DeleteMail(ctx context.Context, arg DeleteMailParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMail, arg.Now, arg.ID, arg.PlayerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUnclaimedBroadcastMail = `-- name: DeleteUnclaimedBroadcastMail :execrows
UPDATE app.mail SET deleted_at = now()
WHERE broadcast_id = $1 AND claimed_at IS NULL AND deleted_at IS NULL
`

func (q *Queries) DeleteUnclaimedBroadcastMail(ctx context.Context, broadcastID pgtype.Int8) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnclaimedBroadcastMail, broadcastID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMail = `-- name: GetMail :one
SELECT id, player_id, kind, sender, title, body, attachments, idem_key, broadcast_id, created_at, expires_at, read_at, claimed_at, deleted_at FROM app.mail WHERE id = $1 AND player_id = $2
`

type GetMailParams struct {
	ID       int64
	PlayerID uuid.UUID
}

func (q *Queries) GetMail(ctx context.Context, arg GetMailParams) (AppMail, error) {
	row := q.db.QueryRow(ctx, getMail, arg.ID, arg.PlayerID)
	var i AppMail
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Kind,
		&i.Sender,
		&i.Title,
		&i.Body,
		&i.Attachments,
		&i.IdemKey,
		&i.BroadcastID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ReadAt,
		&i.ClaimedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertBroadcast = `-- name: InsertBroadcast :one

INSERT INTO admin.mail_broadcasts (audience, segment, sender, title, body, attachments,
                                   include_new, expires_at, created_by, note)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9,
        $10)
RETURNING id, audience, segment, sender, title, body, attachments, include_new, expires_at, sent_count, created_by, created_at, revoked_at, revoked_by, note
`

type InsertBroadcastParams struct {
	Audience    string
	Segment     []byte
	Sender      string
	Title       string
	Body        string
	Attachments []byte
	IncludeNew  bool
	ExpiresAt   time.Time
	CreatedBy   string
	Note        string
}

// ----------------------------------------------------------------------------
// Admin
// ----------------------------------------------------------------------------
func (q *Queries) InsertBroadcast(ctx context.Context, arg InsertBroadcastParams) (AdminMailBroadcast, error) {
	row := q.db.QueryRow(ctx, insertBroadcast,
		arg.Audience,
		arg.Segment,
		arg.Sender,
		arg.Title,
		arg.Body,
		arg.Attachments,
		arg.IncludeNew,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.Note,
	)
	var i AdminMailBroadcast
	err := row.Scan(
		&i.ID,
		&i.Audience,
		&i.Segment,
		&i.Sender,
		&i.Title,
		&i.Body,
		&i.Attachments,
		&i.IncludeNew,
		&i.ExpiresAt,
		&i.SentCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.Note,
	)
	return i, err
}

const insertMail = `-- name: InsertMail :one

INSERT INTO app.mail (player_id, kind, sender, title, body, attachments, idem_key, broadcast_id, expires_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9)
ON CONFLICT (player_id, idem_key) WHERE idem_key IS NOT NULL DO NOTHING
RETURNING id, player_id, kind, sender, title, body, attachments, idem_key, broadcast_id, created_at, expires_at, read_at, claimed_at, deleted_at
`

type InsertMailParams struct {
	PlayerID    uuid.UUID
	Kind        string
	Sender      string
	Title       string
	Body        string
	Attachments []byte
	IdemKey     *string
	BroadcastID pgtype.Int8
	ExpiresAt   time.Time
}

// The Royal Mail. See migration 00031.
// Sends one letter. The idempotency key makes a repeat of the same send a no-op:
// zero rows back means the letter was already delivered.
func (q *Queries) InsertMail(ctx context.Context, arg InsertMailParams) (AppMail, error) {
	row := q.db.QueryRow(ctx, insertMail,
		arg.PlayerID,
		arg.Kind,
		arg.Sender,
		arg.Title,
		arg.Body,
		arg.Attachments,
		arg.IdemKey,
		arg.BroadcastID,
		arg.ExpiresAt,
	)
	var i AppMail
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Kind,
		&i.Sender,
		&i.Title,
		&i.Body,
		&i.Attachments,
		&i.IdemKey,
		&i.BroadcastID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ReadAt,
		&i.ClaimedAt,
		&i.DeletedAt,
	)
	return i, err
}

const latestAllBroadcast = `-- name: LatestAllBroadcast :one
SELECT coalesce(max(id), 0)::bigint FROM admin.mail_broadcasts
WHERE audience = 'all' AND revoked_at IS NULL AND expires_at > $1::timestamptz
`

// The newest live 'all' letter, so a heartbeat can tell in one indexed read
// whether this player has a copy still to make.
func (q *Queries) LatestAllBroadcast(ctx context.Context, now time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, latestAllBroadcast, now)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listBroadcasts = `-- name: ListBroadcasts :many
SELECT b.id, b.audience, b.segment, b.sender, b.title, b.body, b.attachments, b.include_new, b.expires_at, b.sent_count, b.created_by, b.created_at, b.revoked_at, b.revoked_by, b.note,
       (SELECT count(*) FROM app.mail m WHERE m.broadcast_id = b.id)::int AS delivered,
       (SELECT count(*) FROM app.mail m WHERE m.broadcast_id = b.id AND m.claimed_at IS NOT NULL)::int AS claimed,
       (SELECT count(*) FROM app.mail m WHERE m.broadcast_id = b.id AND m.claimed_at IS NULL
          AND b.revoked_at IS NOT NULL AND m.deleted_at = b.revoked_at)::int AS withdrawn,
       coalesce((SELECT p.username FROM app.mail m JOIN app.players p ON p.id = m.player_id
                 WHERE m.broadcast_id = b.id AND b.audience = 'player' LIMIT 1), '')::text AS recipient
FROM admin.mail_broadcasts b
ORDER BY b.created_at DESC
LIMIT $1
`

type ListBroadcastsRow struct {
	ID          int64
	Audience    string
	Segment     []byte
	Sender      string
	Title       string
	Body        string
	Attachments []byte
	IncludeNew  bool
	ExpiresAt   time.Time
	SentCount   int32
	CreatedBy   string
	CreatedAt   time.Time
	RevokedAt   *time.Time
	RevokedBy   *string
	Note        string
	Delivered   int32
	Claimed     int32
	Withdrawn   int32
	Recipient   string
}

// delivered is every copy ever written; withdrawn, the unclaimed ones a revoke
// took back (the revoke stamps them in its own transaction, so at its instant);
// recipient names the lord a single-player letter went to.
func (q *Queries) ListBroadcasts(ctx context.Context, lim int32) ([]ListBroadcastsRow, error) {
	rows, err := q.db.Query(ctx, listBroadcasts, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBroadcastsRow{}
	for rows.Next() {
		var i ListBroadcastsRow
		if err := rows.Scan(
			&i.ID,
			&i.Audience,
			&i.Segment,
			&i.Sender,
			&i.Title,
			&i.Body,
			&i.Attachments,
			&i.IncludeNew,
			&i.ExpiresAt,
			&i.SentCount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.Note,
			&i.Delivered,
			&i.Claimed,
			&i.Withdrawn,
			&i.Recipient,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimableMail = `-- name: ListClaimableMail :many
SELECT id FROM app.mail
WHERE player_id = $1
  AND claimed_at IS NULL AND deleted_at IS NULL
  AND expires_at > $2::timestamptz
  AND attachments <> '{}'::jsonb
ORDER BY created_at ASC, id ASC
LIMIT $3
`

type ListClaimableMailParams struct {
	PlayerID uuid.UUID
	Now      time.Time
	Lim      int32
}

// The letters CLAIM ALL opens: live, unclaimed, and carrying something.
func (q *Queries) ListClaimableMail(ctx context.Context, arg ListClaimableMailParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listClaimableMail, arg.PlayerID, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMail = `-- name: ListMail :many
SELECT id, player_id, kind, sender, title, body, attachments, idem_key, broadcast_id, created_at, expires_at, read_at, claimed_at, deleted_at FROM app.mail
WHERE player_id = $1
  AND deleted_at IS NULL
  AND (expires_at > $2::timestamptz OR claimed_at IS NOT NULL)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListMailParams struct {
	PlayerID uuid.UUID
	Now      time.Time
	Lim      int32
}

// A player's inbox: every letter not deleted that can still be read -- claimable,
// or already claimed and kept. An unclaimed letter past its expiry is gone.
func (q *Queries) ListMail(ctx context.Context, arg ListMailParams) ([]AppMail, error) {
	rows, err := q.db.Query(ctx, listMail, arg.PlayerID, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppMail{}
	for rows.Next() {
		var i AppMail
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Kind,
			&i.Sender,
			&i.Title,
			&i.Body,
			&i.Attachments,
			&i.IdemKey,
			&i.BroadcastID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ReadAt,
			&i.ClaimedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMailRead = `-- name: MarkMailRead :exec
UPDATE app.mail SET read_at = coalesce(read_at, now())
WHERE id = $1 AND player_id = $2
`

type MarkMailReadParams struct {
	ID       int64
	PlayerID uuid.UUID
}

func (q *Queries) MarkMailRead(ctx context.Context, arg MarkMailReadParams) error {
	_, err := q.db.Exec(ctx, markMailRead, arg.ID, arg.PlayerID)
	return err
}

const materializeBroadcasts = `-- name: MaterializeBroadcasts :execrows
INSERT INTO app.mail (player_id, kind, sender, title, body, attachments, idem_key, broadcast_id, expires_at)
SELECT p.id, 'admin', b.sender, b.title, b.body, b.attachments, 'bc:' || b.id, b.id, b.expires_at
FROM admin.mail_broadcasts b
JOIN app.players p ON p.id = $1
WHERE b.audience = 'all' AND b.revoked_at IS NULL
  AND b.expires_at > $2::timestamptz
  AND b.id > p.mail_bc_seen
  AND (b.include_new OR p.created_at <= b.created_at)
ON CONFLICT (player_id, idem_key) WHERE idem_key IS NOT NULL DO NOTHING
`

type MaterializeBroadcastsParams struct {
	PlayerID uuid.UUID
	Now      time.Time
}

// Gives this player their copy of every live 'all' letter newer than the last
// they received. The key 'bc:<id>' makes it safe to run twice.
func (q *Queries) MaterializeBroadcasts(ctx context.Context, arg MaterializeBroadcastsParams) (int64, error) {
	result, err := q.db.Exec(ctx, materializeBroadcasts, arg.PlayerID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeMail = `-- name: PurgeMail :execrows
DELETE FROM app.mail
WHERE (deleted_at IS NOT NULL AND deleted_at < $1::timestamptz)
   OR expires_at < $1::timestamptz
`

// Housekeeping: letters deleted, or expired unclaimed, longer ago than the keep
// window. Claimed letters are kept until the same window passes their expiry.
func (q *Queries) PurgeMail(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeMail, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeBroadcast = `-- name: RevokeBroadcast :one
UPDATE admin.mail_broadcasts SET revoked_at = now(), revoked_by = $1
WHERE id = $2 AND revoked_at IS NULL
RETURNING id, audience, segment, sender, title, body, attachments, include_new, expires_at, sent_count, created_by, created_at, revoked_at, revoked_by, note
`

type RevokeBroadcastParams struct {
	RevokedBy *string
	ID        int64
}

// Revoking stops a letter reaching anyone else and takes back the copies nobody
// has claimed yet. What was claimed stays claimed.
func (q *Queries) RevokeBroadcast(ctx context.Context, arg RevokeBroadcastParams) (AdminMailBroadcast, error) {
	row := q.db.QueryRow(ctx, revokeBroadcast, arg.RevokedBy, arg.ID)
	var i AdminMailBroadcast
	err := row.Scan(
		&i.ID,
		&i.Audience,
		&i.Segment,
		&i.Sender,
		&i.Title,
		&i.Body,
		&i.Attachments,
		&i.IncludeNew,
		&i.ExpiresAt,
		&i.SentCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.Note,
	)
	return i, err
}

const sendSegmentMail = `-- name: SendSegmentMail :execrows
INSERT INTO app.mail (player_id, kind, sender, title, body, attachments, idem_key, broadcast_id, expires_at)
SELECT p.id, 'admin', b.sender, b.title, b.body, b.attachments, 'bc:' || b.id, b.id, b.expires_at
FROM admin.mail_broadcasts b, app.players p
WHERE b.id = $1
  AND NOT p.is_bot AND p.state = 'active'
  AND p.level BETWEEN $2::int AND $3::int
  AND ($4::int = 0
       OR p.last_seen_at > now() - make_interval(days => $4::int))
ON CONFLICT (player_id, idem_key) WHERE idem_key IS NOT NULL DO NOTHING
`

type SendSegmentMailParams struct {
	BroadcastID int64
	MinLevel    int32
	MaxLevel    int32
	ActiveDays  int32
}

// Writes a segment letter for everyone who matches, at once. Bots never get
// mail; they cannot read it.
func (q *Queries) SendSegmentMail(ctx context.Context, arg SendSegmentMailParams) (int64, error) {
	result, err := q.db.Exec(ctx, sendSegmentMail,
		arg.BroadcastID,
		arg.MinLevel,
		arg.MaxLevel,
		arg.ActiveDays,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBroadcastSent = `-- name: SetBroadcastSent :exec
UPDATE admin.mail_broadcasts SET sent_count = $1 WHERE id = $2
`

type SetBroadcastSentParams struct {
	SentCount int32
	ID        int64
}

func (q *Queries) SetBroadcastSent(ctx context.Context, arg SetBroadcastSentParams) error {
	_, err := q.db.Exec(ctx, setBroadcastSent, arg.SentCount, arg.ID)
	return err
}

const setMailBroadcastSeen = `-- name: SetMailBroadcastSeen :exec
UPDATE app.players SET mail_bc_seen = GREATEST(mail_bc_seen, $1::bigint)
WHERE id = $2
`

type SetMailBroadcastSeenParams struct {
	Seen int64
	ID   uuid.UUID
}

func (q *Queries) SetMailBroadcastSeen(ctx context.Context, arg SetMailBroadcastSeenParams) error {
	_, err := q.db.Exec(ctx, setMailBroadcastSeen, arg.Seen, arg.ID)
	return err
}
