// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
)

type AppGoldLedger struct {
	ID           int64
	PlayerID     uuid.UUID
	Delta        int64
	BalanceAfter int64
	Reason       string
	RefID        *string
	CreatedAt    time.Time
}

type AppIdentity struct {
	ID         uuid.UUID
	PlayerID   uuid.UUID
	Kind       string
	Subject    string
	SecretHash *string
	CreatedAt  time.Time
	LastUsedAt *time.Time
}

type AppPlayer struct {
	ID                 uuid.UUID
	Username           string
	DisplayName        string
	Level              int32
	Xp                 int64
	Gold               int64
	TreasuryGold       int64
	Diamonds           int64
	EnergyMilli        int64
	EnergyUpdatedAt    time.Time
	StatEnergy         int32
	StatAttack         int32
	StatDefense        int32
	StatPointsUnspent  int32
	ShieldUntil        *time.Time
	ActionSeq          int64
	State              string
	ResetOffsetMinutes int32
	CreatedAt          time.Time
	LastSeenAt         time.Time
	SoldierSlots       int32
	FreeSlotClaimed    bool
	FreeRecruitClaimed bool
}

type AppPlayerItem struct {
	ID                  uuid.UUID
	PlayerID            uuid.UUID
	DefID               string
	Slot                string
	Tier                string
	Ilvl                int32
	QualityPct          int32
	Masterwork          bool
	Attack              int64
	Defense             int64
	Speed               int64
	EquippedOnHero      bool
	EquippedSoldierID   *uuid.UUID
	AcquiredAt          time.Time
	AcquiredFrom        string
	RolledConfigVersion int32
}

type AppPlayerJobProgress struct {
	PlayerID uuid.UUID
	JobID    string
	Collects int64
}

type AppServerInfo struct {
	Key       string
	Value     string
	UpdatedAt time.Time
}

type AppSession struct {
	ID            uuid.UUID
	PlayerID      uuid.UUID
	FamilyID      uuid.UUID
	TokenHash     []byte
	IssuedAt      time.Time
	ExpiresAt     time.Time
	UsedAt        *time.Time
	RevokedAt     *time.Time
	RevokedReason *string
	UserAgent     *string
}

type AppShopState struct {
	PlayerID      uuid.UUID
	WindowID      int64
	PurchasedMask int32
	RerollIndex   int32
}

type AppSoldier struct {
	ID                  uuid.UUID
	PlayerID            uuid.UUID
	SlotIndex           int32
	TypeID              string
	Tier                string
	Level               int32
	Name                string
	RecruitedAt         time.Time
	RolledConfigVersion int32
}
