// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAuditLog struct {
	ID        int64
	AdminID   *uuid.UUID
	AdminName string
	Action    string
	Subject   *string
	Before    []byte
	After     []byte
	Note      string
	CreatedAt time.Time
}

type AdminBalanceActivation struct {
	ID          int64
	VersionID   int64
	ActivatedBy string
	Reason      string
	ActivatedAt time.Time
}

type AdminBalanceVersion struct {
	ID        int64
	Doc       string
	DocJson   []byte
	Sha256    []byte
	Note      string
	CreatedBy string
	CreatedAt time.Time
}

type AdminSession struct {
	ID        uuid.UUID
	AdminID   uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
}

type AdminUser struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Role         string
	Disabled     bool
	CreatedAt    time.Time
	LastLoginAt  *time.Time
}

type AppAttackCooldown struct {
	AttackerID uuid.UUID
	DefenderID uuid.UUID
	LastAt     time.Time
	Count24h   int32
}

type AppBattle struct {
	ID            uuid.UUID
	AttackerID    uuid.UUID
	DefenderID    uuid.UUID
	Seed          int64
	ConfigVersion int32
	AttackerWon   bool
	Rounds        int32
	AttackerMight int64
	DefenderMight int64
	GoldStolen    int64
	RansomPaid    int64
	XpAwarded     int64
	EnergySpent   int64
	Replay        []byte
	CreatedAt     time.Time
}

type AppGoldLedger struct {
	ID           int64
	PlayerID     uuid.UUID
	Delta        int64
	BalanceAfter int64
	Reason       string
	RefID        *string
	CreatedAt    time.Time
}

type AppIdentity struct {
	ID         uuid.UUID
	PlayerID   uuid.UUID
	Kind       string
	Subject    string
	SecretHash *string
	CreatedAt  time.Time
	LastUsedAt *time.Time
}

type AppKingdom struct {
	ID         uuid.UUID
	Name       string
	Tag        string
	LeaderID   *uuid.UUID
	Level      int32
	Xp         int64
	Treasury   int64
	Reputation int64
	CreatedAt  time.Time
}

type AppKingdomInvite struct {
	KingdomID uuid.UUID
	PlayerID  uuid.UUID
	InvitedBy *uuid.UUID
	CreatedAt time.Time
}

type AppKingdomUpgrade struct {
	KingdomID uuid.UUID
	UpgradeID string
	Level     int32
}

type AppPlayer struct {
	ID                  uuid.UUID
	Username            string
	DisplayName         string
	Level               int32
	Xp                  int64
	Gold                int64
	TreasuryGold        int64
	Diamonds            int64
	EnergyMilli         int64
	EnergyUpdatedAt     time.Time
	StatEnergy          int32
	StatAttack          int32
	StatDefense         int32
	StatPointsUnspent   int32
	ShieldUntil         *time.Time
	ActionSeq           int64
	State               string
	ResetOffsetMinutes  int32
	CreatedAt           time.Time
	LastSeenAt          time.Time
	SoldierSlots        int32
	FreeSlotClaimed     bool
	FreeRecruitClaimed  bool
	IsBot               bool
	TaxMilliAccrued     int64
	TaxUpdatedAt        time.Time
	KingdomID           *uuid.UUID
	KingdomRole         string
	KingdomJoinedAt     *time.Time
	KingdomDonatedTotal int64
	KingdomFavour       int64
	KingdomRepToday     int32
	KingdomDonatedToday int64
	KingdomDay          pgtype.Date
	Avatar              string
}

type AppPlayerHolding struct {
	PlayerID  uuid.UUID
	HoldingID string
	Level     int32
}

type AppPlayerItem struct {
	ID                  uuid.UUID
	PlayerID            uuid.UUID
	DefID               string
	Slot                string
	Tier                string
	Ilvl                int32
	QualityPct          int32
	Masterwork          bool
	Attack              int64
	Defense             int64
	Speed               int64
	EquippedOnHero      bool
	EquippedSoldierID   *uuid.UUID
	AcquiredAt          time.Time
	AcquiredFrom        string
	RolledConfigVersion int32
}

type AppPlayerJobProgress struct {
	PlayerID uuid.UUID
	JobID    string
	Collects int64
}

type AppPlayerUpgrade struct {
	PlayerID  uuid.UUID
	UpgradeID string
	Level     int32
}

type AppServerInfo struct {
	Key       string
	Value     string
	UpdatedAt time.Time
}

type AppSession struct {
	ID            uuid.UUID
	PlayerID      uuid.UUID
	FamilyID      uuid.UUID
	TokenHash     []byte
	IssuedAt      time.Time
	ExpiresAt     time.Time
	UsedAt        *time.Time
	RevokedAt     *time.Time
	RevokedReason *string
	UserAgent     *string
}

type AppShopState struct {
	PlayerID      uuid.UUID
	WindowID      int64
	PurchasedMask int32
	RerollIndex   int32
}

type AppSoldier struct {
	ID                  uuid.UUID
	PlayerID            uuid.UUID
	SlotIndex           int32
	TypeID              string
	Tier                string
	Level               int32
	Name                string
	RecruitedAt         time.Time
	RolledConfigVersion int32
}
