// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const beginLegacy = `-- name: BeginLegacy :one
UPDATE app.players
SET level               = 1,
    xp                  = 0,
    stat_energy         = 0,
    stat_attack         = 0,
    stat_defense        = 0,
    stat_points_unspent = 0,
    legacy              = legacy + 1,
    action_seq          = $1
WHERE id = $2
  AND level = $3
  AND legacy < $4
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs
`

type BeginLegacyParams struct {
	ActionSeq int64
	ID        uuid.UUID
	LevelCap  int32
	MaxStacks int32
}

// Begins a new Legacy run.
//
// Level, experience and every stat point go back to nothing; gold, gear,
// soldiers and estates are untouched. The WHERE is the whole guard: it only
// lands at the cap and below the stack limit, so a double tap cannot burn two
// runs and a client cannot ask for one it has not earned.
func (q *Queries) BeginLegacy(ctx context.Context, arg BeginLegacyParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, beginLegacy,
		arg.ActionSeq,
		arg.ID,
		arg.LevelCap,
		arg.MaxStacks,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const bumpActionSeq = `-- name: BumpActionSeq :one
UPDATE app.players SET action_seq = $2 WHERE id = $1 RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs
`

type BumpActionSeqParams struct {
	ID        uuid.UUID
	ActionSeq int64
}

func (q *Queries) BumpActionSeq(ctx context.Context, arg BumpActionSeqParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, bumpActionSeq, arg.ID, arg.ActionSeq)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const bumpQuestProgress = `-- name: BumpQuestProgress :one
INSERT INTO app.player_quests (player_id, day, collects, wins, buys, energy,
                               stages, hunts, aids, blows, quest_ids)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10, $11)
ON CONFLICT (player_id, day) DO UPDATE
SET collects = app.player_quests.collects + EXCLUDED.collects,
    wins     = app.player_quests.wins     + EXCLUDED.wins,
    buys     = app.player_quests.buys     + EXCLUDED.buys,
    energy   = app.player_quests.energy   + EXCLUDED.energy,
    stages   = app.player_quests.stages   + EXCLUDED.stages,
    hunts    = app.player_quests.hunts    + EXCLUDED.hunts,
    aids     = app.player_quests.aids     + EXCLUDED.aids,
    blows    = app.player_quests.blows    + EXCLUDED.blows,
    updated_at = now()
RETURNING player_id, day, collects, wins, buys, energy, claimed, updated_at, quest_ids, stages, hunts, aids, blows
`

type BumpQuestProgressParams struct {
	PlayerID uuid.UUID
	Day      pgtype.Date
	Collects int32
	Wins     int32
	Buys     int32
	Energy   int32
	Stages   int32
	Hunts    int32
	Aids     int32
	Blows    int32
	QuestIds []string
}

// Bumps today's quest counters, creating the row on first action of the day.
//
// One statement so the hot paths (collect, attack, buy) pay a single round trip
// and never a read-then-write race.
func (q *Queries) BumpQuestProgress(ctx context.Context, arg BumpQuestProgressParams) (AppPlayerQuest, error) {
	row := q.db.QueryRow(ctx, bumpQuestProgress,
		arg.PlayerID,
		arg.Day,
		arg.Collects,
		arg.Wins,
		arg.Buys,
		arg.Energy,
		arg.Stages,
		arg.Hunts,
		arg.Aids,
		arg.Blows,
		arg.QuestIds,
	)
	var i AppPlayerQuest
	err := row.Scan(
		&i.PlayerID,
		&i.Day,
		&i.Collects,
		&i.Wins,
		&i.Buys,
		&i.Energy,
		&i.Claimed,
		&i.UpdatedAt,
		&i.QuestIds,
		&i.Stages,
		&i.Hunts,
		&i.Aids,
		&i.Blows,
	)
	return i, err
}

const claimQuest = `-- name: ClaimQuest :one
UPDATE app.player_quests
SET claimed = claimed | $1
WHERE player_id = $2 AND day = $3
  AND (claimed & $1) = 0
RETURNING player_id, day, collects, wins, buys, energy, claimed, updated_at, quest_ids, stages, hunts, aids, blows
`

type ClaimQuestParams struct {
	Bit      int32
	PlayerID uuid.UUID
	Day      pgtype.Date
}

// Claims one quest slot. The bit test is inside the WHERE, so a double tap gets
// zero rows and is paid once.
func (q *Queries) ClaimQuest(ctx context.Context, arg ClaimQuestParams) (AppPlayerQuest, error) {
	row := q.db.QueryRow(ctx, claimQuest, arg.Bit, arg.PlayerID, arg.Day)
	var i AppPlayerQuest
	err := row.Scan(
		&i.PlayerID,
		&i.Day,
		&i.Collects,
		&i.Wins,
		&i.Buys,
		&i.Energy,
		&i.Claimed,
		&i.UpdatedAt,
		&i.QuestIds,
		&i.Stages,
		&i.Hunts,
		&i.Aids,
		&i.Blows,
	)
	return i, err
}

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO app.players (username, display_name, energy_milli, reset_offset_minutes)
VALUES ($1, $2, $3, $4)
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs
`

type CreatePlayerParams struct {
	Username           string
	DisplayName        string
	EnergyMilli        int64
	ResetOffsetMinutes int32
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, createPlayer,
		arg.Username,
		arg.DisplayName,
		arg.EnergyMilli,
		arg.ResetOffsetMinutes,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const deletePlayer = `-- name: DeletePlayer :execrows
DELETE FROM app.players WHERE id = $1
`

// Removes a player and, through every foreign key's ON DELETE CASCADE, all that
// was theirs: identities and sessions, items, soldiers, estates, battles, the
// gold ledger, revenge, quests, deeds, mail, the collection, device tokens.
// What has no foreign key outlives them on purpose: the diamond ledger and
// app.player_days (see 00027 and 00033).
func (q *Queries) DeletePlayer(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlayer, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureQuestDay = `-- name: EnsureQuestDay :one
INSERT INTO app.player_quests (player_id, day, quest_ids)
VALUES ($1, $2, $3)
ON CONFLICT (player_id, day) DO UPDATE
SET updated_at = app.player_quests.updated_at
RETURNING player_id, day, collects, wins, buys, energy, claimed, updated_at, quest_ids, stages, hunts, aids, blows
`

type EnsureQuestDayParams struct {
	PlayerID uuid.UUID
	Day      pgtype.Date
	QuestIds []string
}

// Creates the day's row with its three quests if it is not there yet, and
// returns whatever the row holds either way.
//
// The DO UPDATE is a no-op touch purely so RETURNING gives a row on conflict:
// the quest_ids of an existing day are never rewritten, which is the whole
// point — the board is frozen once it exists.
func (q *Queries) EnsureQuestDay(ctx context.Context, arg EnsureQuestDayParams) (AppPlayerQuest, error) {
	row := q.db.QueryRow(ctx, ensureQuestDay, arg.PlayerID, arg.Day, arg.QuestIds)
	var i AppPlayerQuest
	err := row.Scan(
		&i.PlayerID,
		&i.Day,
		&i.Collects,
		&i.Wins,
		&i.Buys,
		&i.Energy,
		&i.Claimed,
		&i.UpdatedAt,
		&i.QuestIds,
		&i.Stages,
		&i.Hunts,
		&i.Aids,
		&i.Blows,
	)
	return i, err
}

const findInvitablePlayers = `-- name: FindInvitablePlayers :many
SELECT id, username, display_name, avatar, level, kingdom_id
FROM app.players
WHERE state = 'active'
  AND is_bot = false
  AND id <> $1
  AND lower(username) LIKE lower($2)
ORDER BY level DESC
LIMIT 20
`

type FindInvitablePlayersParams struct {
	ID    uuid.UUID
	Lower string
}

type FindInvitablePlayersRow struct {
	ID          uuid.UUID
	Username    string
	DisplayName string
	Avatar      string
	Level       int32
	KingdomID   *uuid.UUID
}

// Finds someone to invite. Prefix match rather than substring, so a search is
// index-friendly and a player cannot enumerate the roster by typing one letter.
//
// Bots are excluded: they exist to fill the Attack tab and cannot accept.
func (q *Queries) FindInvitablePlayers(ctx context.Context, arg FindInvitablePlayersParams) ([]FindInvitablePlayersRow, error) {
	rows, err := q.db.Query(ctx, findInvitablePlayers, arg.ID, arg.Lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindInvitablePlayersRow{}
	for rows.Next() {
		var i FindInvitablePlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Avatar,
			&i.Level,
			&i.KingdomID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasswordIdentity = `-- name: GetPasswordIdentity :one
SELECT id, player_id, kind, subject, secret_hash, created_at, last_used_at FROM app.identities WHERE player_id = $1 AND kind = 'password'
`

// The password a player signed up with, to confirm a deletion with.
func (q *Queries) GetPasswordIdentity(ctx context.Context, playerID uuid.UUID) (AppIdentity, error) {
	row := q.db.QueryRow(ctx, getPasswordIdentity, playerID)
	var i AppIdentity
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Kind,
		&i.Subject,
		&i.SecretHash,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs FROM app.players WHERE id = $1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id uuid.UUID) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, id)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const getPlayerByUsername = `-- name: GetPlayerByUsername :one
SELECT id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs FROM app.players WHERE lower(username) = lower($1)
`

func (q *Queries) GetPlayerByUsername(ctx context.Context, lower string) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, getPlayerByUsername, lower)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const getQuestProgress = `-- name: GetQuestProgress :one
SELECT player_id, day, collects, wins, buys, energy, claimed, updated_at, quest_ids, stages, hunts, aids, blows FROM app.player_quests WHERE player_id = $1 AND day = $2
`

type GetQuestProgressParams struct {
	PlayerID uuid.UUID
	Day      pgtype.Date
}

func (q *Queries) GetQuestProgress(ctx context.Context, arg GetQuestProgressParams) (AppPlayerQuest, error) {
	row := q.db.QueryRow(ctx, getQuestProgress, arg.PlayerID, arg.Day)
	var i AppPlayerQuest
	err := row.Scan(
		&i.PlayerID,
		&i.Day,
		&i.Collects,
		&i.Wins,
		&i.Buys,
		&i.Energy,
		&i.Claimed,
		&i.UpdatedAt,
		&i.QuestIds,
		&i.Stages,
		&i.Hunts,
		&i.Aids,
		&i.Blows,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT token, platform FROM app.device_tokens
WHERE player_id = $1 AND revoked_at IS NULL
`

type ListDevicesRow struct {
	Token    string
	Platform string
}

func (q *Queries) ListDevices(ctx context.Context, playerID uuid.UUID) ([]ListDevicesRow, error) {
	rows, err := q.db.Query(ctx, listDevices, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicesRow{}
	for rows.Next() {
		var i ListDevicesRow
		if err := rows.Scan(&i.Token, &i.Platform); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPlayer = `-- name: LockPlayer :one
SELECT id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs FROM app.players WHERE id = $1 FOR UPDATE
`

// Locks the row for the duration of the transaction. Every mutating action
// takes this first, so two concurrent collects cannot both read the same energy
// and both spend it.
func (q *Queries) LockPlayer(ctx context.Context, id uuid.UUID) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, lockPlayer, id)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const recentlySeenPlayers = `-- name: RecentlySeenPlayers :many
SELECT id, last_seen_at FROM app.players
WHERE last_seen_at > $1 AND NOT is_bot
`

type RecentlySeenPlayersRow struct {
	ID         uuid.UUID
	LastSeenAt time.Time
}

// The players seen recently, to repopulate the presence registry after a
// restart. Without it a deploy shows every player leaving at once.
func (q *Queries) RecentlySeenPlayers(ctx context.Context, lastSeenAt time.Time) ([]RecentlySeenPlayersRow, error) {
	rows, err := q.db.Query(ctx, recentlySeenPlayers, lastSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentlySeenPlayersRow{}
	for rows.Next() {
		var i RecentlySeenPlayersRow
		if err := rows.Scan(&i.ID, &i.LastSeenAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerDevice = `-- name: RegisterDevice :exec
INSERT INTO app.device_tokens (token, player_id, platform, seen_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (token) DO UPDATE
SET player_id = EXCLUDED.player_id, platform = EXCLUDED.platform,
    seen_at = now(), revoked_at = NULL
`

type RegisterDeviceParams struct {
	Token    string
	PlayerID uuid.UUID
	Platform string
}

// Registers a device, or re-points one that moved to another account.
func (q *Queries) RegisterDevice(ctx context.Context, arg RegisterDeviceParams) error {
	_, err := q.db.Exec(ctx, registerDevice, arg.Token, arg.PlayerID, arg.Platform)
	return err
}

const renamePlayer = `-- name: RenamePlayer :one
UPDATE app.players
SET username     = $1,
    display_name = $2,
    diamonds     = diamonds - $3,
    action_seq   = $4
WHERE id = $5 AND diamonds >= $3
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs
`

type RenamePlayerParams struct {
	Username    string
	DisplayName string
	Diamonds    int64
	ActionSeq   int64
	ID          uuid.UUID
}

// Buys a new name. The WHERE carries the price, so a double tap cannot pay
// twice, and players_username_lower_key refuses a name somebody else holds.
func (q *Queries) RenamePlayer(ctx context.Context, arg RenamePlayerParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, renamePlayer,
		arg.Username,
		arg.DisplayName,
		arg.Diamonds,
		arg.ActionSeq,
		arg.ID,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const setAvatar = `-- name: SetAvatar :one
UPDATE app.players SET avatar = $2, action_seq = $3
WHERE id = $1 RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs
`

type SetAvatarParams struct {
	ID        uuid.UUID
	Avatar    string
	ActionSeq int64
}

func (q *Queries) SetAvatar(ctx context.Context, arg SetAvatarParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, setAvatar, arg.ID, arg.Avatar, arg.ActionSeq)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const spendStatPoints = `-- name: SpendStatPoints :one
UPDATE app.players
SET stat_energy  = stat_energy  + $2,
    stat_attack  = stat_attack  + $3,
    stat_defense = stat_defense + $4,
    stat_points_unspent = stat_points_unspent - $5,
    action_seq   = $6
WHERE id = $1 AND stat_points_unspent >= $5
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs
`

type SpendStatPointsParams struct {
	ID                uuid.UUID
	StatEnergy        int32
	StatAttack        int32
	StatDefense       int32
	StatPointsUnspent int32
	ActionSeq         int64
}

// Spends level-up points. The WHERE clause carries the affordability check, so
// the balance cannot go negative even under a concurrent double-tap.
func (q *Queries) SpendStatPoints(ctx context.Context, arg SpendStatPointsParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, spendStatPoints,
		arg.ID,
		arg.StatEnergy,
		arg.StatAttack,
		arg.StatDefense,
		arg.StatPointsUnspent,
		arg.ActionSeq,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const touchPlayerSeen = `-- name: TouchPlayerSeen :exec
UPDATE app.players SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchPlayerSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchPlayerSeen, id)
	return err
}

const touchPlayersSeen = `-- name: TouchPlayersSeen :exec
WITH seen AS (
    UPDATE app.players SET last_seen_at = now() WHERE id = ANY($1::uuid[]) RETURNING id
)
INSERT INTO app.player_days (player_id, day)
SELECT id, (now() AT TIME ZONE 'UTC')::date FROM seen
ON CONFLICT DO NOTHING
`

// Writes back a whole batch of players the presence registry has heard from.
//
// This is what finally makes the comment in admin.sql true. last_seen_at was
// only ever written as a side effect of the ~18 queries that MUTATE something,
// so a player who opened the game, read their estates and put the phone down
// was never recorded as active at all, and every "actives" number undercounted
// everyone who was merely looking. The registry now records every authenticated
// request in memory and flushes the set here once every thirty seconds -- one
// statement regardless of how many players are online, instead of one write per
// request.
//
// The same statement records the day in app.player_days, so "who played on the
// 3rd" is kept after last_seen_at has moved on: the active series and retention
// read that, and a flush that cannot write one cannot write the other.
func (q *Queries) TouchPlayersSeen(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchPlayersSeen, dollar_1)
	return err
}
