// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shop.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpReroll = `-- name: BumpReroll :one
UPDATE app.shop_state
SET reroll_index = reroll_index + 1,
    purchased_mask = 0
WHERE player_id = $1 AND window_id = $2
RETURNING player_id, window_id, purchased_mask, reroll_index, luck_bp
`

type BumpRerollParams struct {
	PlayerID uuid.UUID
	WindowID int64
}

// Advances the reroll and clears what was bought from the shelf it replaced.
//
// The offers are a pure function of (secret, player, window, reroll index), so
// bumping the index puts six DIFFERENT items on the shelf. Carrying the mask
// across that leaves a slot unbuyable for the rest of the window while showing
// an item nobody has bought: the player rerolls, sees a new sword in slot 3,
// and the shop insists they already own it. The mask still resets on a new
// window, which UpsertShopWindow does.
func (q *Queries) BumpReroll(ctx context.Context, arg BumpRerollParams) (AppShopState, error) {
	row := q.db.QueryRow(ctx, bumpReroll, arg.PlayerID, arg.WindowID)
	var i AppShopState
	err := row.Scan(
		&i.PlayerID,
		&i.WindowID,
		&i.PurchasedMask,
		&i.RerollIndex,
		&i.LuckBp,
	)
	return i, err
}

const getShopState = `-- name: GetShopState :one
SELECT player_id, window_id, purchased_mask, reroll_index, luck_bp FROM app.shop_state WHERE player_id = $1
`

func (q *Queries) GetShopState(ctx context.Context, playerID uuid.UUID) (AppShopState, error) {
	row := q.db.QueryRow(ctx, getShopState, playerID)
	var i AppShopState
	err := row.Scan(
		&i.PlayerID,
		&i.WindowID,
		&i.PurchasedMask,
		&i.RerollIndex,
		&i.LuckBp,
	)
	return i, err
}

const lockShopState = `-- name: LockShopState :one
SELECT player_id, window_id, purchased_mask, reroll_index, luck_bp FROM app.shop_state WHERE player_id = $1 FOR UPDATE
`

func (q *Queries) LockShopState(ctx context.Context, playerID uuid.UUID) (AppShopState, error) {
	row := q.db.QueryRow(ctx, lockShopState, playerID)
	var i AppShopState
	err := row.Scan(
		&i.PlayerID,
		&i.WindowID,
		&i.PurchasedMask,
		&i.RerollIndex,
		&i.LuckBp,
	)
	return i, err
}

const markShopSlotPurchased = `-- name: MarkShopSlotPurchased :one
UPDATE app.shop_state
SET purchased_mask = purchased_mask | $2
WHERE player_id = $1
RETURNING player_id, window_id, purchased_mask, reroll_index, luck_bp
`

type MarkShopSlotPurchasedParams struct {
	PlayerID      uuid.UUID
	PurchasedMask int32
}

func (q *Queries) MarkShopSlotPurchased(ctx context.Context, arg MarkShopSlotPurchasedParams) (AppShopState, error) {
	row := q.db.QueryRow(ctx, markShopSlotPurchased, arg.PlayerID, arg.PurchasedMask)
	var i AppShopState
	err := row.Scan(
		&i.PlayerID,
		&i.WindowID,
		&i.PurchasedMask,
		&i.RerollIndex,
		&i.LuckBp,
	)
	return i, err
}

const payForReroll = `-- name: PayForReroll :one
UPDATE app.players
SET diamonds          = diamonds - $1::bigint,
    action_seq        = $2,
    shop_rerolls_day  = $3,
    shop_rerolls_used = $4
WHERE id = $5 AND diamonds >= $1::bigint
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs
`

type PayForRerollParams struct {
	Diamonds    int64
	ActionSeq   int64
	RerollsDay  pgtype.Date
	RerollsUsed int16
	ID          uuid.UUID
}

// Pays for a reroll and advances the counter in one statement. The WHERE is the
// guard: no row comes back if the player cannot afford it, and the window check
// stops a reroll bought in one window from applying to the next.
// The caller counts the reroll on the lord's day from the locked row, and has
// already refused one past the day's cap.
func (q *Queries) PayForReroll(ctx context.Context, arg PayForRerollParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, payForReroll,
		arg.Diamonds,
		arg.ActionSeq,
		arg.RerollsDay,
		arg.RerollsUsed,
		arg.ID,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const upsertShopWindow = `-- name: UpsertShopWindow :one
INSERT INTO app.shop_state (player_id, window_id, purchased_mask, reroll_index, luck_bp)
VALUES ($1, $2, 0, 0, $3)
ON CONFLICT (player_id) DO UPDATE
SET window_id      = EXCLUDED.window_id,
    purchased_mask = CASE WHEN app.shop_state.window_id = EXCLUDED.window_id
                          THEN app.shop_state.purchased_mask ELSE 0 END,
    reroll_index   = CASE WHEN app.shop_state.window_id = EXCLUDED.window_id
                          THEN app.shop_state.reroll_index ELSE 0 END,
    luck_bp        = CASE WHEN app.shop_state.window_id = EXCLUDED.window_id
                          THEN app.shop_state.luck_bp ELSE EXCLUDED.luck_bp END
RETURNING player_id, window_id, purchased_mask, reroll_index, luck_bp
`

type UpsertShopWindowParams struct {
	PlayerID uuid.UUID
	WindowID int64
	LuckBp   int32
}

// Creates the row on first use and resets it whenever the 5-minute window rolls
// over, in one statement so two concurrent requests cannot both "reset" it.
// The luck column is written ONLY when the window turns. Holding it still for
// the life of a window is what makes a shelf immutable: offers are recomputed on
// every read and once more inside Buy, so a luck change taking effect mid-window
// would swap the item under the player's finger.
func (q *Queries) UpsertShopWindow(ctx context.Context, arg UpsertShopWindowParams) (AppShopState, error) {
	row := q.db.QueryRow(ctx, upsertShopWindow, arg.PlayerID, arg.WindowID, arg.LuckBp)
	var i AppShopState
	err := row.Scan(
		&i.PlayerID,
		&i.WindowID,
		&i.PurchasedMask,
		&i.RerollIndex,
		&i.LuckBp,
	)
	return i, err
}
