// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shop.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const getShopState = `-- name: GetShopState :one
SELECT player_id, window_id, purchased_mask, reroll_index FROM app.shop_state WHERE player_id = $1
`

func (q *Queries) GetShopState(ctx context.Context, playerID uuid.UUID) (AppShopState, error) {
	row := q.db.QueryRow(ctx, getShopState, playerID)
	var i AppShopState
	err := row.Scan(
		&i.PlayerID,
		&i.WindowID,
		&i.PurchasedMask,
		&i.RerollIndex,
	)
	return i, err
}

const lockShopState = `-- name: LockShopState :one
SELECT player_id, window_id, purchased_mask, reroll_index FROM app.shop_state WHERE player_id = $1 FOR UPDATE
`

func (q *Queries) LockShopState(ctx context.Context, playerID uuid.UUID) (AppShopState, error) {
	row := q.db.QueryRow(ctx, lockShopState, playerID)
	var i AppShopState
	err := row.Scan(
		&i.PlayerID,
		&i.WindowID,
		&i.PurchasedMask,
		&i.RerollIndex,
	)
	return i, err
}

const markShopSlotPurchased = `-- name: MarkShopSlotPurchased :one
UPDATE app.shop_state
SET purchased_mask = purchased_mask | $2
WHERE player_id = $1
RETURNING player_id, window_id, purchased_mask, reroll_index
`

type MarkShopSlotPurchasedParams struct {
	PlayerID      uuid.UUID
	PurchasedMask int32
}

func (q *Queries) MarkShopSlotPurchased(ctx context.Context, arg MarkShopSlotPurchasedParams) (AppShopState, error) {
	row := q.db.QueryRow(ctx, markShopSlotPurchased, arg.PlayerID, arg.PurchasedMask)
	var i AppShopState
	err := row.Scan(
		&i.PlayerID,
		&i.WindowID,
		&i.PurchasedMask,
		&i.RerollIndex,
	)
	return i, err
}

const upsertShopWindow = `-- name: UpsertShopWindow :one
INSERT INTO app.shop_state (player_id, window_id, purchased_mask, reroll_index)
VALUES ($1, $2, 0, 0)
ON CONFLICT (player_id) DO UPDATE
SET window_id      = EXCLUDED.window_id,
    purchased_mask = CASE WHEN app.shop_state.window_id = EXCLUDED.window_id
                          THEN app.shop_state.purchased_mask ELSE 0 END,
    reroll_index   = CASE WHEN app.shop_state.window_id = EXCLUDED.window_id
                          THEN app.shop_state.reroll_index ELSE 0 END
RETURNING player_id, window_id, purchased_mask, reroll_index
`

type UpsertShopWindowParams struct {
	PlayerID uuid.UUID
	WindowID int64
}

// Creates the row on first use and resets it whenever the 5-minute window rolls
// over, in one statement so two concurrent requests cannot both "reset" it.
func (q *Queries) UpsertShopWindow(ctx context.Context, arg UpsertShopWindowParams) (AppShopState, error) {
	row := q.db.QueryRow(ctx, upsertShopWindow, arg.PlayerID, arg.WindowID)
	var i AppShopState
	err := row.Scan(
		&i.PlayerID,
		&i.WindowID,
		&i.PurchasedMask,
		&i.RerollIndex,
	)
	return i, err
}
