// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: soldiers.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const buySoldierSlot = `-- name: BuySoldierSlot :one
UPDATE app.players
SET soldier_slots = soldier_slots + 1,
    gold = gold - $2,
    action_seq = $3
WHERE id = $1 AND gold >= $2 AND soldier_slots = $4
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs
`

type BuySoldierSlotParams struct {
	ID           uuid.UUID
	Gold         int64
	ActionSeq    int64
	SoldierSlots int32
}

func (q *Queries) BuySoldierSlot(ctx context.Context, arg BuySoldierSlotParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, buySoldierSlot,
		arg.ID,
		arg.Gold,
		arg.ActionSeq,
		arg.SoldierSlots,
	)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const claimFreeRecruit = `-- name: ClaimFreeRecruit :one
UPDATE app.players
SET free_recruit_claimed = true, action_seq = $2
WHERE id = $1 AND free_recruit_claimed = false
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs
`

type ClaimFreeRecruitParams struct {
	ID        uuid.UUID
	ActionSeq int64
}

func (q *Queries) ClaimFreeRecruit(ctx context.Context, arg ClaimFreeRecruitParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, claimFreeRecruit, arg.ID, arg.ActionSeq)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const claimFreeSlot = `-- name: ClaimFreeSlot :one
UPDATE app.players
SET soldier_slots = soldier_slots + 1,
    free_slot_claimed = true,
    action_seq = $2
WHERE id = $1 AND free_slot_claimed = false AND soldier_slots = 0
RETURNING id, username, display_name, level, xp, gold, treasury_gold, diamonds, energy_milli, energy_updated_at, stat_energy, stat_attack, stat_defense, stat_points_unspent, shield_until, action_seq, state, reset_offset_minutes, created_at, last_seen_at, soldier_slots, free_slot_claimed, free_recruit_claimed, is_bot, tax_milli_accrued, tax_updated_at, kingdom_id, kingdom_role, kingdom_joined_at, kingdom_donated_total, kingdom_favour, kingdom_rep_today, kingdom_donated_today, kingdom_day, avatar, tax_milli_per_hour, tax_unlogged, luck_bp, luck_expires_at, xp_boost_bp, xp_boost_expires_at, daily_streak, daily_claimed_on, might, legacy, kingdom_left_at, diamond_debt, refills_day, refills_used, boost_until, cos_frame, cos_title, cos_color, cos_crest, mail_bc_seen, vip_points, patron_until, steward_owned, bag_bonus, stipend_until, stipend_claimed, stipend_ref, vip_gift_on, shop_rerolls_day, shop_rerolls_used, storehouse_milli, storehouse_at, storehouse_cap_milli, cart_stock, cart_at, carts_opened, calendar_pos, calendar_cycle, frenzy_meter_milli, frenzy_last_at, frenzy_until, frenzy_energy_left, frenzy_day, frenzy_used, frenzy_ready_at, road_claimed, guide_step, guide_done_at, guide_skipped, winback_at, winback_tier, arena_day, arena_fights_used, arena_refresh_used, arena_first_win_on, bounty_day, bounty_placed, chat_muted_until, chat_strikes, chat_strike_at, chat_rules_version, chat_seen_seq, gift_day, gifts_taken, friend_req_day, friend_reqs, spy_day, spy_used, aid_day, aid_given, aid_asked_at, notif_raid, notif_chat, notif_mail, notif_events, notif_friends, quiet_from, quiet_to, privacy_profile, privacy_online, privacy_requests, talent_respecs
`

type ClaimFreeSlotParams struct {
	ID        uuid.UUID
	ActionSeq int64
}

func (q *Queries) ClaimFreeSlot(ctx context.Context, arg ClaimFreeSlotParams) (AppPlayer, error) {
	row := q.db.QueryRow(ctx, claimFreeSlot, arg.ID, arg.ActionSeq)
	var i AppPlayer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.Gold,
		&i.TreasuryGold,
		&i.Diamonds,
		&i.EnergyMilli,
		&i.EnergyUpdatedAt,
		&i.StatEnergy,
		&i.StatAttack,
		&i.StatDefense,
		&i.StatPointsUnspent,
		&i.ShieldUntil,
		&i.ActionSeq,
		&i.State,
		&i.ResetOffsetMinutes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SoldierSlots,
		&i.FreeSlotClaimed,
		&i.FreeRecruitClaimed,
		&i.IsBot,
		&i.TaxMilliAccrued,
		&i.TaxUpdatedAt,
		&i.KingdomID,
		&i.KingdomRole,
		&i.KingdomJoinedAt,
		&i.KingdomDonatedTotal,
		&i.KingdomFavour,
		&i.KingdomRepToday,
		&i.KingdomDonatedToday,
		&i.KingdomDay,
		&i.Avatar,
		&i.TaxMilliPerHour,
		&i.TaxUnlogged,
		&i.LuckBp,
		&i.LuckExpiresAt,
		&i.XpBoostBp,
		&i.XpBoostExpiresAt,
		&i.DailyStreak,
		&i.DailyClaimedOn,
		&i.Might,
		&i.Legacy,
		&i.KingdomLeftAt,
		&i.DiamondDebt,
		&i.RefillsDay,
		&i.RefillsUsed,
		&i.BoostUntil,
		&i.CosFrame,
		&i.CosTitle,
		&i.CosColor,
		&i.CosCrest,
		&i.MailBcSeen,
		&i.VipPoints,
		&i.PatronUntil,
		&i.StewardOwned,
		&i.BagBonus,
		&i.StipendUntil,
		&i.StipendClaimed,
		&i.StipendRef,
		&i.VipGiftOn,
		&i.ShopRerollsDay,
		&i.ShopRerollsUsed,
		&i.StorehouseMilli,
		&i.StorehouseAt,
		&i.StorehouseCapMilli,
		&i.CartStock,
		&i.CartAt,
		&i.CartsOpened,
		&i.CalendarPos,
		&i.CalendarCycle,
		&i.FrenzyMeterMilli,
		&i.FrenzyLastAt,
		&i.FrenzyUntil,
		&i.FrenzyEnergyLeft,
		&i.FrenzyDay,
		&i.FrenzyUsed,
		&i.FrenzyReadyAt,
		&i.RoadClaimed,
		&i.GuideStep,
		&i.GuideDoneAt,
		&i.GuideSkipped,
		&i.WinbackAt,
		&i.WinbackTier,
		&i.ArenaDay,
		&i.ArenaFightsUsed,
		&i.ArenaRefreshUsed,
		&i.ArenaFirstWinOn,
		&i.BountyDay,
		&i.BountyPlaced,
		&i.ChatMutedUntil,
		&i.ChatStrikes,
		&i.ChatStrikeAt,
		&i.ChatRulesVersion,
		&i.ChatSeenSeq,
		&i.GiftDay,
		&i.GiftsTaken,
		&i.FriendReqDay,
		&i.FriendReqs,
		&i.SpyDay,
		&i.SpyUsed,
		&i.AidDay,
		&i.AidGiven,
		&i.AidAskedAt,
		&i.NotifRaid,
		&i.NotifChat,
		&i.NotifMail,
		&i.NotifEvents,
		&i.NotifFriends,
		&i.QuietFrom,
		&i.QuietTo,
		&i.PrivacyProfile,
		&i.PrivacyOnline,
		&i.PrivacyRequests,
		&i.TalentRespecs,
	)
	return i, err
}

const deleteSoldier = `-- name: DeleteSoldier :exec
DELETE FROM app.soldiers WHERE id = $1 AND player_id = $2
`

type DeleteSoldierParams struct {
	ID       uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) DeleteSoldier(ctx context.Context, arg DeleteSoldierParams) error {
	_, err := q.db.Exec(ctx, deleteSoldier, arg.ID, arg.PlayerID)
	return err
}

const getSoldier = `-- name: GetSoldier :one
SELECT id, player_id, slot_index, type_id, tier, level, name, recruited_at, rolled_config_version FROM app.soldiers WHERE id = $1 AND player_id = $2
`

type GetSoldierParams struct {
	ID       uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) GetSoldier(ctx context.Context, arg GetSoldierParams) (AppSoldier, error) {
	row := q.db.QueryRow(ctx, getSoldier, arg.ID, arg.PlayerID)
	var i AppSoldier
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.SlotIndex,
		&i.TypeID,
		&i.Tier,
		&i.Level,
		&i.Name,
		&i.RecruitedAt,
		&i.RolledConfigVersion,
	)
	return i, err
}

const listItemsForSoldiers = `-- name: ListItemsForSoldiers :many
SELECT id, player_id, def_id, slot, tier, ilvl, quality_pct, masterwork, attack, defense, speed, equipped_on_hero, equipped_soldier_id, acquired_at, acquired_from, rolled_config_version FROM app.player_items
WHERE player_id = $1 AND equipped_soldier_id IS NOT NULL
`

func (q *Queries) ListItemsForSoldiers(ctx context.Context, playerID uuid.UUID) ([]AppPlayerItem, error) {
	rows, err := q.db.Query(ctx, listItemsForSoldiers, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPlayerItem{}
	for rows.Next() {
		var i AppPlayerItem
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.DefID,
			&i.Slot,
			&i.Tier,
			&i.Ilvl,
			&i.QualityPct,
			&i.Masterwork,
			&i.Attack,
			&i.Defense,
			&i.Speed,
			&i.EquippedOnHero,
			&i.EquippedSoldierID,
			&i.AcquiredAt,
			&i.AcquiredFrom,
			&i.RolledConfigVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSoldiers = `-- name: ListSoldiers :many
SELECT id, player_id, slot_index, type_id, tier, level, name, recruited_at, rolled_config_version FROM app.soldiers WHERE player_id = $1 ORDER BY slot_index
`

func (q *Queries) ListSoldiers(ctx context.Context, playerID uuid.UUID) ([]AppSoldier, error) {
	rows, err := q.db.Query(ctx, listSoldiers, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSoldier{}
	for rows.Next() {
		var i AppSoldier
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.SlotIndex,
			&i.TypeID,
			&i.Tier,
			&i.Level,
			&i.Name,
			&i.RecruitedAt,
			&i.RolledConfigVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSoldier = `-- name: LockSoldier :one
SELECT id, player_id, slot_index, type_id, tier, level, name, recruited_at, rolled_config_version FROM app.soldiers WHERE id = $1 AND player_id = $2 FOR UPDATE
`

type LockSoldierParams struct {
	ID       uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) LockSoldier(ctx context.Context, arg LockSoldierParams) (AppSoldier, error) {
	row := q.db.QueryRow(ctx, lockSoldier, arg.ID, arg.PlayerID)
	var i AppSoldier
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.SlotIndex,
		&i.TypeID,
		&i.Tier,
		&i.Level,
		&i.Name,
		&i.RecruitedAt,
		&i.RolledConfigVersion,
	)
	return i, err
}

const releaseSoldierItems = `-- name: ReleaseSoldierItems :exec
UPDATE app.player_items SET equipped_soldier_id = NULL
WHERE player_id = $1 AND equipped_soldier_id = $2
`

type ReleaseSoldierItemsParams struct {
	PlayerID          uuid.UUID
	EquippedSoldierID *uuid.UUID
}

// Dismissing a soldier must not destroy its gear; the items return to the bag.
func (q *Queries) ReleaseSoldierItems(ctx context.Context, arg ReleaseSoldierItemsParams) error {
	_, err := q.db.Exec(ctx, releaseSoldierItems, arg.PlayerID, arg.EquippedSoldierID)
	return err
}

const setSoldierEquipped = `-- name: SetSoldierEquipped :exec
UPDATE app.player_items
SET equipped_soldier_id = $3, equipped_on_hero = false
WHERE id = $1 AND player_id = $2
`

type SetSoldierEquippedParams struct {
	ID                uuid.UUID
	PlayerID          uuid.UUID
	EquippedSoldierID *uuid.UUID
}

func (q *Queries) SetSoldierEquipped(ctx context.Context, arg SetSoldierEquippedParams) error {
	_, err := q.db.Exec(ctx, setSoldierEquipped, arg.ID, arg.PlayerID, arg.EquippedSoldierID)
	return err
}

const setSoldierLevel = `-- name: SetSoldierLevel :one
UPDATE app.soldiers SET level = $3 WHERE id = $1 AND player_id = $2 RETURNING id, player_id, slot_index, type_id, tier, level, name, recruited_at, rolled_config_version
`

type SetSoldierLevelParams struct {
	ID       uuid.UUID
	PlayerID uuid.UUID
	Level    int32
}

func (q *Queries) SetSoldierLevel(ctx context.Context, arg SetSoldierLevelParams) (AppSoldier, error) {
	row := q.db.QueryRow(ctx, setSoldierLevel, arg.ID, arg.PlayerID, arg.Level)
	var i AppSoldier
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.SlotIndex,
		&i.TypeID,
		&i.Tier,
		&i.Level,
		&i.Name,
		&i.RecruitedAt,
		&i.RolledConfigVersion,
	)
	return i, err
}

const setSoldierTier = `-- name: SetSoldierTier :one
UPDATE app.soldiers
SET tier = $1, rolled_config_version = $2
WHERE id = $3 AND player_id = $4
RETURNING id, player_id, slot_index, type_id, tier, level, name, recruited_at, rolled_config_version
`

type SetSoldierTierParams struct {
	Tier                string
	RolledConfigVersion int32
	ID                  uuid.UUID
	PlayerID            uuid.UUID
}

// A reroll: the soldier keeps its id, slot, type and gear, and takes a new tier.
func (q *Queries) SetSoldierTier(ctx context.Context, arg SetSoldierTierParams) (AppSoldier, error) {
	row := q.db.QueryRow(ctx, setSoldierTier,
		arg.Tier,
		arg.RolledConfigVersion,
		arg.ID,
		arg.PlayerID,
	)
	var i AppSoldier
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.SlotIndex,
		&i.TypeID,
		&i.Tier,
		&i.Level,
		&i.Name,
		&i.RecruitedAt,
		&i.RolledConfigVersion,
	)
	return i, err
}

const unequipSoldierSlot = `-- name: UnequipSoldierSlot :exec
UPDATE app.player_items
SET equipped_soldier_id = NULL
WHERE player_id = $1 AND equipped_soldier_id = $2 AND slot = $3
`

type UnequipSoldierSlotParams struct {
	PlayerID          uuid.UUID
	EquippedSoldierID *uuid.UUID
	Slot              string
}

// Frees the soldier's slot before the new item goes in, so the unique index
// never sees two items in one slot even transiently.
func (q *Queries) UnequipSoldierSlot(ctx context.Context, arg UnequipSoldierSlotParams) error {
	_, err := q.db.Exec(ctx, unequipSoldierSlot, arg.PlayerID, arg.EquippedSoldierID, arg.Slot)
	return err
}

const upsertSoldier = `-- name: UpsertSoldier :one
INSERT INTO app.soldiers (player_id, slot_index, type_id, tier, level, name, rolled_config_version)
VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT (player_id, slot_index) DO UPDATE
SET type_id = EXCLUDED.type_id,
    tier    = EXCLUDED.tier,
    level   = EXCLUDED.level,
    name    = EXCLUDED.name,
    recruited_at = now(),
    rolled_config_version = EXCLUDED.rolled_config_version
RETURNING id, player_id, slot_index, type_id, tier, level, name, recruited_at, rolled_config_version
`

type UpsertSoldierParams struct {
	PlayerID            uuid.UUID
	SlotIndex           int32
	TypeID              string
	Tier                string
	Level               int32
	Name                string
	RolledConfigVersion int32
}

// Recruiting into an occupied slot replaces the occupant, so this is an upsert
// rather than an insert.
func (q *Queries) UpsertSoldier(ctx context.Context, arg UpsertSoldierParams) (AppSoldier, error) {
	row := q.db.QueryRow(ctx, upsertSoldier,
		arg.PlayerID,
		arg.SlotIndex,
		arg.TypeID,
		arg.Tier,
		arg.Level,
		arg.Name,
		arg.RolledConfigVersion,
	)
	var i AppSoldier
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.SlotIndex,
		&i.TypeID,
		&i.Tier,
		&i.Level,
		&i.Name,
		&i.RecruitedAt,
		&i.RolledConfigVersion,
	)
	return i, err
}
